### ISSUE TITLE
cron list / cron run 

### ISSUE THREAD

**Issue by Dx3webs** [netz98/n98-magerun2#1028]
I frequently see this when calling up a cron list or trying to run a specific cron job

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to N98\Magento\Command\System\Cron\AbstractCronCommand::getSchedule() must be of the type array, bool given, called in phar:///var/www/vhosts/m2-proam.magedemo.co.uk/httpdocs/n98-magerun2.phar/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php on line 106 and defined in phar:///var/www/vhosts/m2-proam.magedemo.co.uk/httpdocs/n98-magerun2.phar/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php:141

Anyone know what it refers to?

n98-magerun2 5.2.0
PHP 7.4.30
Magento CLI 2.4.3

**Comment by cmuench** [comment]
@Dx3webs Is that a standard cronjob? If, yes ... pleaseyou tell us the name.

**Comment by cmuench** [comment]
ok. That's interesting. We run this command via an automatic test in a Magento 2.4.3-p2 without any issue.

Example: https://github.com/netz98/n98-magerun2/runs/7691855089

I hope we can reproduce the issue.

**Comment by ktomk** [comment]
Wasn't there a default cronjob schedule configuration in Magento some time that didn't had an array but just a scalar to signal either its running every minute or is disabled? Just guessing terrain here, have not even looked in the code.

**Comment by cmuench** [comment]
Seems that it depends on some data. I will check if the job configuration is empty. That should fix the issue.

**Comment by cmuench** [comment]
Issues should be fixed.
You can try it by updating with `n98-magerun2.phar self-update --unstable`.

**Comment by Dx3webs** [comment]
amazing.. confirmed working

**Comment by cmuench** [comment]
Will be released with v5.3.0.
