### ISSUE TITLE
GPG key expired

### ISSUE THREAD

**Issue by tdgroot** [netz98/n98-magerun2#1060]
FYI: the GPG key used to generate phar signatures has expired:
```
-> gpg --verify sig.pgp n98-magerun2.phar
gpg: Signature made wo 19 okt 2022 18:20:08 CEST
gpg:                using RSA key EF7B19538B65EA5BE3F60AB9E92FF862BCBFE89A
gpg: Good signature from "Christian Münch - netz98 <c.muench@netz98.de>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: EF7B 1953 8B65 EA5B E3F6  0AB9 E92F F862 BCBF E89A
```

**Comment by cmuench** [comment]
Thanks for the info. Will try to update it.

**Comment by cmuench** [comment]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/211294/201531485-3557c308-4288-457c-9124-fdccd3e790c1.png">

I just checked the latest phar file. Looks good on my machine.

**Comment by cmuench** [comment]
Maybe the key was not send to key servers. Just did it.

**Comment by tdgroot** [comment]
Yeah looks good now, thanks :)
