### ISSUE TITLE
can we remove drop table statements from db:dump command?

### ISSUE THREAD

**Issue by ioweb-gr** [netz98/n98-magerun2#1094]
## Your Question
I am experimenting with the db:dump command and I was wondering if it's possible to create a dump for a specific table without the drop table statement. 

For example  

`n98-magerun2.phar db:dump --include catalog_category_product`

will add this statement

```
DROP TABLE IF EXISTS `catalog_category_product`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `catalog_category_product` (
  `entity_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Entity ID',
  `category_id` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'Category ID',
  `product_id` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'Product ID',
  `position` int(11) NOT NULL DEFAULT 0 COMMENT 'Position',
  PRIMARY KEY (`entity_id`,`category_id`,`product_id`),
  UNIQUE KEY `CATALOG_CATEGORY_PRODUCT_CATEGORY_ID_PRODUCT_ID` (`category_id`,`product_id`),
  KEY `CATALOG_CATEGORY_PRODUCT_PRODUCT_ID` (`product_id`),
  CONSTRAINT `CAT_CTGR_PRD_CTGR_ID_CAT_CTGR_ENTT_ENTT_ID` FOREIGN KEY (`category_id`) REFERENCES `catalog_category_entity` (`entity_id`) ON DELETE CASCADE,
  CONSTRAINT `CAT_CTGR_PRD_PRD_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`product_id`) REFERENCES `catalog_product_entity` (`entity_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=35847771 DEFAULT CHARSET=utf8 COMMENT='Catalog Product To Category Linkage Table';
/*!40101 SET character_set_client = @saved_cs_client */;

```

I would like to avoid dropping the table and only insert the rows

* Source File:
* Line(s):
* Question:

**Comment by cmuench** [comment]
@ioweb-gr it's currently not implemented. This command is only a wrapper of mysqldump.
I checked the options and it should be possible by adding `--no-create-info` option.
So we could extend our command with the same option.

**Comment by cmuench** [comment]
@ioweb-gr A quick workaround...
You can use the `--only-command` option to print the mysqldump command and then add the `--no-create-info` manually to it.

**Comment by ioweb-gr** [comment]
@cmuench Cool thank you :) I'll try modifying the command
