### ISSUE TITLE
dev:console on Adobe Cloud hosting

### ISSUE THREAD

**Issue by plel** [netz98/n98-magerun2#1096]
## Describe the bug

When using `magerun2 dev:console` on the adobe hosted Magento cloud the readonly file system will prevent successful starting with message

```
  User Notice: Writing to directory /app/name/.config/psysh is not allowed. in phar:///app/name/bin/n98-magerun2/vendor/psy/psysh/src/ConfigPaths.php on line 362
```
 
## Expected behaviour

Successful start of the dev console

## Steps to reproduce the issue

1. open up shell to magento cloud
2. try starting the dev:console by using the `dev:console`command on magerun

## Technical details

- Magento cloud setup with readonly file system

## Possible Fix

There might be an workaround to change the path by using an env variable
- ENV Variable "PSYSH_CONFIG"

**Comment by cmuench** [comment]
@plel Did some tests. Psysg tries to load/write the history file from different configuation locations.
If the configuration directory is readonly then a "user notice" is triggered by Psysh.
That's not so nice.

In Magerun v6.1.1 the notice lead into an Exception and stops the execution flow.
In the upcoming v7.0.0 the notice will be written to the console but does NOT stop execution flow.

In the PR #1097 I will additionally supress the warning. The warning does not harm anything. The console works like a charm if there is no history file.

**Comment by cmuench** [comment]
@plel Can you test with current develop version again?

**Comment by plel** [comment]
Seems to work fine, tested version tag 'n98-magerun2 7.0.0-dev (commit: 2ed1b2b)'

**Comment by cmuench** [comment]
@plel I close this issue.
