### ISSUE TITLE
Porting command: local-config:generate

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#110]
Generates local.xml config

**Comment by cmuench** [comment]
Obsolete.

**Comment by mmenozzi** [comment]
Why you don't want to port this?

**Comment by cmuench** [comment]
There is no local.xml in Magento 2.
Magento 2 offers this feature with setup:config:set command.
http://devdocs.magento.com/guides/v2.2/install-gde/install/cli/install-cli-subcommands-deployment.html

**Comment by mmenozzi** [comment]
Didn't know thank you!
