### ISSUE TITLE
Multiple similar PS4 namespaces will replace each other

### ISSUE THREAD

**Issue by Pacolu** [netz98/n98-magerun2#1144]
## Describe the bug

I have a case, where I have two Magerun plugins, which are using the same Namespace. Those namespaces are defined in the config yamls.
`autoloaders_psr4:
  VENDOR\MODULE\: %module%/src
`

During the config merge, one Namespace will be replaced and the config cannot find the classes from the other plugin.
It might be an edge case, but it worked up to version 7. Probably because the Magento autoloader was also loaded, which used the autoload entries in my composer.json.

## Expected behavior

Both Namespace directories are used.

## Steps to reproduce the issue

Create two magerun plugins, with the same namespace definition for PSR4

## Technical details

- MacOS
- PHP 8
- Magerun 7

## Possible Fix

Maybe add some kind of list compatibility so we can use multiple paths for a namespace.

**Comment by cmuench** [comment]
Fix will be deployed with 7.0.1.
