### ISSUE TITLE
Cannot use downgrade command on v7.0.0

### ISSUE THREAD

**Issue by Axel29** [netz98/n98-magerun2#1147]
## Describe the bug

The `sys:setup:downgrade-versions` command throws a Fatal Error on the latest version with Magento 2.4.3-p3:

> PHP Fatal error:  Uncaught TypeError: Return value of "N98\Magento\Command\System\Setup\DowngradeVersionsCommand::execute()" must be of the type int, "null" returned. in phar:///app/n98-magerun2.phar/vendor/symfony/console/Command/Command.php:301
> Stack trace:
> #0 phar:///app/n98-magerun2.phar/src/N98/Magento/Command/AbstractMagentoCommand.php(249): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #1 phar:///app/n98-magerun2.phar/vendor/symfony/console/Application.php(1058): N98\Magento\Command\AbstractMagentoCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #2 phar:///app/n98-magerun2. in phar:///app/n98-magerun2.phar/vendor/symfony/console/Command/Command.php on line 301

## Expected behaviour

Modules downgraded successfully

## Steps to reproduce the issue

1. Run `sys:setup:downgrade-versions` with Magento 2.4.3-p3 and n98-magerun2.phar on version 7.0.0.

## Technical details

- Host Machine OS (Windows/Linux/Mac): Ubuntu
- PHP 7.4
- n98-magerun2.phar 7.0.0
- Magento 2.4.3-p3

**Comment by cmuench** [comment]
@cmuench Problem is fixed and will be release in the next upcoming bugfix release 7.0.1.
In the meantime you can update to the develop version with `n98-magerun2.phar self-update --unstable` to get the fix.

**Comment by Axel29** [comment]
> @Axel29 Problem is fixed and will be release in the next upcoming bugfix release 7.0.1. In the meantime you can update to the develop version with `n98-magerun2.phar self-update --unstable` to get the fix.

Thanks, that was fast :)
