### ISSUE TITLE
Capturing the command output via Robo does not work anymore (regression in 7.0.0)

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#1149]
We are using Robo v4 and n98-magerun2 in the following way:

    private function magerunTwoWithResult(string $command): string
    {
        return $this->taskExec(sprintf('php8.1 %s %s', '/usr/local/bin/n98-magerun2', $command))
            ->printOutput(false)
            ->run()
            ->getMessage();
    }

## Expected behaviour

When calling the above function in the RoboFile for example with `deploy:mode:show` we get the output (verified with 6.1.1), but with 7.0.0 we get an empty result. Robo v3.0.10 and magerun2 v7.0.0 show the same problem.

## Steps to reproduce the issue

1. Execute the above code in a robo file
2. result is not empty

## Workaround

When calling bin/magento instead of magerun2 it works.

Was there anything changed in the TTY handling or something like this which could cause this issue?

**Comment by cmuench** [comment]
@amenk yes, we call all Core commands now as sub-process (via Symfony Process).
Can you provide a small sample?
Sadly I will not be available until next week to do serious work on n98-magerun2 to fix this issue.

**Comment by cmuench** [comment]
The output is passed to the output of the command.

```php
$process->run(function ($type, $buffer) use ($output) {
    $output->write($buffer);
});
```

**Comment by cmuench** [comment]
I just did a test in the Magerun dev box with this RoboFile.

```php
<?php
/**
 * This is project's console commands configuration for Robo task runner.
 *
 * @see https://robo.li/
 */
class RoboFile extends \Robo\Tasks
{
    private function magerunTwoWithResult(string $command): string
    {
        return $this->taskExec(sprintf('php8.2 %s %s', './n98-magerun2.phar --root-dir=/opt/magento-test-environments/magento_2_4_6/', $command))
            ->printOutput(false)
            ->run()
            ->getMessage();
    }

    public function deployModeShow()
    {
        return $this->magerunTwoWithResult('deploy:mode:show');
    }
}
```

I did a test with "bin/n98-magerun2" and the phar file.
Both are working.

What I currently see is that we do not prepend the PHP interpreter to the bin/magento call.
Maybe that's an issue if several PHP versions are used.

**Comment by amenk** [comment]
Not sure if the output comes from robo or from magerun. Can you try

```var_dump( $this->magerunTwoWithResult('deploy:mode:show') );```

**Comment by ktomk** [comment]
@amenk: Please try and see if it works:

~~~
sprintf('php8.1 %s %s | cat', ...
                      ##### 
~~~

and please share which operating system and shell.

This might be similar: https://github.com/composer/composer/issues/9454#issuecomment-725357457

**Comment by cmuench** [comment]
@ktomk Good finding. We have also a similar issue for the db dump in #929 which is a sub-process like here.

**Comment by amenk** [comment]
@ktomk 
`| cat` does not help.
default shell is bash on Ubuntu 22.04

**Comment by ktomk** [comment]
@amenk Thanks, that's what I thought. Can you try to invoke robo prefixed with the `unbuffer` command (part of the `expect` package)? If that works, this strongly points to TTY handling of the Symfony Console component in use and a potential solution could be similar as in Composer.

**Comment by cmuench** [comment]
We use the TTY mode of the Symfony Process depends if the tool is started interactive or non-interactive.
https://symfony.com/doc/5.4/components/process.html#using-tty-and-pty-modes

There is also a Pty Mode. I have not tested this, because I had not had any issues.

**Comment by cmuench** [comment]
I changed `setTty` to `setPty`. Both work in the debian based docker container. Would be interesting to know where the environment differs. Currently I am not able to reproduce the issue.

**Comment by cmuench** [comment]
@ktomk do you think we handle that in n98-magerun2 in any way?

**Comment by cmuench** [comment]
@amenk have you tried with `--no-interaction` option?

**Comment by amenk** [comment]
`--no-interaction` works like a charm and makes a lot of sense in this case.
We can go with changing our scripts in this way.

From my point of view we could close this issue.
Eventually it should be added to some release notes or so...

Thank you very much!
