### ISSUE TITLE
Clear media cache

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#1192]
## Feature description

Add a command to clear this cache

![Media Cache Clear](https://user-images.githubusercontent.com/1087128/233371331-33ef745e-4434-4611-af68-0deac3489076.png)

## Problem and motivation

Avoid going to the admin panel

## Is this something you're interested in working on

maybe

**Comment by amenk** [comment]
I am wondering if this is as simple as deleting the according folder?

**Comment by cmuench** [comment]
@amenk maybe but we have to check first if Adobe Commerce supports other storages like S3.
