### ISSUE TITLE
The wget file is n98-magerun version not n98-magerun2 version please change the file

### ISSUE THREAD

**Issue by tekodan** [netz98/n98-magerun2#1204]
The wget file is n98-magerun version not n98-magerun2 version please change the file, thanks

**Comment by cmuench** [comment]
@tekodan Can you comment here the `wget` command you run?

**Comment by tekodan** [comment]
this is wget https://files.magerun.net/n98-magerun2.phar, this is the cammand in te installation In the README.md file

**Comment by tekodan** [comment]
you have reason, my bad sorry, maybe i puzzled with another versions, thanks for early help
