### ISSUE TITLE
When run bin/n98-magerun2.phar  sys:setup:downgrade-versions it throws Deprecated: version_compare(): Passing null to parameter #2

### ISSUE THREAD

**Issue by mudithafn** [netz98/n98-magerun2#1206]
## Describe the bug
I am upgrading from php 2.4.4-p2 to php 2.4.6 latest release. 
As a part of upgrade, I am upgrading the n98-magerun2 from 5.1.0 to 7.0.3 

After the upgrade, I see following error occurring when running `bin/n98-magerun2.phar  sys:setup:downgrade-versions`

`Deprecated: version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated in phar:///app/bin/n98-magerun2.phar/src/N98/Magento/Command/System/Setup/DowngradeVersionsCommand.php on line 121`

I have PHP 8.1.17 

## Expected behaviour

Downgrade should downgrade the versions matching to Database versions without generating Deprecated version_compare() issue.

## Steps to reproduce the issue

Upgrade the n98-magerun2 to the latest version (7.0.3 )
Run `bin/n98-magerun2.phar  sys:setup:downgrade-versions`

## Technical details

- Host Machine OS: Ubuntu / Mac

## Additional context

**Comment by cmuench** [comment]
@mudithafn I did a small fix but I have no data to verify it.
You can test it by downloading the generated phar file: https://nightly.link/netz98/n98-magerun2/actions/artifacts/710361299.zip (phar is in the zip file)
