### ISSUE TITLE
Remove non-routes from route:list

### ISSUE THREAD

**Issue by galdiuz** [netz98/n98-magerun2#1304]
## Current Implementation
The `route:list` command currently uses `\Magento\Framework\Module\Dir\Reader->getActionFiles()` to find classes in every module's `Controller` directory. However, all of these classes don't actually represent an actual route, as there can be things like abstract classes, interfaces, or just plain non-action classes.

## Suggested Enhancement
Check each class before including it. This can be done at the start of the foreach in [ListCommand.php](https://github.com/netz98/n98-magerun2/blob/develop/src/N98/Magento/Command/Route/ListCommand.php#L91). Using [is_a($fullActionPath, '\Magento\Framework\App\ActionInterface', true)](https://www.php.net/manual/en/function.is-a.php) to check if the class implements ActionInterface would catch all non-action classes, then reflection could be used to also catch any abstract classes.

## Expected Benefits
`route:list` would no longer list results that are not accessible paths.

**Comment by cmuench** [comment]
Will be released with v7.3.0
