### ISSUE TITLE
Allow to place and n98-magerun2.phar directly in a Magento installation without `--root-dir` option

### ISSUE THREAD

**Issue by kanevbg** [netz98/n98-magerun2#1305]
Magento version: 2.4.6
magerun version: 7.1.0

Command used:
```
php81 -c ~/deps/shared/php-cli.ini -d memory_limit=-1 ~/deps/current/bin/n98-magerun2.phar db:query "SHOW TABLES;" -v
```

Exception trace:
```
at phar:///home/project/deps/releases/6a70878_1695663999/bin/n98-magerun2.phar/src/N98/Util/Console/Helper/DatabaseHelper.php:74
 N98\Util\Console\Helper\DatabaseHelper->detectDbSettings() at phar:///home/project/deps/releases/6a70878_1695663999/bin/n98-magerun2.phar/src/N98/Magento/Command/Database/AbstractDatabaseCommand.php:63
 N98\Magento\Command\Database\AbstractDatabaseCommand->detectDbSettings() at phar:///home/project/deps/releases/6a70878_1695663999/bin/n98-magerun2.phar/src/N98/Magento/Command/Database/QueryCommand.php:72
 N98\Magento\Command\Database\QueryCommand->execute() at phar:///home/project/deps/releases/6a70878_1695663999/bin/n98-magerun2.phar/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///home/project/deps/releases/6a70878_1695663999/bin/n98-magerun2.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:249
 N98\Magento\Command\AbstractMagentoCommand->run() at phar:///home/project/deps/releases/6a70878_1695663999/bin/n98-magerun2.phar/vendor/symfony/console/Application.php:1058
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/project/deps/releases/6a70878_1695663999/bin/n98-magerun2.phar/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar:///home/project/deps/releases/6a70878_1695663999/bin/n98-magerun2.phar/src/N98/Magento/Application.php:254
 N98\Magento\Application->doRun() at phar:///home/project/deps/releases/6a70878_1695663999/bin/n98-magerun2.phar/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///home/project/deps/releases/6a70878_1695663999/bin/n98-magerun2.phar/src/N98/Magento/Application.php:363
 N98\Magento\Application->run() at /home/project/deps/releases/6a70878_1695663999/bin/n98-magerun2.phar:8

db:query [--connection CONNECTION] [--only-command] [--] [<query>]
```

related part of env.php:
```
<?php
return [
	// .......
    'db' => [
		'table_prefix' => '',
        'connection' => [
            'default' => [
                'host' => '127.0.0.1:3307',
                'dbname' => 'project',
                'username' => 'project',
                'password' => '***********',
                'model' => 'mysql4',
                'engine' => 'innodb',
                'initStatements' => 'SET NAMES utf8mb3;',
                'active' => '1',
                'driver_options' => [
                    1014 => false
                ],
                'profiler' => [
                    'class' => 'Magento\\Framework\\DB\\Profiler',
                    'enabled' => true
                ]
            ]
		]
    ],
	// ......
];
```

PS: there is "TODO" comment at _src/N98/Util/Console/Helper/DatabaseHelper.php:71_, which may be related:
![image](https://github.com/netz98/n98-magerun2/assets/11477130/3e18c319-9acb-47ca-b46b-638364e3de95)

**Comment by cmuench** [comment]
@kanevbg Can you check if the `sys:info` works?

**Comment by kanevbg** [comment]
@cmuench 

```
php81 -c ~/deps/shared/php-cli.ini -d memory_limit=-1 ~/deps/current/bin/n98-magerun2.phar sys:info -v
In AbstractMagentoCommand.php line 166:
                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  Magento folder could not be detected
```

**Comment by cmuench** [comment]
@could it be that your current working directory is not in the shop project?
If yes, then try to set the root path with the `--root-dir` option.

**Comment by kanevbg** [comment]
Yes, it is. The suggested CLI option solves the main issue, but please consider it work around, as it's causing bad UX. It will help me and thank you for being active on the issue. Here is the output:

```
php81 -c ~/deps/shared/php-cli.ini -d memory_limit=-1 ~/deps/current/bin/n98-magerun2.phar sys:info --root-dir ~/deps/current/ -v
**Magento Core Commands cannot be loaded. Please verify if "bin/magento" is running.**
Run with -vvv option to see the error output.
Only n98-magerun2 commands are available until the issue is fixed.

                              
  Magento System Information  
                              
.... specifics here ....
```

I marked as bold the message above, which is likely a second issue with the concrete work-around.

**Comment by cmuench** [comment]
@kanevbg that's how it's supposed to work. If you are inside the shop it's finding the shop root.
If you are outside the shop, then you can define the root. The tool can work with several installations on your machine. If you have always one installation a solution is to define a bash alias with the root-dir option set.

**Comment by kanevbg** [comment]
Would not you like to work like bin/magento?

**Comment by cmuench** [comment]
@kanevbg n98-magerun2 can execute `bin/magento` command but provide own features.
What's missing?

**Comment by kanevbg** [comment]
I mean that if for `bin/magento` is possible to locate the DOC_ROOT of Magento:
```
[project@srv03 ~]$ php81 -c ~/deps/shared/php-cli.ini -d memory_limit=-1 ~/deps/current/bin/magento app:config:status
Config files are up to date.
```
than it will be practical for us to have the same capability for `bin/n98-magerun2.phar`.
The `--doc-root` argument can still be available.
And one more suggestion - when there is issue with finding the document root, than the tool can advertise it's `--doc-root` option to achieve better UX.

**Comment by cmuench** [comment]
@kanevbg I created a small video which demonstrates the idea behind the tool.
https://www.youtube.com/watch?v=Ob608NnIEKA

**Comment by kanevbg** [comment]
I see your point being that it's a global install, but that's not required, right?
If I put it at bin directory of Magento 2 installation, it will be practical to be able to find the root without requiring me to add --root-dir.
Thanks for your time.

**Comment by cmuench** [comment]
OK. I understand your point here.
Let's see if we can support that. There is also a logic which checks for sub-directories.
List of directories is defined by config (can be extended) https://github.com/netz98/n98-magerun2/blob/7b0e718167add7b0337963f0fae70df320e544bb/config.yaml#L53

I have to check if that can conflict.

**Comment by cmuench** [comment]
@kanevbg I did some experiments and created a PR as draft.
This logic has to be tested very well, because it's changing the behavior.

You can download the phar file (inside the zip) with the changed logic if you want to test:

https://nightly.link/netz98/n98-magerun2/actions/artifacts/952569521.zip

**Comment by kanevbg** [comment]
@cmuench sorry for the late response. I confirmed that the build you provided works as expected.

**Comment by cmuench** [comment]
@kanevbg we will deploy that with the upcoming 7.3.0 release.
