### ISSUE TITLE
"--all" parameter is ignored in customer:delete command

### ISSUE THREAD

**Issue by vncnt-mb** [netz98/n98-magerun2#1359]
## Describe the bug

When you execute the command "./n98-magerun2.phar customer:delete", everything works. Except that if we add the "--all" parameter, even after filling in the appropriate questions (Delete more than 1 customer? & Delete all customers?), the command returns a "No filter was specified. To delete all customers, add the --all option".

## Expected behaviour

All customers must be deleted from the database

## Steps to reproduce the issue

Execute the command : `./n98-magerun2.phar customer:delete --all` or `./n98-magerun2.phar customer:delete -a`
<img width="561" alt="Capture d’écran 2023-12-08 à 10 39 16" src="https://github.com/netz98/n98-magerun2/assets/48125944/1c5620ff-082e-45e4-8692-1aa6f6cc9805">

## Technical details

- Host Machine OS (Windows/Linux/Mac): Mac OS Sonoma
- Dockerized Magento (markshust/docker-magento)
- n98-magerun 7.2.0

## Possible Fix

After reading the history of "Customer"'s DeleteCommand.php file. I have the impression that commit 89a2162cc5d897bdd929d4e00301a93cb261b1dc may have produced the bug.

There's no check if the user has inserted the "--all" parameter in the logic. The $filterAttributes variable is therefore empty and produces error line 227.
<img width="557" alt="Capture d’écran 2023-12-08 à 10 43 13" src="https://github.com/netz98/n98-magerun2/assets/48125944/b28e5f72-6681-477c-9382-dfe69e36fb0e">

Otherwise, thank you for this wonderful tool! 😇

**Comment by cmuench** [comment]
@vncnt-mb The option is currently a bit confusing in the documentation.
The `--all` can only be used in combination with a filter.
I will refactor the command so that the `--all` option can be specified only without any filter. That's more clear.

**Comment by cmuench** [comment]
@vncnt-mb I updated the command and the develop phar file. You can try to by `n98-magerun2.phar self-update --unstable`.

**Comment by vncnt-mb** [comment]
@cmuench Great ! Thank you very much for your responsiveness. :) 

It seems to work, (i deleted the old customers data with the --range parameter : min:0 | max: 9999, just before your commit)
<img width="625" alt="Capture d’écran 2023-12-08 à 13 50 19" src="https://github.com/netz98/n98-magerun2/assets/48125944/0b0cb368-c1c1-49fe-b542-1bcb51a5d85c">
