### ISSUE TITLE
"dev:di:info" core command does return error 

### ISSUE THREAD

**Issue by DenisMir** [netz98/n98-magerun2#1396]
## Describe the bug

Using the `dev:di:info` core command you get an error when proxying it through `./bin/n98-magerun2`. 

For example `./bin/n98-magerun2 dev:di:info "Magento\Catalog\Model\ProductRepository"` does return: 

```
DI configuration for the class MagentoCatalogModelProductRepository in the GLOBAL area

Preference: MagentoCatalogModelProductRepository

Constructor Parameters:

In ClassReader.php line 34:
                                                               
  Class "MagentoCatalogModelProductRepository" does not exist  
                                                               

dev:di:info <class>
```

Running the same through the core magento binary does work perfectly. `./bin/magento dev:di:info "Magento\Catalog\Model\ProductRepository"`

## Expected behaviour

The command should work like `./bin/magento dev:di:info "Magento\Catalog\Model\ProductRepository"`

## Steps to reproduce the issue

Just run `./bin/n98-magerun2 dev:di:info "Magento\Catalog\Model\ProductRepository"` and you will see the above mentioned error.

## Technical details

Magento: 2.4.6-p3
n98-magerun2 version: 7.2.0
OS: MacOS (but also inside unix container)

**Comment by cmuench** [comment]
Seems like a shell quoting topic.

I was able to run it by replacing the double quotes with single quotes.

```
'Magento\\Catalog\\Model\\ProductRepository'
"Magento\\\\Catalog\\\\Model\\\\ProductRepository"
```

Let's see how we can fix this :-)

**Comment by cmuench** [comment]
@DenisMir I added a fix to the develop version.
You can try it by updating with `n98-magerun2.phar self-update --unstable`.

**Comment by DenisMir** [comment]
Oh that was quick I will try it out tomorrow. Awesome! Thank you very much.

**Comment by DenisMir** [comment]
Works perfectly now. I'm waiting now for our production projects for `n98/magerun2-dist`. Thanks for the quick fix.
