### ISSUE TITLE
Php from /Application Support/ folder provides issues (like with herd)

### ISSUE THREAD

**Issue by kayintveen** [netz98/n98-magerun2#1406]
Running Magerun2 with tools like for example Laravel herd or valet provides me issues 

the php binary runs from the "application support" directory. and the space in the dir name is providing issues.

```
/Users/kayintveen/Library/Application: line 2: xdebug.mode=debug: command not found
```

When running this with -vvv I see the following

```
Filtering environment variables for bin/magento
  - PHP_IDE_CONFIG
  - PHP_OPTIONS
  - XDEBUG_CONFIG
  - XDEBUG_SESSION
  - XDEBUG_SESSION_START
  - XDEBUG_TRACE
  - XDEBUG_PROFILE
Execute: /Users/kayintveen/Library/Application Support/Herd/bin/php81 /Users/kayintveen/Sites/vanharvey/bin/magento 'se:up' -vvv
  - Timeout: 86400
  - TTY: 1
  ```
  
  Even if I run symlink php in the ~/ dir for example it still wont work.

**Comment by cmuench** [comment]
@kayintveen thanks for reporting this. I will check if we can handle this by quoting the path.

**Comment by cmuench** [comment]
@kayintveen I was able to quote the php binary.
You can update the phar file to the dev version by running the `self-update --unstable` command.
