### ISSUE TITLE
dev:asset:clear command

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#141]
Removed files in `pub/static/frontend/<Vendor>/<theme>` folders. This cause Magento 2 to republish all assets again.

**Comment by erikhansen** [comment]
You might also want to consider removing the contents of the `var/view_preprocessed/less/frontend/<vendor>/<theme>` and `var/view_preprocessed/source/frontend/<vendor>/<theme>` folders. If you don't do that, then any changes made to the assets in `app/design/frontend/<vendor>/<theme>` will not get published to the `pub/static/frontend/<Vendor>/<theme>` folder.

**Comment by jthln** [comment]
Can be closed, has been implemented by #266.
