### ISSUE TITLE
Running multiple customer:createin script fails with "Area code is already set"

### ISSUE THREAD

**Issue by DanieliMi** [netz98/n98-magerun2#1414]
## Describe the bug

We are trying to create a test customer for every website via script (script seems to be slightly more performant than separate calls). But after creating the first customer it fails with the message "Area code is already set".
```
$ printf "customer:create customer@imi.dev Dev123456789# Dev Customer 1\ncustomer:create customer@imi.dev Dev123456789# Dev Customer 2\ncustomer:create customer@imi.dev Dev123456789# Dev Customer 3" | n98-magerun2 script
Customer customer@imi.dev successfully created
Area code is already set
Area code is already set

```

## Expected behaviour

All customers are created.

## Steps to reproduce the issue

Run the following command:
```
printf "customer:create customer@imi.dev Dev123456789# Dev Customer 1\ncustomer:create customer@imi.dev Dev123456789# Dev Customer 2\ncustomer:create customer@imi.dev Dev123456789# Dev Customer 3" | n98-magerun2 script
```

## Technical details

- Host Machine OS (Windows/Linux/Mac): Ubuntu 20.04
- Magento 2.4.6-p3
- n98-magerun2 Version: Tested on 7.0.3 and 7.3.1

**Comment by amenk** [comment]
Wow :racing_car:

**Comment by cmuench** [comment]
@DanieliMi I added a fix. You can test it in the unreleased version by updating to it with `n98-magerun2.phar self-update --unstable`.
