### ISSUE TITLE
"Magento core commands cannot be loaded" on 7.3.1

### ISSUE THREAD

**Issue by TheBadong** [netz98/n98-magerun2#1431]
## Describe the bug

Hello!
I can reproduce the error first mentioned [here](https://github.com/netz98/n98-magerun2/issues/1164), which has been apparently fixed in this [PR](https://github.com/netz98/n98-magerun2/pull/1291)

## Expected behaviour

I should not get a process warning regarding magento core commands when using XDEBUG

## Steps to reproduce the issue

![image](https://github.com/netz98/n98-magerun2/assets/32772726/9ba64637-6cb0-4d33-a48d-422a8df1a5ba)

1. Run any command with XDEBUG
2. See error

## Technical details

Adobe Commerce ver. 2.4.5-p6
n98-magerun2 7.3.1

## Additional context

Running on Mac, inside a debian 12 container

**Comment by cmuench** [comment]
@TheBadong I just tested the same n98-magerun2 version on my machine with enabled xdebug v3.3.1 in a docker container.
I was not able to break it.
Can you check if "bin/magento" works in your shop installation without any issues?

**Comment by cmuench** [comment]
@TheBadong Can you try to run n98-magerun2 with `-vvv` option?
This will print more information.

**Comment by cmuench** [comment]
@TheBadong Do you see any command in the list if you run `bin/magento`.
Technically n98-magerun2 does only fetch the command list of `bin/magento` via JSON.
If it cannot get a JSON result then we see this error message.

**Comment by cmuench** [comment]
Cannot be reproduced.
