### ISSUE TITLE
Create integration, required arguments

### ISSUE THREAD

**Issue by sergiirepin** [netz98/n98-magerun2#1441]
Hallo, 
I believe email and endpoint could be optional.

https://github.com/netz98/n98-magerun2/blob/aa60c1f7ae033b21154c02ffbc5ee1b7370a6495/src/N98/Magento/Command/Integration/CreateCommand.php#L69

**Comment by cmuench** [comment]
@sergiirepin thanks. I will check this next week.

**Comment by cmuench** [comment]
@sergiirepin you are right.
To make the email options we also need to make the endpoint url optional, because both are arguments and not options.
I just checked the endpoint url and it seems that that we can make both arguments optional.

**Comment by cmuench** [comment]
@sergiirepin The change is now in the development version. If you want you can test by updating to it `n98-magerun2.phar self-update --unstable`.

**Comment by sergiirepin** [comment]
@cmuench thanks! Looks good to me!

> because both are arguments and not options.
Does it make sense to swap the arguments to options ?

**Comment by cmuench** [comment]
@sergiirepin Maybe but it is then a break for some automations.

**Comment by cmuench** [comment]
Released with v7.4.0
