### ISSUE TITLE
db:dump doesn't work after 0.74-beta10

### ISSUE THREAD

**Issue by erikhansen** [netz98/n98-magerun2#150]
In Magento 2 0.74-beta10, the `app/etc/config.php` file was split into two files: `config.php` and `env.php`.

`env.php` now stores the database configuration information, as documented here: [http://devdocs.magento.com/guides/v1.0/config-guide/config/config-php.html#config-php-upgrade](http://devdocs.magento.com/guides/v1.0/config-guide/config/config-php.html#config-php-upgrade)

After 0.74-beta10, the db:dump script no longer works and results in this error:

![htdocs_ _bash_ _206x57](https://cloud.githubusercontent.com/assets/129031/8037950/429db47e-0dc6-11e5-86d7-be95a933486f.png)

If I update the `app/etc/config.php` file to also contain the contents of the `env.php` file, then the db:dump command works just fine.

**Comment by cmuench** [comment]
@erikhansen This was fixed in dev version for 10 days.
https://github.com/netz98/n98-magerun2/commit/e1a41948bddf080766878e1a173ef09fb920649f

Current dev version could be downloaded here: http://files.magerun.net/n98-magerun2-dev.phar

**Comment by erikhansen** [comment]
@cmuench - You guys are on it! Sorry I didn't test the dev version before submitting this issue. I'll make sure to do that in the future. Magerun is an amazing tool! Closing this issue…

**Comment by cmuench** [comment]
@erikhansen no problem. Feel free to create issues here.
