### ISSUE TITLE
db:* does not work with 1.0.0-beta - read env.php instead of config.xml

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#151]
$ n98-magerun2.phar db:dump sql/master.sql --only-command
    DB settings was not found in config.xml file

DB Config is now in app/etc/env.php

**Comment by amenk** [comment]
Already fixed in develop / unstable. Sorry for the noise.

**Comment by tkn98** [comment]
Best flaws are those already fixed. Thanks for taking care to report this!
