### ISSUE TITLE
sys:maintenance broken with M2 1.0.0-beta2

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#152]
$ n98-magerun2.phar sys:main --off
	PHP Fatal error:  Call to a member function get() on null in phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/System/MaintenanceCommand.php on line 48
	PHP Stack trace:
	PHP   1. {main}() /usr/local/bin/n98-magerun2.phar:0

Looks to me like the Object Manager can not be fetched?

**Comment by cmuench** [comment]
The fatal error is now fixed, but we have now a toggle problem. I try to fix it soon.

**Comment by cmuench** [comment]
@amenk Should now work in latest RC2
