### ISSUE TITLE
db:dump uses invalid mysqldump command when Magento db connection uses SSL

### ISSUE THREAD

**Issue by mfickers** [netz98/n98-magerun2#1526]
## Describe the bug

Database connection runs over SSL, here is an excerpt from the env.php:
```php
    'db' => [
        'table_prefix' => '',
        'connection' => [
            'default' => [
                'host' => '████████',
                'dbname' => 'magento2',
                'username' => '████████',
                'password' => '████████,
                'model' => 'mysql4',
                'engine' => 'innodb',
                'initStatements' => 'SET NAMES utf8;',
                'active' => '1',
                'driver_options' => [
                    1009 => '/etc/ssl/cert.pem'
                ]
            ]
        ]
    ],
```

When running db:dump, I get an error regarding the --ssl-mode parameter:
```bash
$ n98-magerun2 db:dump --compression=gzip --no-tablespaces var/magento2.sql.gz


  Dump MySQL Database


Start dumping database magento2 to file var/magento2.sql.gz
mysqldump: unknown variable 'ssl-mode=VERIFY_CA'

In Exec.php line 51:

  Exit status 7 for command set -o pipefail; mysqldump --single-transaction --quick --no-tablespaces -h'████████' --ssl-ca='/etc/ssl/cert.pem' -
  -ssl-mode=VERIFY_CA -u'████████' --password='████████' 'magento2' | LANG=C LC_CTYPE=C LC_ALL=C sed -E 's/DEFINER[ ]*=[ ]*`[^`]+`@`[^`]+`/DEFINER=CURRENT_USER/g
  ' | gzip -c  > 'var/magento2.sql.gz' 2>&1. Output was:


db:dump [--connection CONNECTION] [-t|--add-time [ADD-TIME]] [-c|--compression COMPRESSION] [--only-command] [--print-only-filename] [--dry-run] [--set-gtid-purged-off] [--no-single-transaction] [--human-readable] [--git-friendly] [--add-routines] [--no-tablespaces] [--stdout] [-s|--strip [STRIP]] [-e|--exclude [EXCLUDE]] [-i|--include [INCLUDE]] [-f|--force] [--keep-column-statistics] [--keep-definer] [--] [<filename>]
```

## Expected behaviour
`db:dump` is able to connect to the database using the configured connection from Magento.

## Steps to reproduce the issue

1. Configure Magento to connect to database over SSL
2. Run magerun db:dump

## Technical details

- Docker Image based on Alpine Linux v3.20
- mysqldump  Ver 10.19 Distrib 10.11.8-MariaDB, for Linux (x86_64)
- n98-magerun2 7.4.0 (commit: 94ac790) by netz98 GmbH
- Magento ver. 2.4.7-p2
- Database uses MySQL 8.0.32

## Possible Fix

My workaround is to add `--only-command` parameter to the `db:dump` command. Then I modify the `mysqldump` command by removing the `--ssl-mode` parameter.

**Comment by cmuench** [comment]
@mfickers ok that's tricky. We map the DB config of Magento to the external mysqldump parameters. Currently we support only a set of all the options. I will try to find a solution.

**Comment by cmuench** [comment]
ok. Looks like it's not so easy to setup MySQL with SSL in my ddev box... I just spent two hours with only a bit progress to setup the environment in my dev box.

**Comment by mfickers** [comment]
I appreciate you spending the time to look into it, thank you.

I think this might actually be a problem with mariadb-client, as I found similar issues there. Seems like mariadb-client does not support the `--ssl-mode` parameter in some versions even though it should. But I've not had the time to verify by comparing to mysql-client.

For now I have a workaround and I don't need to dump dbs very often for the affected system.

**Comment by cmuench** [comment]
@mfickers that's a good hint. I will check, how we can distinguish the client tool here. Maybe I can simply check if the option exists by calling the dump commands `--help` option.

**Comment by cmuench** [comment]
@mfickers I created a fix for the issue. You can test it by updating to the dev version via `n98-magerun2.phar self-update --unstable`.
