### ISSUE TITLE
dev:console command issue with 2.4.7 Adobe Commerce Cloud

### ISSUE THREAD

**Issue by aligent-lturner** [netz98/n98-magerun2#1548]
## Describe the bug

There appears to be an issue with running the `dev:console` command and interactive with the database on Adobe Commerce Cloud instances.
The command works fine when getting classes, etc., but as soon as it needs to read from the database, it gets an error:

## Expected behaviour

Records are able to be read from the datbase without issue.

## Steps to reproduce the issue

A simple set of commands to reproduce the issue:
```
~$ bin/n98 dev:console
Magento 2.4.7-p3 Enterprise initialized ✔
At the prompt, type help for some help.

To exit the shell, type ^D.
Psy Shell v0.12.3 (PHP 8.3.9 — cli) by Justin Hileman
> $connection = $di->get('Magento\Framework\App\ResourceConnection')->getConnection();
= Magento\ResourceConnections\DB\Adapter\Pdo\MysqlProxy\Interceptor {#15443}

> $select = $connection->select();
= Magento\Framework\DB\Select {#15449}

> $select->from('catalog_product_entity')->where("type_id = 'configurable'");
= Magento\Framework\DB\Select {#15449}

> $rows = $connection->fetchAll($select);

   ERROR  Port must be configured within host parameter (like localhost:3306 in vendor/magento/zend-db/library/Zend/Db/Select.php on line 1376.


   ERROR  Port must be configured within host parameter (like localhost:3306 in vendor/magento/zend-db/library/Zend/Db/Select.php on line 1376.


   Zend_Db_Adapter_Exception  Port must be configured within host parameter (like localhost:3306.

>
```

## Technical details

Using n98 v7.4.0

## Additional context

We have only seen this issue happen on a non-integration environment with 2.4.7 installed. Earlier versions appear to be unaffected, and integration environments, which don't have the master/slave DB setup appear to be unaffected.

**Comment by cmuench** [comment]
This problem sounds similar to this bug report: https://github.com/magento/magento2/issues/38799

**Comment by aligent-lturner** [comment]
@cmuench thanks, yeah - we discovered that this patch fixes it - https://github.com/magento/quality-patches/blob/master/patches/os/ACSD-61366_2.4.7-p1.patch. It's the same as the PR for that issue.
