### ISSUE TITLE
make:config:routes in dev:console creates system.xml

### ISSUE THREAD

**Issue by peterjaap** [netz98/n98-magerun2#171]
This concerns the code-generator branch

<img width="391" alt="screenshot 2016-01-30 18 08 59" src="https://cloud.githubusercontent.com/assets/431360/12697161/975ae066-c77c-11e5-9259-bc5b2e4c4143.png">

**Comment by cmuench** [comment]
@peterjaap Thanks for testing. I corrected the command and deployed a new test phar file.

**Comment by peterjaap** [comment]
Verified, works now;

```➜  src git:(master) ✗ cat ./Elgentos/Test/etc/frontend/routes.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/etc/routes.xsd">
</config>%
```
