### ISSUE TITLE
BaseURL Check Error

### ISSUE THREAD

**Issue by simkea** [netz98/n98-magerun2#172]
here is the row from my mage2 database -> core_config_data:

| 2 | default | 0 | web/unsecure/base_url | http://192.168.78.45/ |
| 3 | default | 0 | web/secure/base_url | https://192.168.78.45/ |

The Result from command "n98-magerun2 sys:check":

✖ Invalid Secure BaseURL:  of Store: default Wrong hostname configured. Hostname must contain a dot
✖ Invalid Unsecure BaseURL:  of Store: default Wrong hostname configured. Hostname must contain a dot

is this an problem from my configuration?! or is there an bug in magerun?
thx. br

**Comment by tkn98** [comment]
This needs review, beacause I know you can run an M2 store with an IP address based base-URL, but it might not have been correct in M1 and we perhaps ported the base-URL validator too early.

I assume your site work correctly with your base-URL setting, right?

And thanks for reporting.

**Comment by simkea** [comment]
Yes! My magento 2 is running perfect :)

**Comment by ktomk** [comment]
@simkea: Can you run the config:get command and check those config paths with it, too? From what I see in your report is, that the base-URLs are empty when the check is done. So that is the actual problem (in use is: *`Magento\Framework\App\Config\ScopeConfigInterface`* in `CheckAbstract::__construct()).

**Comment by simkea** [comment]
Result:

mage2-shop# n98-magerun2.phar config:get
Couldn't find a config value for ""

oO  okay...

**Comment by ktomk** [comment]
@simkea: My fault, sorry for being that imprecise about the *full* command, the path needs to be given:

    n98-magerun2.phar config:get "*/base_url"

this command should list the settings you also showed from the database table. However I found the culprit and a fix is on the way.

Thanks again for reporting the issue!

**Comment by ktomk** [comment]
The fix is now part of the development version. You can do a self-upgrade to the unstable variant to obtain it. It will become part of the next stable version when released.

**Comment by simkea** [comment]
thx ;)

**Comment by RapidMod** [comment]
The magento installation is working properly, other than logging in, but this error still persists

**## the error**

`   magerun2 sys:check

✖ Invalid Secure BaseURL:  of Store: default Wrong hostname configured. Hostname must contain a dot
✖ Invalid Unsecure BaseURL:  of Store: default Wrong hostname configured. Hostname must contain a dot
✔ Empty cookie Domain (secure) of Store: default - OK
✔ Empty cookie Domain (unsecure) of Store: default - OK
`

**## base url info**

`magerun2 config:get "*/base_url"
+-----------------------+---------+----------+------------------------------+
| Path                  | Scope   | Scope-ID | Value                        |
+-----------------------+---------+----------+------------------------------+
| web/unsecure/base_url | default | 0        | http://www.practiceshop.net/ |
+-----------------------+---------+----------+------------------------------+
shell>:/var/www/practiceshop.net/html# 
`

**Comment by ktomk** [comment]
@RapidMod: Can you share the `n98-magerun2.phar --version`  for your report please? That would be great!

**Comment by RapidMod** [comment]
n98-magerun2 version 1.1.4 by netz98 new media GmbH
Debian GNU/Linux 8
PHP 7.0.4-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
Server version: Apache/2.4.10 (Debian)
Server built:   Nov 28 2015 14:05:48
Magento CLI version 2.0.2

**Comment by ktomk** [comment]
@rapidmod: Can you please update to the development version? It's not fixed in 1.1.4 but in 1.1.5 (develop). It should be gone then.

To do so, just run

~~~
n98-magerun2.phar self-update --unstable
~~~

Afterwards try the *`sys:check`* command again. Please report back then.
