### ISSUE TITLE
You should not accept an invalid password when installing

### ISSUE THREAD

**Issue by aguimaraes** [netz98/n98-magerun2#174]
install command is allowing passwords that are not compliant with this rule:

> The password must be at least 7 characters in length and must include at least one alphabetic and at least one numeric character.

**Comment by ktomk** [comment]
Yes, that's normally known (at least I imagine it that way), it works well or did you run into an issue with your password? Do you want to have this (not state of the art anyway) rule applied? Do you need it?

**Comment by aguimaraes** [comment]
Hello, 
It seems I was a bit tired and my message looks a little rude and incomplete because of my laziness.
Sorry about that.

That was just a hiccup, I was able to finish the installation gracefully.
I just found it annoying to restart the process because of the lack of information about the password. I'm new to magento and did not know that rule.

Thank you.

**Comment by tkn98** [comment]
@aguimaraes: It should work with any password. AFAIK the check within Magento is only when creating a user in the adminhtml area. Or do you mean the message is given but so late in the process that it was hindering a good working experience? Please share.
