### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by stefandoorn** [netz98/n98-magerun2#178]
If installing according to the installation instructions, how to keep this tool up-to-date with updates? Is there also a way to install it as a composer dependency so it can update with every `composer update` run?

**Comment by cmuench** [comment]
@stefandoorn Like in version 1 we only call the Magento installer. In Magento 2 all updates of the core are done by composer.

**Comment by stefandoorn** [comment]
I'm not sure this is about updating n98-magerun2 itself. Like composer has a self-update command, does n98-magerun2 have something like this?

**Comment by cmuench** [comment]
@stefandoorn Yes :-) 

`n98-magerun2.phar self-update`

**Comment by stefandoorn** [comment]
Great. Is there a way to install it as a composer dependency (through composer.json) instead of downloading the file through wget?

**Comment by cmuench** [comment]
@stefandoorn 

https://packagist.org/packages/n98/magerun2

I hope this works for you:

`composer.phar require n98/magerun2`

**Comment by cmuench** [comment]
@stefandoorn i close this issue. If you have still problems, please feel free to reopen the issue.
