### ISSUE TITLE
support per-condebase configuration 

### ISSUE THREAD

**Issue by briceburg** [netz98/n98-magerun2#183]
does magerun2 support custom/per-codebase configuration (as magerun1 did via placing  n98-magerun.yaml in app/etc/ ?)

**Comment by ktomk** [comment]
Yes, the same configuration principles have been taken over, just the name of the config file has been slightly changed: `n98-magerun2.yaml`.

The file you name is also known as *Project Config File* and the location is:

    <magento-root-path>/app/etc/n98-magerun2.yaml

Just let me know if this does not work for you.

**Comment by briceburg** [comment]
@ktomk thanks for this clarification. Works! Closing.
