### ISSUE TITLE
Testsuite CWD = Magento 2 directory takes roughly double the time and memory

### ISSUE THREAD

**Issue by ktomk** [netz98/n98-magerun2#186]
Running the magerun2 testsuite within the Magento2 directory takes roughtly double the time and memory as if not.
- N98_MAGERUN2_TEST_MAGENTO_ROOT=www Time: 1.38 minutes, Memory: 792.25Mb
- N98_MAGERUN2_TEST_MAGENTO_ROOT=. Time: 2.72 minutes, Memory: 1411.50Mb
- N98_MAGERUN2_TEST_MAGENTO_ROOT=../www Time: 2.76 minutes, Memory: 1411.25Mb
- N98_MAGERUN2_TEST_MAGENTO_ROOT=/path/to/n98-magerun2/magento2/www Time: 2.65 minutes, Memory: 1411.00Mb

This behaviour is reproducible.

**Comment by cmuench** [comment]
Seems to be fixed in development version (v4.0.0).
Tested with 3 of 4 variants.

Runtime on my machine in all 3 runs -> media 1.8 minutes.
