### ISSUE TITLE
Can't install magerun2 greater then v1.1.6 using composer while using Magento 2 (due to symfony/console dependency)

### ISSUE THREAD

**Issue by hostep** [netz98/n98-magerun2#198]
Hi guys

We have set up Magento 2 using composer.
And also added n98/magerun2 as a dependency in the composer.json file.

But lately I've been noticing we don't get any more updates, we are stuck at version 1.1.6

After some testing and looking around, this seems to be because `n98/magerun2` depends on `symfony/console: ~2.7.10` while `magento/composer` currently depends on `symfony/console: ~2.3 <2.7`

So this won't work together.

I noticed you changed the version requirements in this commit: https://github.com/netz98/n98-magerun2/commit/153b3f92fc454e1fa979c1fab70125770020e123

I'm not sure what the best way to solve this is? Either n98-magerun should depend on the same version of `symfony/console` as Magento 2 does, or we should try to convince the Magento guys to upgrade their dependency version.

What do you think?

**Comment by ktomk** [comment]
@hostep I've just updated the development version and made the version requirements exactly the same. I think this should resolve your issue, if not, please let me know.

I also hope for the composer version this won't bite. IMHO that one is more important so that everyone is on stable grounds:

- https://github.com/magento/magento2/issues/4359
- https://github.com/magento/composer/pull/2

Do you need the changes in Magerun symfony/console in a stable release? If so just let me know then I'll increment.

**Comment by hostep** [comment]
Thansk, it seems to work now:
```sh
➜ tools/composer.phar require n98/magerun2 dev-develop
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating n98/magerun2 (1.1.6 => dev-develop 5a4b9c8)
    Checking out 5a4b9c8c78010b9906c4052b39c55ae82d3e9476

Writing lock file
Generating autoload files
```

`composer/composer` version `1.0.0-alpha10` is installed, and doesn't seem to give any conflicts, so no worries there.

For me this isn't a very urgent issue, so you can just stick to your normal release cycle and take this change with the next stable release.

Thanks again!

**Comment by ktomk** [comment]
@hostep  I'll change this again, back to "~2.3" as it's done in magento/magento2 and magento/composer by removing "<2.1", see https://github.com/magento/magento2/pull/8151/commits/c6ef98fccd64be22d03941f2ea3a5138333be931 .

Nicolas Grekas bumped the upstream issue ca. a month ago and some days ago the changes were merged in Magento2 master as well as for the Magento Composer package.

I'm aware that this conflicts with your scenario but streamlining the magerun development version makes me do this change, at least I assume yet I need to change it. I don't know how long it takes for the Magento2 upstream changes that this reflects in their packages. Your feedback on this is welcome.

**Comment by ktomk** [comment]
We could add a build in Travis that checks if installing from composer with n98-magerun2 is possible, so we can track the status. I've not done this, just an idea that comes to mind this moment.

**Comment by hostep** [comment]
Hi Tom

I think you are making the correct decision by following the requirements exactly as defined in Magento2.

And I don't think this will cause any issues.
- If you install Magento 2.0.x or 2.1.x in combination with Magerun2 with composer, it should install symfony/console 2.6.x
- if you install Magento 2.2 (currently develop branch) in combination with Magerun2, you'll get symfony/console 2.8.x.

So this change will cause no problems I think, unless something backwards incompatible was changed in symfony/console. But according to semver, it shouldn't be.

The conflict you are referring to was because the requirement of Magerun2 was previously set to `~2.7.10` which indeed conflicted with the Magento2 requirement of `~2.3 <2.7`, but that was no longer an issue since you fixed this in https://github.com/netz98/n98-magerun2/commit/f63da32797e591ed20a94a3cb12f436db5295299

Thanks for the heads-up though :)

**Comment by hostep** [comment]
Update, if you want to have the exact same requirements as Magento2, you should set the dependency as follows: `~2.3, !=2.7.0`. See: https://github.com/magento/magento2/blob/988f3a37bc17b458c98bfa0a1dc0238805f98380/composer.json#L47

Apparently there was something wrong with 2.7.0 which is explained over here: https://github.com/magento/magento2/pull/8151/commits/c6ef98fccd64be22d03941f2ea3a5138333be931

**Comment by ktomk** [comment]
@hostep: Thanks for the quick feedback. I've seen that `!=2.7.0` but couldn't locate it. I think we can leave it out as composer will prefer a later version anyway (yolo).

I also think that keeping up with the upstream changes is fine, however, with older versions you will run into trouble. If it's fine for you, I'll do a stable release today with the changes in. For us it's related to some janitor work (better dev requirements, streamlining with magerun 1) and we'll get reproducible phar builds with the new version then (finally!).
