### ISSUE TITLE
Bug importing config from scripts where value is NULL

### ISSUE THREAD

**Issue by SchumacherFM** [netz98/n98-magerun2#208]
Hi there,

my config script contains some exported database NULLs as you can see below:

```
config:set "web/unsecure/base_media_url"    NULL
config:set "web/unsecure/base_static_url"   NULL
```

Importing those scripts will result NOT in a real database NULL, we get a string NULL.

```
select * from core_config_data where value = 'NULL';
+-----------+---------+----------+------------------------------------------------------+-------+
| config_id | scope   | scope_id | path                                                 | value |
+-----------+---------+----------+------------------------------------------------------+-------+
|        65 | default |        0 | crontab/default/jobs/catalog_product_alert/run/model | NULL  |
|        78 | default |        0 | general/store_information/merchant_vat_number        | NULL  |
|        89 | default |        0 | web/cookie/cookie_path                               | NULL  |
|        92 | default |        0 | web/secure/base_media_url                            | NULL  |
|        93 | default |        0 | web/secure/base_static_url                           | NULL  |
|       104 | default |        0 | web/unsecure/base_media_url                          | NULL  |
|       105 | default |        0 | web/unsecure/base_static_url                         | NULL  |
+-----------+---------+----------+------------------------------------------------------+-------+
7 rows in set (0.00 sec)
```

I suggests that the value NULL in a text file gets interpreted as a database NULL.

What do you think?

**Comment by tkn98** [comment]
To prevent ambiguities, this needs a flag or even multiple. Quick sketch:

    --null     # do not accept value, set path with database null-value
    --null-as-null   # interpret the value string "NULL" as database null-value

Otherwise if that is possible currently to have NULL values, we should have it.

**Comment by SchumacherFM** [comment]
Any updates here?

**Comment by ktomk** [comment]
Not yet, but I think there might be some use to invert the flag. Using the string "`NULL`" (all caps) should be treated as NULL value unless ` --no-null` (or similar) is used. That would allow to set an entry to NULL while passing data from a textfile into the command (e.g. hsccd or other scripts).

**Comment by SchumacherFM** [comment]
I would have needed that today ... ;-)

**Comment by ktomk** [comment]
But you can only have it tomorrow ... ;-). It's not the prettiest code and quite quickly written as in the end the output formats needed to be dealt with (`config:get`). I therefore covered it with tests for the scenarios which came to my mind.

You can use `--no-null` with `config:set` for the old behaviour if you need to have NULL as string. I think this is unlikely, but it is supported.

---

We believe that the enhancement asked for is available in the development version now. It can be upgraded to it using the `self-update` command with the `--unstable` switch.

**Comment by SchumacherFM** [comment]
You're awesome! Thank you very much!

**Comment by ktomk** [comment]
@SchumacherFM: For those versions of Magento 1 which do support NULL in config table values, this feature has been backported to Magerun 1 (https://github.com/netz98/n98-magerun/commit/cb1bd42c2dd176c32492833b8357ee593e614e21). Just FYI.
