### ISSUE TITLE
config:set and config:get don't encrypt/decrypt "obscure" config values

### ISSUE THREAD

**Issue by erikhansen** [netz98/n98-magerun2#209]
# Issue explanation

The `config:set` and `config:get` values don't work with config fields that have the "type" of "obscure". For an example of this type of field, look here: https://github.com/magento/magento2/blob/develop/app/code/Magento/Authorizenet/etc/adminhtml/system.xml#L24

<hr>
# Steps to reproduce `config:get` error
* Login to M2 admin. Go to _STORES > Configuration > SALES > Payment Methods > Authorize.net Direct Post_ and enter "12345" into the "API Login ID" field. Click "Save Config"
* Go to the command line and run:
```
n98-magerun2.phar config:get "payment/authorizenet_directpost/login"
```

# Actual results from `config:get`
```
+---------------------------------------+---------+----------+-----------------------------------------------------------------------------------+
| Path                                  | Scope   | Scope-ID | Value                                                                             |
+---------------------------------------+---------+----------+-----------------------------------------------------------------------------------+
| payment/authorizenet_directpost/login | default | 0        | 0:2:svHvS9w9bf7x42pyZPZK2QpIGqDG4fgm:sSSEjJ9+1qLb/w+WcGv4+msDaYleOCgSLOxNQCaJUKA= |
+---------------------------------------+---------+----------+-----------------------------------------------------------------------------------+
```

# Expected results from `config:get`

```
+---------------------------------------+---------+----------+-------+
| Path                                  | Scope   | Scope-ID | Value |
+---------------------------------------+---------+----------+-------+
| payment/authorizenet_directpost/login | default | 0        | 12345 |
+---------------------------------------+---------+----------+-------+
```

<hr>

# Steps to reproduce `config:set` error
* Go to the command line and run:
```
n98-magerun2.phar config:set "payment/authorizenet_directpost/login" "12345"
```
* Flush cache.
* Login to M2 admin. Go to _STORES > Configuration > SALES > Payment Methods > Authorize.net Direct Post_.

# Expected results from `config:set`

The "API Login ID" field should contain values in the input:
![magento admin-ocpj9](https://cloud.githubusercontent.com/assets/129031/15942875/0237dfca-2e4c-11e6-9cca-4746ca6daa7c.png)

# Actual results from `config:set`

Since the `config:set` command didn't encrypt the value, the field will be blank:
![magento admin-ka2vv](https://cloud.githubusercontent.com/assets/129031/15942913/219073e6-2e4c-11e6-9875-8cce96679c43.png)

**Comment by ktomk** [comment]
If you need to get/set an encrypted value (what you call obscured) you have to tell the magerun command that it is encrypted:

*  'config:get` command: use the `--decrypt` switch
*  'config:set` command: use the `--encrypt` switch

The key used for the encryption is the one of the installation. Magerun does not automatically guess that a setting is encrypted (or not).

**Comment by erikhansen** [comment]
@ktomk Ah, thanks for bringing those flags to my attention. And thanks for all of your work on this amazing tool.

**Comment by ktomk** [comment]
No problem, please check if these flags do work for you.

**Comment by erikhansen** [comment]
I just checked and those flags work great.
