### ISSUE TITLE
Command sys:maintenance ignores options --on and --off

### ISSUE THREAD

**Issue by maderlock** [netz98/n98-magerun2#211]
Both options just toggle the current setting rather than force one way or the other.

**Comment by tkn98** [comment]
Would you please be so kind and provide an example how to reproduce. It might seem redundant to you but it helps a lot in getting things fixed more quickly.

**Comment by maderlock** [comment]
Sure!

To reproduce:
1. Using n98-magerun2.phar v.1.1.16
2. In Magento2 base folder with maintenance mode currently off (can visit site)
3. run n98-magerun2.phar sys:maintenance --off

Expected result:
To see a message "Maintenance mode off"

Actual result:
See message "Maintenance mode on"

And visa versa.

**Comment by tkn98** [comment]
Thanks, can confirm it's broken. Toggles instead of sets.

**Comment by tkn98** [comment]
Build: https://travis-ci.org/netz98/n98-magerun2/builds/143930833

**Comment by tkn98** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.

**Comment by tkn98** [comment]
Just seeing that maybe --on should be preferred over --off in case someone uses both options...

And thanks for your report.
