### ISSUE TITLE
ScriptCommand.php not compatible with Magento 2.1

### ISSUE THREAD

**Issue by p-makowski** [netz98/n98-magerun2#212]
Magento broke public interface in 2.1:

> PHP Fatal error:  Uncaught Error: Undefined class constant 'VERSION' in phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/ScriptCommand.php:287
Stack trace:
#0 phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/ScriptCommand.php(120): N98\Magento\Command\ScriptCommand->initScriptVars()
#1 phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): N98\Magento\Command\ScriptCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/AbstractMagentoCommand.php(432): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(882): N98\Magento\Command\AbstractMagentoCommand->run(Object(Symfony\Component\Console\Input\Arr in phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/ScriptCommand.php on line 287

**Comment by tkn98** [comment]
Magento 2.1 still is RC, isn't it? Have you reported this problem upstream? Breaking the public interface could qualify as flaw in 2.1, so this would be good to know firsthand.

**Comment by p-makowski** [comment]
M2.1 was unfortunately released on Thu or Fri last week, so I didn't have a chance to report it before release.

**Comment by tkn98** [comment]
Yes, just coming back as I see the message. Can you provide instructions on how to reproduce?

**Comment by hostep** [comment]
FYI: https://github.com/magento/magento2/issues/4840 & https://github.com/magento/magento2/issues/4369

**Comment by tkn98** [comment]
The upcoming B2B Edition needs a way to change the version which is then possible via  `\Magento\Framework\App\ProductMetadata`. That's perhaps a reason why this change of the public interface happened. We need to fix this ASAP, let me also fix the build be then.

**Comment by p-makowski** [comment]
@tkn98 
How to reproduce:

1. Set the environment variable N98_MAGERUN2_TEST_MAGENTO_ROOT with a path to a Magento 2.1 installation which can be used to run tests
2. $ vendor/bin/phpunit --filter \N98\Magento\Command\ScriptCommandTest::testExecute

**Comment by tkn98** [comment]
The changes are now part of the development version (unstable). It will be fixed in the next stable release (1.1.15).

**Comment by tkn98** [comment]
You should see this fixed in stable 1.1.15 release which went out the night. If this does not resolve the issue, please report back and/or reopen.
