### ISSUE TITLE
ScriptCommand in 1.1.16: Call to a member function get() on null

### ISSUE THREAD

**Issue by p-makowski** [netz98/n98-magerun2#218]
Running script:repo:run X results in the following error:

> PHP Fatal error:  Uncaught Error: Call to a member function get() on null in phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/ScriptCommand.php:294

Stack trace:
> #0 phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/ScriptCommand.php(120): N98\Magento\Command\ScriptCommand->initScriptVars()
#1 phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): N98\Magento\Command\ScriptCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/AbstractMagentoCommand.php(432): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(882): N98\Magento\Command\AbstractMagentoCommand->run(Object(Symfony\Component\Console\Inpu in phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/ScriptCommand.php on line 294

This issue is fixed in:

- PR: https://github.com/netz98/n98-magerun2/pull/215

- commit: https://github.com/netz98/n98-magerun2/pull/215/commits/e50106605fea275fdab76d7414d424f64a4d8306

**Comment by ktomk** [comment]
Please provide a single-commit PR to address the fix of this issue only. That PR must not contain any refactoring, but you can if you like provide fixes for the code-style issues that have been introduced in the previous PR.

**Comment by tkn98** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the self-update command with the --unstable switch.
