### ISSUE TITLE
connection leak when importing lot's of rows via n98-magerun script

### ISSUE THREAD

**Issue by adiibanez** [netz98/n98-magerun2#219]
n98-magerun2 version 1.1.16

after ~150 rows

 [Zend_Db_Adapter_Exception]
  SQLSTATE[08004] [1040] Too many connections
 
 

  [PDOException]
  SQLSTATE[08004] [1040] Too many connections
 
config:set [--scope[="..."]] [--scope-id[="..."]] [--encrypt] path value
 
 
  [Zend_Db_Adapter_Exception]
  SQLSTATE[08004] [1040] Too many connections
 
 

  [PDOException]
  SQLSTATE[08004] [1040] Too many connections
 
config:set [--scope[="..."]] [--scope-id[="..."]] [--encrypt] path value

PHP Fatal error:  Uncaught Exception: Warning: proc_open(): unable to create pipe Too many open files in /var/www/proj/site/vendor/symfony/console/Symfony/Component/Console/Application.php on line 974 in /var/www/proj/site/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'proc_open(): un...', '/var/www/siesob...', 974, Array)
#1 /var/www/proj/site/vendor/symfony/console/Symfony/Component/Console/Application.php(974): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 /var/www/proj/site/vendor/symfony/console/Symfony/Component/Console/Application.php(784): Symfony\Component\Console\Application->getSttyColumns()
#3 /var/www/proj/site/vendor/symfony/console/Symfony/Component/Console/Application.php(745): Symfony\Component\Console\Application->getTerminalDimensions()
#4 /var/www/proj/site/vendor/symfony/console/Symfony/Component/Console/Application.php(675): Symfony\Component\Console\Application-> in /var/www/proj/site/vendor/magento/framework/App/ErrorHandler.php on line 61

**Comment by ktomk** [comment]
Please share the script, but please remove redundant lines and obfuscate private information if necessary.

**Comment by adiibanez** [comment]
for i in {1..300}; do echo 1; done | awk '{print "config:set \"test" NR "\" \"test" NR "\""}' > lotsofrows.magerun

**Comment by cmuench** [comment]
@adiibanez Please try to import so many rows as batch with the script command.
https://github.com/netz98/n98-magerun2#n98-magerun-script

This will only open one DB connection and inserts all the config entries in one bootstrapped store.

**Comment by adiibanez** [comment]
Not the case for me ... 

command i was using before was:
bin/n98-magerun2 script lotsofrows.magerun

now I have also tried: 

bin/n98-magerun2 script < lotsofrows.magerun
with the very same error "unable to create pipe Too many open files"

**Comment by ktomk** [comment]
Following the explanation of Alan Storm who is known for his in-depth analysis, ObjectManagert:;;get() should return a singleton instance but in this case this is obviously not the case (otherwise there would not be a hit of the MySql connction limit).

Using a singleton instance does solve the problem.

**Comment by tkn98** [comment]
@adiibanez We believe that the bug you reported is fixed in the development version. You can upgrade to it with the `--unstable` switch.
