### ISSUE TITLE
script command very slow

### ISSUE THREAD

**Issue by SchumacherFM** [netz98/n98-magerun2#222]
Hi!

Running this command inside my vagrant box (with bindfs) takes too long:

```
[vagrant@vagrant dev]$ time make M2_ENV=dev config
./site/bin/n98-magerun2 --root-dir=site script ../configuration/core-config-data/pre.magerun
catalog/category/root_id => 2
catalog/custom_options/date_fields_order => d,m,y
catalog/custom_options/time_format => 24h
catalog/fields_masks/meta_description => {{name}} {{description}}
catalog/fields_masks/meta_keyword => {{name}}
catalog/fields_masks/meta_title => {{name}}
catalog/fields_masks/sku => {{name}}
catalog/frontend/flat_catalog_category => 1
catalog/frontend/flat_catalog_product => 1
catalog/price/scope => 0
cataloginventory/options/can_subtract => 0
^Cmake: *** [config] Interrupt


real	0m12.230s
user	0m9.031s
sys	0m0.218s
```

In total one second for each `config:set` command.

PHP 7.0.8 

Any ideas to speed this up? Have you observed the same?

**Comment by tkn98** [comment]
Hmm, that's really long.

Can you try as well with an empty script and a single config call? That might show more about how the time distributes.

Please share the magerun version as well.

IIRC we have some recent fixes for config commands. So please try as well the development version.

**Comment by SchumacherFM** [comment]
```
[vagrant@vagrant site]$ time ./bin/n98-magerun2 script ../configuration/core-config-data/demo.magerun
catalog/category/root_id => 2
catalog/custom_options/date_fields_order => d,m,y
catalog/custom_options/time_format => 24h

real	0m5.184s
user	0m3.861s
sys	0m0.135s
[vagrant@vagrant site]$ time ./bin/n98-magerun2 --version
n98-magerun2 version 1.1.17 by netz98 new media GmbH

real	0m3.102s
user	0m1.449s
sys	0m0.130s
[vagrant@vagrant site]$ time ./bin/n98-magerun2 script ../configuration/core-config-data/demo.magerun
catalog/custom_options/time_format => 24h

real	0m4.810s
user	0m2.694s
sys	0m0.137s
```
Cache was off ... scary slow ... 😱 🤓

**Comment by tkn98** [comment]
Even with cache off, it shouldn't take that long IMHO.

I also had an idea earlier to provide a config:set for more than one key / value pair at once as in deployment scripts you normally set a bunch of options and it's kind of a batch operation then.

**Comment by SchumacherFM** [comment]
We set for now 200 config values ... and it's growing ... batch mode would be great.

**Comment by ktomk** [comment]
@SchumacherFM: Now as I see your report: What cache was that? The one from Magento?

And for batch mode this needs some kind of different interface, would be good if it works well with Symfony Console.

Otherwise perhaps a file that is read (or something provided via stdin / pipe).

**Comment by SchumacherFM** [comment]
All of the M2 cache was disabled.

I could also port https://github.com/Zookal/HarrisStreet-ImpEx to M2 but if I do I would like to know if you're keen to add it to the magerun2 core and not as a plugin.

**Comment by ktomk** [comment]
That is great to read and a pretty good suggestion as it would enable us to provide better (internal) config classes for such batch operations.

We're already working on shared code between Magerun 1 + 2 and with some little abstraction the config related tasks are a good candiate to be streamlined between Magento 1 and 2 from what I could see so far.

I have looked into that in the past because of your great extension and I was thinking about keeping the cost to port to Magento 2 low and also to make it easy to maintain.
