### ISSUE TITLE
Add installer for 2.1.0

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#223]
Could the adding be done automatically?

**Comment by ktomk** [comment]
Should only require the 2.1.0 package. Would you like to file a PR? Otherwise I could do.

**Comment by amenk** [comment]
You can do it :-)

**Comment by ktomk** [comment]
We believe that the issue reported is taken care of in the development version. It can be upgraded to it using the ` self-update` command with the `--unstable` switch.
