### ISSUE TITLE
getting this error, when trying to change password

### ISSUE THREAD

**Issue by surjit** [netz98/n98-magerun2#227]
surjit@ubuntu:~/public_html$ php n98-magerun2.phar admin:user:change-password
Username:admin
Password:S123k456
SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction, query was: INSERT INTO `admin_passwords` (`user_id`, `password_hash`, `expires`, `last_updated`) VALUES (?, ?, ?, ?)

**Comment by jissereitsma** [comment]
I don't think this is related to `magerun2`. This error is a general error stating that your MySQL instance has performance issues.

**Comment by tkn98** [comment]
Correct, the timeout should not be relevant to Magerun 2. If you have high load on your database server, try the command when load normalizes. Also please check if there is a deadlock on that table.
