### ISSUE TITLE
Add Magento 2.0.8

### ISSUE THREAD

**Issue by rafaelstz** [netz98/n98-magerun2#229]
Add Magento 2.0.8 into `magerun2 install` command.

**Releases**
https://github.com/magento/magento2/releases

**Comment by tkn98** [comment]
Edit: And  2.0.9 ;)

**Comment by ktomk** [comment]
2.0.11+ should work as expected, found a flaw with 2.0.8 - 2.0.10.

We believe that the issue reported is taken care of in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.
