### ISSUE TITLE
Template hints toggling doesn't work

### ISSUE THREAD

**Issue by tommypyatt** [netz98/n98-magerun2#230]
Toggling template hints returns a success message but doesn't seem to be affecting the config option in the admin panel, nor the output on the frontend:

`$ n98-magerun2.phar dev:template-hints default`
`Template Hints enabled for store default`

Magento version: 2.1.0-rc3
OS: Mac

**Comment by agoeurysky** [comment]
Yes...
https://github.com/netz98/n98-magerun2/issues/91#issuecomment-217834112

**Comment by tkn98** [comment]
I can confirm it broken.

**Comment by tkn98** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.

**Comment by timneutkens** [comment]
@tkn98 Confirmed it's fixed now in the unstable build. Experienced the exact same thing as @tommypyatt.
