### ISSUE TITLE
Uncaught Error: Class 'Mage_Core_Model_Config_Options' not found 

### ISSUE THREAD

**Issue by Valentyn-Kubrak** [netz98/n98-magerun2#232]
Hi team. I found issue from new fresh installation of magerun:

~~~
PHP Fatal error:  Uncaught Error: Class 'Mage_Core_Model_Config_Options' not found in phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Application.php:357
Stack trace:
#0 phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Application.php(523): N98\Magento\Application->checkVarDir(Object(Symfony\Component\Console\Output\StreamOutput))
#1 phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(126): N98\Magento\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Application.php(558): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /usr/local/bin/n98-magerun2.phar(8): N98\Magento\Application->run()
#4 {main}
  thrown in phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Application.php on line 357
~~~

Previous version: n98-magerun2-1.1.16  works fine.

**Comment by tkn98** [comment]
Can you please share the command typed in to provoke this error?

**Comment by Valentyn-Kubrak** [comment]
@tkn98 
I just executed n98-magerun2.phar in magento2 root folder
tested with php 5.6 and php 7

**Comment by tkn98** [comment]
I'm able to reproduce this as well now. You see this error after #207. It's a check if a local `/tmp/magento/var` folder exists which was discouraged in Magento 1.

I can't say if that is still the case for Magento 2 but nevertheless, the check we do needs to be ported.

Thanks for reporting this flaw.

**Comment by tkn98** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.
