### ISSUE TITLE
Installing magerun2 downgrades symfony/finder from v3.x to v2.x

### ISSUE THREAD

**Issue by hostep** [netz98/n98-magerun2#234]
Hi

Just something I noticed, is probably not very important, but I think this change makes sense.

So, I just setup a new Magento 2 project (version 2.1.0) using composer, and one of the first dependencies I installed was magerun2, but when I did that, I saw this line in my console:
```
  - Removing symfony/finder (v3.1.3)
  - Installing symfony/finder (v2.8.9)
    Loading from cache
```

I thought this was a bit strange.

Anyway, I looked around in the composer.lock for all the dependency constraints for `symfony/finder` and found these ones:

- `"symfony/finder": "^2.2 || ^3.0"` (from `composer/composer`)
- `"symfony/finder": "~2.3"` (from `n98/magerun2`)
- `"symfony/finder": "~2.1|~3.0"` (from `psy/psysh`)
- `"symfony/finder": "~2.1|~3.0"` (from `fabpot/php-cs-fixer`)
- `"symfony/finder": "~2.3|~3.0"` (from `sebastian/finder-facade`)

**Proposition**: I think it makes sense to change the dependency version of n98/magerun2 to this: `^2.3 || ^3.0`

- Double pipes, since single pipes were [discouraged a long time ago](http://spiechu.pl/2015/03/09/new-composer-version-constraints/).
- And caret instead of tilde, because in my opinion, it's the more correct constraint (maybe the other composer deps should also be converted to use caret?).

What do you think?

Thanks!

**Comment by tkn98** [comment]
Let me guess, you installed Magerun 2 via composer, right?

For the double-pipes: fine.

For the caret instead tilde: I can say for here, we use an outdated Satis which not yet can handle the carets, so even I think your argument is generally correct, I can say that it's currently a burden on our end.

And then I remember some older ticket maybe even in Magerun 1 we should cross-link first because there were/was something, so good for review.

Albeit that, I think it should be fine for Magento 2 to allow the current stable version of these Packages, too.

Should I take care within the development version for this?

**Comment by hostep** [comment]
Ok, no problem for tilde, is not really necessary.

I can create a PR if you want, but it will probably have to wait until tonight. I don't have much time currently :)

**Comment by tkn98** [comment]
I just took some care now about this, also no time over here, so I pressed it into develop, if you can give it a try tonight that would be superb.

The reference I meant was https://github.com/netz98/n98-magerun/commit/584e6151ecc72b3ba2bd038b4f496d66898c7043 still no ticket. But this is from remembering, so looks safe.

Reference docs about [caret and tilde (composer versions)](https://getcomposer.org/doc/articles/versions.md).

**Comment by hostep** [comment]
Looks great (and will test tonight).

We didn't use composer for Magento 1, so I can't really comment on that.

**Comment by hostep** [comment]
Hi, just tested with `composer require n98/magerun2:dev-develop` and it works. `symfony/finder` no longer gets downgraded and stays at 3.1.3 👍 

Additional benefit, before you had to run: `composer require --no-update n98/magerun2 && composer update` otherwise composer threw errors about `symfony/finder` no being compatible. And now you can just run `composer require n98/magerun2`.
(I'm guessing composer tries less hard for dependency resolving when you use `require` and more when using `update`.)

Closing as this has been fixed on the develop branch.

**Comment by ktomk** [comment]
Great report and great feedback. I just updated the changelog. Good teamwork!
