### ISSUE TITLE
sys:check throws fatal error in production mode

### ISSUE THREAD

**Issue by hostep** [netz98/n98-magerun2#241]
Hi

I just noticed when trying to run `sys:check` on a production server that we get this fatal error:

```
php vendor/bin/n98-magerun2 sys:check
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to N98\Magento\Command\System\Check\Settings\CheckAbstract::__construct() must implement interface Magento\Framework\App\Config\ScopeConfigInterface, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /var/www/html/releases/20161005143021/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /var/www/html/releases/20161005143021/vendor/n98/magerun2/src/N98/Magento/Command/System/Check/Settings/CheckAbstract.php:34
Stack trace:
#0 /var/www/html/releases/20161005143021/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): N98\Magento\Command\System\Check\Settings\CheckAbstract->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))
#1 /var/www/html/releases/20161005143021/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('N98\\Magento\\Com...', Array)
#2 /var/www/html/releases/20161005143021/vendor/ in /var/www/html/releases/20161005143021/vendor/n98/magerun2/src/N98/Magento/Command/System/Check/Settings/CheckAbstract.php on line 34
```

This doesn't happen on a development machine, and my guess is that this is most likely because we don't run `setup:di:compile` locally.
I could reproduce the problem on 3 different completely different production machines, so it isn't depending on a certain environment.

Using magerun2 version 1.2.2, installed using composer.

If you need more info, please let me know :)

**Comment by tkn98** [comment]
Thanks for the report and indeed interesting.

From top of my head this should not be handled via ctor but the inject method we have for those dependencies. But that's just quick.

**Comment by tkn98** [comment]
Can reproduce on a production system.

**Comment by ktomk** [comment]
Sorry for the slow progress on this issue. I must admit we missed so far to run the test-suite against `production` mode, it was yet only running against the `default`.

It took some time to finally realize the culprit, add a change to testing and then fix the `sys:check`-sub-command creation to deal with production mode. That means, we have a fix!

Next to that some other commands which are intended for `development` mode (which includes `default` mode) needed to reflect the new testing as well by skipping the tests in production mode as a quick fix (e.g. the `make:block` command from the developer console generator commands suite).

Then finally I needed to get the switch to production mode running. Unfortunately Magento 2.0.x is not easy to deal with as the multi-tenant di compile has issues and for a general working way, switching the mode needed to be scripted in more detail (I don't have the best references at hand, this is an older one, I had it with 2.0.{9,10,11}: https://github.com/magento/magento2/issues/4070 , the same error message as here: [OptionInterfacePersistor error when compiling magento in production mode](http://magento.stackexchange.com/questions/147219/optioninterfacepersistor-error-when-compiling-magento-in-production-mode)).

**Comment by ktomk** [comment]
I brought the fix into develop, please try with the unstable version, you should see this fixed.

**Comment by hostep** [comment]
Just checked, can confirm this is now fixed with the latest develop version.

Thanks again Tom!
