### ISSUE TITLE
./bin/n98-magerun2 admin:user:change-password: Lock wait timeout exceeded

### ISSUE THREAD

**Issue by SchumacherFM** [netz98/n98-magerun2#242]
```
[user@server site]$ ./bin/n98-magerun2 admin:user:change-password usernameXYZ
Password:admin123
SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction, query was: INSERT INTO `admin_passwords` (`user_id`, `password_hash`, `expires`, `last_updated`) VALUES (?, ?, ?, ?)
```
n98-magerun2 version 1.3.0 by netz98 GmbH => Real version from composer.json is: `"n98/magerun2": "dev-develop", => 9affa3221415da8033267010d0ec4e14dab51e2b`

Magento 2.1.1 with PHP 7.0.11

If you need more informations, let me know.

Any idea what this can be?

**Comment by ktomk** [comment]
Mysql Table lock. Have you repeated it and turned it out to be working then?

**Comment by SchumacherFM** [comment]
It never works. Doesn't matter how many times I execute it.

**Comment by ktomk** [comment]
Sounds like the command is locking it's own table. I never used it in MR2 so far IIRC, the create admin user should work, I constantly make use of it. Requires further inspection, this sounds like a real flaw we have there.

**Comment by SchumacherFM** [comment]
For now I delete the admin user and re-create the admin ... but that is only OK on dev/staging systems.

**Comment by ktomk** [comment]
Can reproduce, have found a fix. Will push a fix-branch soon.

**Comment by ktomk** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.

**Comment by SchumacherFM** [comment]
Thanks you!
