### ISSUE TITLE
Cron Job List command sys:cron:list does not merges system config path values

### ISSUE THREAD

**Issue by atishgoswami** [netz98/n98-magerun2#244]
Hello Team,

The `sys:cron:list` command does not consider the path values saved in the `core_config_data` table.

Faced this [issue](https://github.com/netz98/n98-magerun/issues/727) in [n98-magerun](https://github.com/netz98/n98-magerun) version 1 as well.

Thanks

**Comment by tkn98** [comment]
Okay, I think we need to port the fix over to Magerun 2. I remember, yes. thanks for the report.

**Comment by cmuench** [comment]
@atishgoswami Fix will be included in v4.0.0.
