### ISSUE TITLE
db:dump sales strip too aggressive

### ISSUE THREAD

**Issue by rikwillems** [netz98/n98-magerun2#247]
The @sales strip for db:dump is too agressive. It also filters status and state tables. These should not be excluded as the contain valuable store setup data.

- sales_order_status
- sales_order_status_label
- sales_order_status_state

**Comment by tkn98** [comment]
Reminds me a recent issue. Can you check if this is still an issue with the development version?

**Comment by tkn98** [comment]
@rikwillems: Mentioned issue I remembered is here: https://github.com/netz98/n98-magerun2/issues/239

**Comment by rikwillems** [comment]
To be honest I only know how to work with the .phar. Can I create a .phar from the develop branch?

**Comment by cmuench** [comment]
You can run `n98-magerun2. phar self-update - - unstable`. 
We also provide a dev phar at https://files.magerun.net

**Comment by rikwillems** [comment]
Thank you @cmuench and @tkn98 the development version makes the order status tables come along with the dump.
