### ISSUE TITLE
Documentation for db:dump command is missing from the readme

### ISSUE THREAD

**Issue by mwgamble** [netz98/n98-magerun2#248]
If there's nothing significantly different between the Mage1 and Mage2 versions of this command, I can look into porting the documentation from the Mage1 version and submit a PR for it. Let me know!

**Comment by ktomk** [comment]
Sure, patches are always welcome. You can cross-check with `--help` as the built-in help is normally most up-to-date. A PR has the additional benefit that it gets some review, too. So just do as you see fit, if you have more questions don't hesitate to ask.

BTW check against the development branch README.md, master tends to be behind and IIRC on Github it shows master first. PR also against develop, not master (is mentioned in the Github PR template, too),

**Comment by ktomk** [comment]
@mwgamble: You still have interest to do this?
