### ISSUE TITLE
Add support for more area types in the dev:module:observer:list command

### ISSUE THREAD

**Issue by hostep** [netz98/n98-magerun2#249]
Hi

Today, I was surprised to find that to observe certain events in Magento2, you need to observe them from within the `webapi_rest` area. See this ticket I created and then closed after finding the solution: https://github.com/magento/magento2/issues/7524

It would be great if magerun2 could support that extra area in the `dev:module:observer:list` command.

I found even a bunch more area's which are defined in Magento2 currently: https://github.com/magento/magento2/blob/5448233594d94688b146564d7bdb882d6e88058a/lib/internal/Magento/Framework/App/Area.php#L18-L24

I'm not sure if all of those are actually valid area's where you can observe events, but it probably can't hurt to add those to the list in magerun2?

The change in magerun2 is probably very easy, as we just have to add those extra area's [over here](https://github.com/netz98/n98-magerun2/blob/ecdd092a9e0242cc4d461ee5ac57342e5b30155d/src/N98/Magento/Command/Developer/Module/Observer/ListCommand.php#L16-L21) I believe?

Maybe best to also keep an eye out for [this request to add more documentation](https://github.com/magento/devdocs/issues/908) regarding those area's in combination with events & observers.

What do you think?

**Comment by ktomk** [comment]
Okay, I can tell you by my colleagues feedback that you're not the only one who is surprised about that. ;)

Therefore I strongly feel that the suggestion you give is much valuable. We should cover all these standard (read: defined by these class AREA_* constants) areas.

The place you link with the constants should be authoritative and we should take the strings over. An integration test could check against [`ReflectionClass::getConstants`](http://php.net/manual/en/reflectionclass.getconstants.php) that we cover for the Magento version in question.

These areas are all valid from what I know.

Please let me know if you want to file a PR.

**Comment by hostep** [comment]
Ok, good to hear that there is a need for this :)

I can create a PR, including the test (which I have very little experience with, but it is always fun to learn new stuff). But it will probably take me a couple of days until I find some decent time to work on this unfortunately...

**Comment by ktomk** [comment]
You can do the PR an do with the test as you see fit (read: you can skip it for a moment if you feel uncertain or just comment if you're not confident with it). Most important is to add the missing areas for the moment (I think these are across all Magento 2.x versions so far).

**Comment by hostep** [comment]
There you go, I skipped the test because I couldn't find an example in the existing tests using Reflection, so I wouldn't know where to start :)

**Comment by ktomk** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.
