### ISSUE TITLE
n98-magerun2.phar admin:user:change-password throws an error

### ISSUE THREAD

**Issue by EliasKotlyar** [netz98/n98-magerun2#251]
Hello n98-magerun2-Team,

We have found a bug with the latest enterprise-edition:
```
n98-magerun2.phar admin:user:change-password
Username:<username>
Password:<password>
Circular dependency: Magento\Backend\Model\Auth\Session depends on Magento\Backend\Model\Authorization\RoleLocator and vice versa.
```
                              
Our System:
```              

+------------------+----------------------------------+
| name             | value                            |
+------------------+----------------------------------+
| Name             | Magento                          |
| Version          | 2.1.2                            |
| Edition          | Enterprise                       |
| Application Mode | developer                        |
| Session          | files                            |
| Crypt Key        | <crypt key> |
| Install Date     | Mon, 21 Nov 2016 14:54:12 +0000  |
| Cache Backend    | Cm_Cache_Backend_File            |
| Vendors          | Magento                          |
| Attribute Count  | 176                              |
| Customer Count   | 0                                |
| Category Count   | 2                                |
| Product Count    | 0                                |
+------------------+----------------------------------+

```
Note: Its vanilla Magento, no customisations were made

Greetings,
Elias

**Comment by tkn98** [comment]
Please run `generation:flush` and try again. If it still crashes, check if you can try as well with the development version. So far I can not reproduce this issue but I remember having see such an error.

**Comment by samgranger** [comment]
I am also experiencing this exact same issue but also with cronjobs. Running generation:flush does not seem to help.

This doesn't occur with every cronjob or command. I made a cron a while back without any issues and it still runs without any issues. I created a new blank cron which is failing however, which I stripped back entirely to only echo a string in the execute function. Sys information is identical to Elais'.

The admin:user:change-password command throws the same error here.

**Comment by ktomk** [comment]
@samgranger: Can you compile DI (for production) and check if there are some errors reported? I don't know if Magento 2 is able to statically detect circrefs, but compilation does some checks which might point you in the right direction.

**Comment by diazwatson** [comment]
It just happened to me and I fixed it by doing `bin/magento setup:di:compile` 
Make sure /var/ has the right permissions

**Comment by arkadij-K** [comment]
We have exact this issue on Magento 2.1.3.
``bin/magento setup:di:compile`` doesn't help nor ``bin/magento generation:flush``.
We did also ``rm -rf var/generation/ var/cache/ var/page_cache/ var/di/`` but no effect.

**Comment by ktomk** [comment]
@arkadij-K In which mode do you have the store running, default, developer or production?

**Comment by arkadij-K** [comment]
@ktomk It was in 'default' mode.

**Comment by ktomk** [comment]
I just tested it against the current stable and development version of magerun2 and a clean install of CE 2.1.3 in default mode and can not reproduce. So this probably is on enterprise only.

**Comment by EliasKotlyar** [comment]
Hello,

I have found this Error again on M2 EE 2.1.3:
`
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
| name             | value                                                                                                                                                 |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
| Name             | Magento                                                                                                                                               |
| Version          | 2.1.3                                                                                                                                                 |
| Edition          | Enterprise                                                                                                                                            |
| Application Mode | developer                                                                                                                                             |
| Session          | files                                                                                                                                                 |
| Crypt Key        | <crypt>                                                                                                                     |
| Install Date     | Fri, 27 Jan 2017 12:20:42 +0000                                                                                                                       |
| Cache Backend    | Cm_Cache_Backend_File                                                                                                                                 |
| Vendors          | <Modules> |
| Attribute Count  | 274                                                                                                                                                   |
| Customer Count   | 1671                                                                                                                                                  |
| Category Count   | 68                                                                                                                                                    |
| Product Count    | 136                                                                                                                                                   |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+

`

I have found a dirty Quickfix for that error:

You should uncomment the following Line in magento/vendor/magento/module-backend/etc/di.xml:74

<preference for="Magento\Framework\Authorization\RoleLocatorInterface" type="Magento\Backend\Model\Authorization\RoleLocator" />

After that, everything is working fine. I can confirm that its appearing on EE only.

Greetings
Elias

**Comment by tkn98** [comment]
@EliasKotlyar Thanks for the update, Is that this file/line:

https://github.com/magento/magento2/blob/2.1.3/app/code/Magento/Backend/etc/di.xml#L74

~~~
<preference for="Magento\Framework\Authorization\RoleLocatorInterface" type="Magento\Backend\Model\Authorization\RoleLocator" />    
~~~

And have you had any chance to test this against EE 2.1.5?

**Comment by EliasKotlyar** [comment]
Hello tkn98,

Yes, its this line which i have uncommented.  Unfortunately , we are still on 2.1.3 and will not update to prior to 2.2

Greetings
Elias

**Comment by EliasKotlyar** [comment]
I found another Bug in the Magento 2.2 B2B Edition. 
My System:
Magento 2.2.2 EE
B2B Extension 1.0.2

The original one was solved by Magento.

The Following Plugin from the B2B Extension is responsible for this error:

```
    <type name="Magento\User\Model\User">
        <plugin name="aroundAdminUserSave" type="Magento\NegotiableQuote\Model\Plugin\User\Model\User" />
    </type>
```


I have disabled this module, due that we are not using this feature.

**Comment by cmuench** [comment]
@EliasKotlyar Can you verify if your problem still exists? With the 2.3.3 release we should have delivered a fix for the change-password commands.
For me it is working in my local 2.2.6 EE environment.

**Comment by EliasKotlyar** [comment]
I can confirm that this bug is fixxed on a EE 2.2.7. I cannot guarantee for other versions.

**Comment by cmuench** [comment]
@EliasKotlyar Thanks for checking. I close this ticket. If anyone has problems, we can reopen it again.
