### ISSUE TITLE
PHP 7.1 support

### ISSUE THREAD

**Issue by ktomk** [netz98/n98-magerun2#256]
Since 1 Dec 2016 PHP 7.1 stable has hit earth surface. Support for that version of the language is most likely to be requested therefore Magerun 2 should support it.

- [x] Lint Magerun 2 code with PHP 7.1
- [x] Run PHP-CS-Fixer with PHP 7.1 on Magerun 2 code
- [x] Build Magerun 2 with PHP 7.1
- [x] Run the Phpunit test-suite (w/o Magento 2 installation) with PHP 7.1
- [x] Install Magento 2 running Magerun 2 with PHP 7.1
- [x] Run the Phpunit test-suite (on the Magento 2 installation) with PHP 7.1

**Comment by tkn98** [comment]
Another build task could be to run the Phpunit test-suite w/o installing Magento (would be unit-tests only, integration tests are skipped when no Magento application is found).
