### ISSUE TITLE
n98-magerun2 db:dump --stdout appears to be broken. 

### ISSUE THREAD

**Issue by fliphess** [netz98/n98-magerun2#258]
When i use `n98-magerun2 db:dump` with the feature flag `--stdout` enabled, no output is returned to stdout. 

```
app@er59pg-zxcvbnm-magweb-do:~$ n98-magerun2 db:dump --root-dir=/data/web/magento2  --strip="@stripped"   --stdout
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
app@er59pg-zxcvbnm-magweb-do:~$
```

**Comment by ktomk** [comment]
It is buggy at least. Can reproduce, creates a file named "`.sql`" in the current working dir. Most likely the command needs to be updated with the changes from Magerun 1, I smell some there fixed bugs.

**Comment by ktomk** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.

**Comment by ktomk** [comment]
This took a bit longer as the db:dump command needed some maintenance work under the hood. It should now work as expected again.

There might be an issue with mysql database on commandline warnings, so please check if this works well for your case. If you run into any problems, please report back.
