### ISSUE TITLE
db:dump command does not work with socket connection

### ISSUE THREAD

**Issue by bery** [netz98/n98-magerun2#259]
Hi,

db:dump command fails if the connection to the database is configured using a socket rather than IP address. Sample output:

~~~
magerun2 db:dump


  Dump MySQL Database


Filename for SQL dump: [2016-12-19_100909_project_stage.sql]
Start dumping database jlr_stage to file 2016-12-19_100909_project_stage.sql
Unknown suffix 'e' used for variable 'port' (value 'europe-west1')
mysqldump: Error while setting value 'europe-west1' to 'port'
Finished
~~~

Would it be possible to make the db:dump command compatible with database connection made using sockets?

**Comment by tkn98** [comment]
Sockets should be supported. Can you share the magerun version you're using?

**Comment by bery** [comment]
magerun2 --version says

n98-magerun2 version 1.2.2 by netz98 new media GmbH

Do you mean that sockets should work already?

**Comment by ktomk** [comment]
Please upgrade to version 1.3.0 and try. I know that it should work. If it doesn't work in the latest stable we should fix it. The config/db routines do support sockets so this looks like a flaw to me. But please check against the latest version first.

**Comment by bery** [comment]
Will do and will let you know, thanks for your quick reply!

**Comment by ktomk** [comment]
Please provide an excerpt of your `app/etc/env.php` which shows the database configuration (please mask any secure credentials).

**Comment by bery** [comment]
I have tried to update magerun to the latest version as suggested (1.3.0) and the erorr stil persist. 

env.php, when using google cloud DB service:
```
...
array (
    'connection' =>
    array (
      'indexer' =>
      array (
        'host' => '/cloudsql/project-name:region:name',
        'dbname' => 'db_name',
        'username' => 'user',
        'password' => 'pass',
        'model' => 'mysql4',
        'engine' => 'innodb',
        'initStatements' => 'SET NAMES utf8;',
        'active' => '1',
        'persistent' => NULL,
      ),
      'default' =>
      array (
        'host' => '/cloudsql/project-name:region:name',
        'dbname' => 'db_name',
        'username' => 'user',
        'password' => 'pass',
        'model' => 'mysql4',
        'engine' => 'innodb',
        'initStatements' => 'SET NAMES utf8;',
        'active' => '1',
      ),
    ),
    'table_prefix' => '',
  ),
...
```

**Comment by ktomk** [comment]
By providing the full information, it's now visible what the issue is. You're using the wrong setting to specify the socket. The correct name is "`unix_socket`", you're using "`host`".

If you replace it, this should work already. Leave *host* out or empty (zero-length string), set *unix_socket*.

Please let me know if this solves your issue.

**Comment by bery** [comment]
Worked as a charm, perfect, thanks. For the future reference, should somebody come across the same issue:
```
array (
        // we are using sockets, but host is a required parameter
        'host' => '',
        'unix_socket' => '/socket-path/here',
        'dbname' => 'db_name'
        ....,
```

Host is a required value and needs to be set to an empty string as suggested.
