### ISSUE TITLE
Module code generation Setup template wrong

### ISSUE THREAD

**Issue by jurgisl** [netz98/n98-magerun2#261]
Setup template for UpdateData script is wrong. Class is named UpdateSchema not UpdateData, and there is not defined namespace for ModuleDataSetupInterface.

https://github.com/netz98/n98-magerun2/blob/master/res/twig/dev/module/create/app/code/module/Setup/UpgradeData.php.twig

**Comment by tkn98** [comment]
Thanks for the report and PR!

We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.
