### ISSUE TITLE
cache:flush does not send purge command to Varnish

### ISSUE THREAD

**Issue by iancassidyweb** [netz98/n98-magerun2#265]
**Issue**
When running the n98 cache:flush command Varnish is not purged. However, When flushing the 
cache via Magento's bin/magento cache:flush Varnish is purged correctly.

See the following file for reference.

`module-cache-invalidate/Observer/FlushAllCacheObserver.php`

**Steps to Replicate**
1. Install Magento CE or EE (tested on CE 2.1.3)
2. [Add Varnish HTTP Cache Hosts to your env.php file ](http://devdocs.magento.com/guides/v2.0/config-guide/varnish/use-varnish-cache.html)
`magento setup:config:set --http-cache-hosts=192.0.2.100:6081`
3. Run n98 cache:flush 
4. Varnish cache is not purged 

**Expected Result**
When running n98 cache:flush Varnish should be cleared if the --http-cache-hosts have been defined in the env.php file. 

**Actual Result**
Varnish is not cleared.

**Comment by tkn98** [comment]
Can you please check with the development version? We recently have fixed #263 which seems to be related as now an event is triggered which previously was not.

**Comment by cmuench** [comment]
Closed due to missing feedback.
