### ISSUE TITLE
Install Command fails with "[RuntimeException]   Installation failed."

### ISSUE THREAD

**Issue by DavidLambauer** [netz98/n98-magerun2#267]
When I run n98-magerun2.phar install and follow the Guide, I end with the following Exception:

`[RuntimeException]   Installation failed.`

Environment is the following:
PHP: 7.0.13
Magerun: 1.3.1

This is a Screenshot, where you should able to reproduce.

<img width="1905" alt="screenshot at feb 05 22-42-45" src="https://cloud.githubusercontent.com/assets/1841317/22630145/7ad640d2-ebf4-11e6-98a6-f28928c01387.png">

**Comment by tkn98** [comment]
Hi David, please run the command verbatim (you can see it in the middle) and try to find out what went wrong. Magerun runs it and if it fails you see this exception.

**Comment by DavidLambauer** [comment]
Hey Tommy,

thanks for the quick answer. Now I am able to see an Exception. 

`/usr/bin/env php /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/bin/magento setup:install --language='de_DE' --timezone='Europe/Berlin' --db-host='127.0.0.1:32768' --db-name='demoshopintergration' --db-user='root' --base-url='http://demoshop.dev/' --use-rewrites='1' --use-secure='0' --use-secure-admin='1' --admin-user='admin' --admin-lastname='Doe' --admin-firstname='John' --admin-email='john.doe@example.com' --admin-password='password123' --session-save='files' --backend-frontname='admin' --currency='EUR' --db-password='root' --base-url-secure='https://demoshop.dev/'
PHP Fatal error:  Uncaught Error: Class 'Locale' not found in /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/vendor/magento/framework/Locale/Bundle/DataBundle.php:64
Stack trace:
#0 /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/vendor/magento/framework/Locale/Bundle/DataBundle.php(28): Magento\Framework\Locale\Bundle\DataBundle->cleanLocale('en_US')
#1 /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/vendor/magento/framework/Setup/Lists.php(80): Magento\Framework\Locale\Bundle\DataBundle->get('en_US')
#2 /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/vendor/magento/framework/Validator/Locale.php(42): Magento\Framework\Setup\Lists->getLocaleList()
#3 /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/setup/src/Magento/Setup/Console/Command/InstallStoreConfigurationCommand.php(307): Magento\Framework\Validator\Locale->isValid('de_DE')
#4 /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/setup/src/Magento/Setup/Console/Command/InstallStoreConfigurationCommand.php(197): Mag in /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/vendor/magento/framework/Locale/Bundle/DataBundle.php on line 64

Fatal error: Uncaught Error: Class 'Locale' not found in /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/vendor/magento/framework/Locale/Bundle/DataBundle.php:64
Stack trace:
#0 /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/vendor/magento/framework/Locale/Bundle/DataBundle.php(28): Magento\Framework\Locale\Bundle\DataBundle->cleanLocale('en_US')
#1 /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/vendor/magento/framework/Setup/Lists.php(80): Magento\Framework\Locale\Bundle\DataBundle->get('en_US')
#2 /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/vendor/magento/framework/Validator/Locale.php(42): Magento\Framework\Setup\Lists->getLocaleList()
#3 /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/setup/src/Magento/Setup/Console/Command/InstallStoreConfigurationCommand.php(307): Magento\Framework\Validator\Locale->isValid('de_DE')
#4 /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/setup/src/Magento/Setup/Console/Command/InstallStoreConfigurationCommand.php(197): Mag in /Volumes/Data/Entwicklung/Workspace/netz98/Shops/DemoShop/vendor/magento/framework/Locale/Bundle/DataBundle.php on line 64`

For now I am able to debug it. I'll let you know what happens, when I found out. In general it would be nice, to see the exact same Error Message when running the mr2 command. I'll have a look into that as well.

**Comment by tkn98** [comment]
The error output should be visible with Magerun, too. I tag this a a bug.

**Comment by DavidLambauer** [comment]
I found the reason for my problem. /usr/bin/env php doesn't use my aliased php version and due to that, some extensions like php intl are missing. For usability reasons, this should be checked, before running a command. What do you think?

**Comment by tkn98** [comment]
David, please upgrade to the latest unstable version. Magerun should use for the installer the same PHP binary that is used for Magerun itself.

**Comment by tkn98** [comment]
From a quick check, I'd say this needs forward porting from Magerun 1. We have these issues incl. the better display of errors and the correct PHP binary fixed.
