### ISSUE TITLE
Add Magento version 2.0.12 and 2.1.4

### ISSUE THREAD

**Issue by hostep** [netz98/n98-magerun2#270]
Since you are planning on releasing a new version today, it might be worth to add the latest versions of Magento which got released this week.

**Comment by ktomk** [comment]
Jup, let's flush them in. I'll do this.

**Comment by ktomk** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.
