### ISSUE TITLE
Magerun2 is no longer installable using composer in a Magento project due to composer/composer ^1.3.0 constraint

### ISSUE THREAD

**Issue by hostep** [netz98/n98-magerun2#271]
Hi

I'm back with yet another new issue when trying to install magerun2 using composer 😉 

I have a Magento 2.1.4 project where magerun2 version 1.3.0 is installed, but upgrading to 1.3.1 is not working:
```bash
$ composer why-not n98/magerun2 1.3.1
n98/magerun2        1.3.1        requires          composer/composer (^1.3.0)
vendor/our-project  dev-develop  does not require  composer/composer (but 1.0.0-beta1 is installed)
```

In version 1.3.0 of magerun2, the constraint of the `composer/composer` package was set to `^1.0.0`, but in version 1.3.1 this was increased to `^1.3.0`: https://github.com/netz98/n98-magerun2/compare/1.3.0...1.3.1#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

But since Magento for some unknown reason [still hasn't updated their composer dependency](https://github.com/magento/magento2/issues/4359) to something other then `1.0.0-beta1` this doesn't work together.

Was there a reason for upgrading to at least version 1.3.0 of the `composer/composer` package?
If not, then I would suggest you revert this back to `^1.0.0`.

~~If there indeed was a good reason, then we again have to change the `composer.json` file of our project and change the line: `"composer/composer": "@alpha",` to: `"composer/composer": "1.3.2 as 1.0.0-beta1",`. After this change, we can upgrade magerun2 to version 1.3.1 :)~~

**UPDATE**: the above solution doesn't work (I should have actually tested it before posting :p).
This is because since `composer/composer` version 1.3.0 they [require](https://github.com/composer/composer/commit/eb40287691645157ac2f079930265baad9cd7295) `symfony/console` to be at least version 2.7 or higher, and currently Magento 2.1.4 [prevents this](https://github.com/magento/magento2/blob/2.1.4/composer.json#L46) from working, but this will [change again in Magento 2.2 probably](https://github.com/magento/magento2/pull/8151/commits/c6ef98fccd64be22d03941f2ea3a5138333be931)

Pfff, dependency management can be complicated sometimes :)

**Comment by ktomk** [comment]
Reason is I wanted to have the current stable composer version as I've integrated it into the build, so the build has all commands after composer install - incl. composer. I know it's kind of a hen and egg problem.

If I read your report right, it's that for 13.1 you need to change the composer.json in the Magento project so that composer installs the magerun dependency. But you also needed to modify this earlier, just with a different change.

So technically it is the old issue that I remember (but can't find the issue number right now) and we can go back to the previous version constraint, albeit if you already upgraded and this needs a workaround anyway, would this make a difference?

**Comment by ktomk** [comment]
@hostep: To solve both problems, we could create specially tagged versions in git that contain a compatible composer.json. You then could require that version I guess with `-dev` suffix.

For the console problem, I have seen this coming the other day, we could also solve that with it if it works out.

I've created a new tag called `depdev-1.3.2`, let me know if you can require that version with composer. Right now that version contains the previous `^1.0.0` composer requirement. If this works out, we can even downgrade further to make the inline alias in your project not necessary any longer.

https://github.com/netz98/n98-magerun2/commit/d902db49bc0886e37620ebb0b9a6ff5633b366ce

**Comment by hostep** [comment]
Thanks Tom

I'll try to check this out later today. Bit swamped at the moment :)

The alias would never have worked anyways, since the composer resolver would have seen it as `1.0.0-beta` instead of `1.3.2`, I don't know what I was thinking yesterday, sorry if this caused any confusion.

**Comment by tkn98** [comment]
No not all, it's good to get a quick report. You have a thinking person at the other end as well ;). Would be great this tagging works (I might be able to test this locally over the day, too) and we can eradicate the workaround anyway.

**Comment by hostep** [comment]
Hi Tom

Can confirm that downgrading the `composer/composer` constraint to `^1.0.0` makes it work again.
But unfortunately your tag name is not supported by composer:
```
➜ composer require n98/magerun2:depdev-1.3.2
  [UnexpectedValueException]
  Could not parse version constraint depdev-1.3.2: Invalid version string "depdev-1.3.2"
```

So I had to get a bit more creative and cloned the magerun2 repo, then used the [Path repo type](https://getcomposer.org/doc/05-repositories.md#path) of composer to be able to use my clone of this project.
I then tagged your `depdev-1.3.2` as `1.3.2` on my local machine, so composer could pick it up like that, and that worked!


Anyways, if you need some steps to be able to reproduce the actual problem:

```bash
$ composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition ./m2

    Authentication required (repo.magento.com):
      Username: aabbccdd...
      Password:
Do you want to store credentials for repo.magento.com in ~/.composer/auth.json ? [Yn] n
Installing magento/project-community-edition (2.1.4)
...
Writing lock file
Generating autoload files

$ cd m2

$ composer require n98/magerun2
Using version ^1.3 for n98/magerun2
./composer.json has been updated
...
  - Installing n98/magerun2 (1.3.0) Loading from cache
...
Writing lock file
Generating autoload files

$ composer why-not n98/magerun2 1.3.1
n98/magerun2                       1.3.1  requires          composer/composer (^1.3.0)
magento/project-community-edition  2.1.4  does not require  composer/composer (but 1.0.0-beta1 is installed)

# Then after cloning the repo and changing the repo in my composer.json file to the path type and re-tagging your depdev-1.3.2 to 1.3.2, like described above:

$ composer update
...
Package operations: 0 installs, 1 update, 0 removals
  - Removing n98/magerun2 (1.3.0)
  - Installing n98/magerun2 (1.3.2.0) Symlinked from /path/to/my/clone/of/n98-magerun2
```


I'm afraid that if you are going to continue supporting n98/magerun2 to be installed using composer, there is currently no way back to revert the constraint to `^1.0.0`.
In your case this shouldn't be a problem, as you'll always get the latest version of `composer/composer` (as long as they don't release a version 2.0), but for people who install magerun2 using composer inside a Magento2 project, they will currently (due to Magento's fault) be stuck on version 1.0.0-beta1. For me this is no problem.

What do you think?

**Comment by ktomk** [comment]
@hostep: I have done some tests on my end as well. I don't have  followed your scenario exactly yet, just ran some tries before that and now I managed this similar to yours as I quickly read it. I have done the create-project step at first and then I do the following:

    $ composer require n98/magerun2:dev-magento2-composer/1.3.2

This worked on my end. It does not work with tags as you have found out as well, but it works with branches. Please try it your own.

If you use a recent 1.3.* composer as the command to do it, it will also cache the git repo so that you will see an acceptable performance with it.

**Comment by hostep** [comment]
Alrighty, yes this works indeed. So we have now confirmed that changing the constraint back to `^1.0.0` solves the issue of not being able to install the latest version of magerun2 using composer.

In your opinion, is there a downside to changing this constraint back? Because you were talking about maintaining two different versions of this package, one for installations using composer, and the other for phar files. I think this is not necessary and don't really see the point in doing this?

If the constraint is put back to `^1.0.0`, then both those installation types should work perfectly fine. Or am I missing something obvious here?

**Comment by ktomk** [comment]
Oh actually not at all! The error is on my side, I've misunderstood the caret notation `^1.0.0`  will semver just up to but not `2.0.0`. So technically in the `composer.lock` file this means having the latest version. So actually a simple "my fault" here - I'm actually sorry for the interruption.

So I must admin, now I see a point in this any longer. A lesson learned. You can find the `1.3.2` version now released with `^1.0.0` given. I also tested it, should work with `composer create-project`.

About the question why Magento does not upgrade the requirement, I can't answer this precisely. A colleague I talked about this today, reminded me that I once was telling him and showing why (they use something that is in the version they use but went away with stable) but I don't remember this precisely so I can't share a link to github with that change. I hate it when it's that oral only and from memory, as it's not precise and does not help to better understand it. Given the silence these two Magento 2 issues have, I assume it is of such kind. If I stumble over it again, I'll think of you.

Okay, this all looks good in my testbed, please give it a try. And sorry again for the hurdles while you're already swamped.

**Comment by hostep** [comment]
Awesome, thanks once again! No problem for the hurdles, I made it too difficult myself with my initial post which contained a lot of incorrect information.

Can confirm I can now again upgrade to a stable magerun2 1.3.2 version, so that makes me happy :)

**Comment by ktomk** [comment]
Well I also had in mind wrongly that ^1.0.0 would require patching the composer.json with an inline alias which isn't the case either. And great to see we're working for happiness in the end :).
