### ISSUE TITLE
Phpunit autoloading on Travis conflicts with Magento 2 while integration testing

### ISSUE THREAD

**Issue by tkn98** [netz98/n98-magerun2#272]
(via: ##266) We need to fix the travis build and/or need to align the PhpUnit version. Due to Magento2 dev requirements (which we hopefully don't need but just install) there is a conflict with autoloading in Magento 2 and Magerun 2 for Phpunit.

* https://travis-ci.org/netz98/n98-magerun2/jobs/202162135
* Let's just cross fingers for a momemt that issues like https://github.com/magento/magento2/issues/1690 are fixed.

Locally I've done that with the `--no-dev` switch and at least testing did work then.

**Comment by ktomk** [comment]
Fixed in https://github.com/netz98/n98-magerun2/commit/9534d3f0524088ad5120f39657513a06f7ba31cc
