### ISSUE TITLE
Include guidance on checksuming the .phar

### ISSUE THREAD

**Issue by mpchadwick** [netz98/n98-magerun2#279]
The README for n98-magerun includes guidance on checking checksuming the PHAR file, however the same guidance is not available, AFAICT in the README for this repo.

**Comment by ktomk** [comment]
@mpchadwick: Yes, there is an issue with the default branch on Github. We should change it to the development branch then the latest information is available and it's easier to contribute.

@cmuench: Can you change the default branch to "develop" and place a link to the Magerun Homepage in the project description (compage to Magerun 1)?

**Comment by cmuench** [comment]
The default branch is now set to "develop".

**Comment by cmuench** [comment]
@ktomk The default branch is switched. I don't understand the issue here? Can you help me?

**Comment by ktomk** [comment]
@cmuench It's the note on how to checksum. I can update that later today and close this one afterwards. Nowadays both repos need an update.

**Comment by ktomk** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.
