### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by FluroShift** [netz98/n98-magerun2#284]
Hello!
I'm trying to install Magento 2 through magerun2 on a server with a SSh connection. I've tried a few different approaches for installing magento, but I keep getting the same error over and over again. I've included a picture of the error.
![knipsel](https://cloud.githubusercontent.com/assets/15103015/25228035/1323f702-25cb-11e7-9f37-857cc5bd5893.PNG)

**Comment by FluroShift** [comment]
The command i entered is: php -f bin/n98-magerun2 -- install

**Comment by cmuench** [comment]
This looks like a local permission problem to me. Can you check the folder permissions?

**Comment by fedekrum** [comment]
Same error here.
All local permissions OK.
Tried even being root and had the same error.
n98-magerun2 is able to download composer to the target folder, so n98-magerun2 has permissions to write to it.

May be I am missing something, but I cant get a solution.
A good thing  n98-magerun2 can do for us, is to give a clue of which directory was not accesible and the kind of denial it has receibed.

**Comment by FluroShift** [comment]
@fedekrum I solved this by bypassing the whole downloading step. Just manually download the magento files you want to use and place them on your local or external server you want to install magento on using n98-magerun2. Then run the original install command with --noDownload at the end to tell n98-magerun2 that the magento files are already in place. Hope this helps!
