### ISSUE TITLE
Running an n98 script ignores --skip-root-check

### ISSUE THREAD

**Issue by wrsenn** [netz98/n98-magerun2#285]
If running an n98 script file (i.e. `n98-magerun2 script <filename>`) as root with `--skip-root-check`, the root warning still fires for each individual command within the script file.

**Comment by cmuench** [comment]
@wrsenn I cannot reproduce a wrong behaviour.
One common problem is that the "--skip-root-check" option must be placed before the command call.

Correct:
`n98-magerun2.phar --skip-root-check script <filename>`

Wrong:

`n98-magerun2.phar script --skip-root-check <filename>`

**Comment by cmuench** [comment]
Closed according to missing response. Please re-open if the problem still exists.
