### ISSUE TITLE
n98-magerun2 not working within a project in PHP Storm.

### ISSUE THREAD

**Issue by jay-metmeer** [netz98/n98-magerun2#286]
Hi,
I'm currently working on a few different projects, but n98-magerun2 won't excute within a certain project in PHPStorm IDE after running  n98-magerun2 setup:upgrade at initial setup of project.

**Comment by cmuench** [comment]
@jay-metmeer Thank you for reporting your issue. Please provide more informations.
How do you execute n98-magerun2 in your PHPStorm IDE?

**Comment by cmuench** [comment]
Closed due to missing response. Please re-open of the problem still exists.
