### ISSUE TITLE
sys:cron:run can only run crons in group 'default'

### ISSUE THREAD

**Issue by PascalBrouwers** [netz98/n98-magerun2#288]
Version: 1.4.0

sys:cron:run can only run crons in group 'default'. When I try to run a run in the 'index' group using `sys:cron:run indexer_update_all_views` I get:
`Notice: Undefined index: name in phar:///Users/pascal/Sites/kingdo2/n98-magerun2.phar/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php on line 97`

**Comment by cmuench** [comment]
@PascalBrouwers Thanks for reporting. I try to find a fix for the issue.

**Comment by cmuench** [comment]
@PascalBrouwers I checked this in a current Magento 2.1.6 release and it seems to work. We get the cron job list from Magento `\Magento\Cron\Model\ConfigInterface`. This could be a bug in an older Magento version. Can you provide your used Magento version?

**Comment by PascalBrouwers** [comment]
Hmm, must be something wrong with my 2.1.4 installation. A clean install of 2.1.4 does not give this problem. Maybe some module is interfering.

**Comment by cmuench** [comment]
@PascalBrouwers ok. Thanks for checking. I close the ticket. If anyone could reproduce the issue we can reopen it again.
