### ISSUE TITLE
Sync Optimize with magerun1 / autocommit=0 missing

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#290]
The autocommit=0; + COMMIT options should be added

see

https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Database/ImportCommand.php#L59

As I don't understand that shared folder thing (where I believe it should be moved) - I can not provide a pull request... :-(

Can you fix it?

**Comment by amenk** [comment]
Seriously ... I sure can copy&paste the function from magerun1 ... but how can it be properly done? Could you extract the DB Helper functions in the proper way for me @tkn98 ? I can then adapt the optimize code.

**Comment by ktomk** [comment]
Files that are exactly the same can move into shared. But that is not to make files exactly the same, just how the shared folder works.

The rest is forward porting and extracting. Often I can cherry pick from one repo into the other or vice/versa, even w/o conflicts (change log sometime has these, but that's not to prevent).

**Comment by amenk** [comment]
@cmuench thanks for merging ... a bugfix release would be awesome...

**Comment by amenk** [comment]
@cmuench @ktomk could you make a release 1.4.1 ? or shall I make one?

**Comment by cmuench** [comment]
Version 1.5.0 will be released today. Stay tuned.
