### ISSUE TITLE
Admin password expires despite recent change

### ISSUE THREAD

**Issue by robbertstevens** [netz98/n98-magerun2#293]
When I update the password with the command the password expire message doesn;t get reset. So even if I change it everyday I still get notification I need to change my password.

**Comment by ktomk** [comment]
I guess the timestamp column needs to be updated as well, needs a closer look in Magento 2, I made some notes with the previous report in Magerun 1.

        # setNewPassword()
        # getPciAdminUserIsPasswordExpired
        # lock_expires
        # yyyy-MM-dd HH:mm:ss

**Comment by cmuench** [comment]
Possible fix merged in develop branch. Called the password changed tracking method.

**Comment by cmuench** [comment]
Fix as 3.2.0 released.
