### ISSUE TITLE
spelling error inside the installation

### ISSUE THREAD

**Issue by makoeppel** [netz98/n98-magerun2#302]
./n98-magerun.phar --version I think it should be ./n98-magerun2.phar --version

**Comment by cmuench** [comment]
@makoeppel Yes, Thanks for the hint. Waiting for your first  n98-magerun2 PR ;-)

**Comment by opiumated** [comment]
Based on this open issue, there are other areas in the CLI were tiny spelling errors are found like Flushs instead of Flushes etc.
