### ISSUE TITLE
Porting command: admin:user:create

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#31]
Create admin user.

**Comment by cmuench** [comment]
Already part of Magento 2 core (please note that values must be passed as options)

**Comment by ktomk** [comment]
I'd say for portability of setup scripts / configuration management (hs:ccd with scripts), it could be of benefit to have a compatible command available.

**Comment by cmuench** [comment]
@ktomk Some mechanics in magento are really different. It should be not a big effort to update existing commands. I don't know how we can be compatible without replacing the original core command.

**Comment by ktomk** [comment]
I thought more about aliasing the command and mapping options, not re-creating core functionality. If it can't be compatible (e.g. new mandatory option), then my idea won't work.
