### ISSUE TITLE
dev:template-hints not working with Magento 2.2.0

### ISSUE THREAD

**Issue by tommypyatt** [netz98/n98-magerun2#333]
Template hints toggling was working on my Magento 2.1.7 dev instance, but seems not to work after updating to 2.2.0.

```
~/repos/magento2 (develop ✘)✖✹✭ $ mr2 dev:template-hints
Template Hints enabled for store default
```

Output implies template hints should be enabled, but they aren't active on the frontend.

**Comment by tommypyatt** [comment]
The CLI output seems to be correct (if template hints are enabled in the admin panel, message will be `Template Hints disabled for store default`) however the database value seems to stay the same:

```
+-----------+---------+----------+-------------------------------------+-------+
| config_id | scope   | scope_id | path                                | value |
+-----------+---------+----------+-------------------------------------+-------+
|        41 | default |        0 | dev/debug/template_hints_storefront | 1     |
+-----------+---------+----------+-------------------------------------+-------+
```

This makes me assume that the problem is not that the logic is getting/setting the incorrect value, but that the set is maybe failing silently.

**Comment by cmuench** [comment]
Confirmed in my local dev environment.

**Comment by cmuench** [comment]
@tommypyatt Fix is in development version. If you want test it, please upgrade to unstable version.
`n98-magerun2.phar self-update --unstable`

**Comment by tommypyatt** [comment]
@cmuench tested and verified fixed. Thanks! 😸
