### ISSUE TITLE
Porting command: cache:clean

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#34]
Clean magento cache

**Comment by cmuench** [comment]
Ported.

**Comment by EliasZ** [comment]
Heh, I was also working on this (and #37). Pushed to [develop-37-34](https://github.com/eliasz/n98-magerun2/tree/develop-37-34) branch. Let me know if you want to do anything with the code, otherwise I will delete the branch and sync with upstream.

**Comment by EliasZ** [comment]
To prevent this from happening in the future maybe tag issues which are being worked on?

**Comment by cmuench** [comment]
@EliasZ :-) Sorry. We are too fast. I created a new label "in progress".
