### ISSUE TITLE
Question: How to extend magerun2 commands?

### ISSUE THREAD

**Issue by djfordz** [netz98/n98-magerun2#345]
In n98-magerun, there is documentation on how to extend commands with your own, you then put them in ~/.n98-magerun/modules/

However n98-magerun2 I cannot find any documentation on how to extend commands.

Can I get a brief explanation on how to do this? I've created my own magerun2 commands and I would like to integrate them into my workflow.

**Comment by djfordz** [comment]
Seems the same.

**Comment by cmuench** [comment]
@djfordz you can place them into `~/. n98-magerun2/modules`.
I will try to copy the wiki of n98-magerun to v2.

**Comment by djfordz** [comment]
yup, works great! thank you.
