### ISSUE TITLE
eav:attribute:list throws error "Invalid entity_type specified: 19"

### ISSUE THREAD

**Issue by gerben86** [netz98/n98-magerun2#346]
I'm running magerun2 2.0.0
When I execute this command: "n98-magerun2.phar eav:attribute:list" I get this error:
>   [Magento\Framework\Exception\LocalizedException]
>   Invalid entity_type specified: 19

I'm doubting if this is due to a bug in Magerun, I expect a setup issue on my M2.1.10 installation, but where should I start looking?

Thanks!

**Comment by cmuench** [comment]
@gerben86 Please have a look into eav_attribute database table if there is an attribute with the invalid entity type id '19'.
Or add the ID 19 to eav_entity_type table.
Normally this is not possible due to database constraints. Looks like a database with integrity issues.

**Comment by gerben86** [comment]
Hi, thanks! That was indeed the issue!
