### ISSUE TITLE
Can't update n98/magerun2 from 2.1.0 to 2.1.2 using composer in a Magento 2.2 project

### ISSUE THREAD

**Issue by hostep** [netz98/n98-magerun2#349]
```
$ composer show n98/magerun2
name     : n98/magerun2
descrip. : Tools for managing Magento projects and installations
keywords : cli, installer, magento, magerun2
versions : * 2.1.0
type     : library
...

$ composer why-not n98/magerun2:2.1.2
n98/magerun2             2.1.2    requires          composer/composer (^1.6.0)
vendor/our-mage-project  develop  does not require  composer/composer (but 1.4.1 is installed)
```

This problem was introduced in https://github.com/netz98/n98-magerun2/commit/f8590127bcf63c3e792a2d1235ab78b00c9603dc
Magento 2.2.0 and up have a [hardcoded dependency](https://github.com/magento/magento2/blob/2.2.0/composer.json#L42) on `composer/composer` v1.4.1

My suggestion would be to change the constraint to `^1.4` or even back to `^1.0` because they will all result in the latest of v1.x to be installed when installing `n98/magerun2` separately. And if you install `n98/magerun2` within a Magento 2.2.x project, it will install v1.4.1 of `composer/composer`

Thanks! :)

**Comment by ktomk** [comment]
Sounds good to me, `^1.0`  should handle all these cases and leave enough room for composer to do the resolution.

**Comment by hostep** [comment]
Thanks for the confirmation @ktomk, PR created: https://github.com/netz98/n98-magerun2/pull/352

**Comment by cmuench** [comment]
If we revert this we will also have issues with current Magento 2.2.2.
We need at least Composer V1.4 because of some autoloading issues.

**Comment by cmuench** [comment]
We can change back to `^1.0` but we need to run "composer update" to lock a newer version for the phar file contribution.

**Comment by hostep** [comment]
@cmuench: ok, I updated my PR and changed the constraint to `^1.4`, if < 1.4 has known issues, then we should definitely put it at `^1.4`

Just out of curiosity, can you give me some insight or links to the autoloading issues you mention?

**Comment by ktomk** [comment]
I see. Hmm. Sounds like we need different phar builds for different Magento versions. There is one tool that (tries to) rename all the classes so you can create your own phar with the dependencies the utility itself needs while not toughing the commonly known ones.

The suggestion I gave with ^1.0 is for a composer based installation which leaves the dependency resolution to the dependency manager than. Howeever what Christian commented about is for the scenario of the phar (I assume) where Composer can't do that any longer as the phar file is already built.

So far we have pretty well managed to solve these problems but it's perhaps at a turning point. Maybe it's viable we can remove composer as a dependency from Magerun? That could lighten up the dependency problems, but I think Christian could say better. IIRC we don't use that much from it, but it is used for self-updating Magerun and perhaps a bit more.

**Comment by cmuench** [comment]
@hostep This issues are related #342 #348

**Comment by hostep** [comment]
#348 seems to be a bug in certain composer versions (1.6.0 & 1.6.1): https://github.com/composer/composer/releases, which was fixed in 1.6.2

Not sure about #342 though (might have been the same problem, since it was reported 27 days ago and composer 1.6.0 was released 28 days ago ...)

**Comment by cmuench** [comment]
At the moment I think @ktomk is right. We need to set the dependency back to `^1.0` to fulfill the requirements for composer installations.
Then we do a "composer update" to fetch the latest composer version and pin them in the composer.lock. That will provide the new version within the phar file. We checked the current phar against a Magento 2.1.x release. It works. So we can go this way.

**Comment by hostep** [comment]
Ah, I mistakenly thought Magerun 2.x wasn't backwards compatible with Magento 2.1, hence why I didn't see a problem with the `^1.4` constraint, but if Magerun 2.x is actually backwards compatible with Magento 2.1, then we should indeed use `^1.0` for composer based installations with Magento 2.1.

I'll update my PR tonight to use `^1.0` again.

**Comment by hostep** [comment]
Ok, updated PR again with `^1.0` constraint.
