### ISSUE TITLE
`search_query` isn't emptied when using db:dump --strip="@development"

### ISSUE THREAD

**Issue by erfanimani** [netz98/n98-magerun2#354]
`search_query` and `search_synonym` should be dropped when using `@search` flag: https://github.com/netz98/n98-magerun2/blob/develop/config.yaml#L202

**Comment by ktomk** [comment]
Can you try with a development build and provide a PR if it matches your expectations?

**Comment by erfanimani** [comment]
Thanks @ktomk. Created PR.

**Comment by ktomk** [comment]
@cmuench: Can you give this a quick review if it is applicable? Looks good from my end.

**Comment by cmuench** [comment]
@ktomk Yes, this looks good for me.
