### ISSUE TITLE
NULL config value gets saved as string

### ISSUE THREAD

**Issue by juho-jaakkola** [netz98/n98-magerun2#356]
Expectation is that when I run this command, the value gets saved as NULL value in the database:
```
n98-magerun2 config:set /path/to/setting NULL
```
What however happens is, that the value gets saved as the *string* "NULL":
```sql
SELECT * FROM core_config_data
WHERE path = "path/to/setting"
AND value IS NOT NULL;

+-----------+---------+----------+-----------------+-------+
| config_id | scope   | scope_id | path            | value |
+-----------+---------+----------+-----------------+-------+
|       123 | default |        0 | path/to/setting | NULL  |
+-----------+---------+----------+-----------------+-------+
```
This causes problems such as different kind of validation to fail saying "NULL is not a valid value".

**Comment by hostep** [comment]
@juho-jaakkola: you are probably using Magento 2.2.x and Magerun 2.x.x, right?

The thing is, the `config:set` command was introduced in Magento 2.2.x through it's bin/magento cli, which Magerun inherits from. So they had to rename the command from Magerun to not override the one from Magento, the new one is called: `config:store:set`. You can read more about it over here: http://magerun.net/version-2-0-0-released-magento-2-2-compatibility/

Also, maybe good to know, there is a `--no-null` flag available in the `config:store:set` command, which writes 'NULL' as a string, if you don't provide the flag, it will be the `NULL` value in the database, which is what you want.

Hope this helps :)

**Comment by juho-jaakkola** [comment]
Yes, using `config:store:set` indeed seems to fix the problem. Thanks!
