### ISSUE TITLE
Best way to update values in core_config_data

### ISSUE THREAD

**Issue by diazwatson** [netz98/n98-magerun2#358]
Hi guys,

I wonder what would you say is the best way to update values in `core_config_data` table on a Magerun2 module.

For Magento2 we can do something like:

```
public function __construct(
    ....
    \Magento\Framework\App\Config\Storage\WriterInterface $configWriter
    .....
)
{
    $this->configWriter = $configWriter;
}
```

and then
```
$this->configWriter->save('my/path/whatever',  $value, $scope = ScopeConfigInterface::SCOPE_TYPE_DEFAULT, $scopeId = 0)
```
But for a Magerun2 module what would be the best way to do the same?

**Comment by cmuench** [comment]
I guess you have a custom command.
You can inject what ever you need in a command by creating an "inject" method.
Rename your constructor to "inject" should work.

It is also possible to call existing commands. So you could also call the config:store:set command.

```php
$input = new StringInput('cache:flush'); // or use ArrayInput for arguments

// ensure that n98-magerun doesn't stop after first command
$this->getApplication()->setAutoExit(false);

// without output
$this->getApplication()->run($input, new NullOutput());

// with output
$this->getApplication()->run($input, $output);
```

**Comment by diazwatson** [comment]
Great, I will try that.
Thanks Christian 😄 👍
