### ISSUE TITLE
After installing n98-magerun2  cron jobs are not running automatically.

### ISSUE THREAD

**Issue by tousif12** [netz98/n98-magerun2#366]
Version : Magento 2.1.8
After Installation I run it for  mailchimp cronjob that worked perfect . 
But after that now mailchimp supposed to sync all contacts after 1 ,2 hours .When I ran cronjob using n98-magerun2  all contacts sync . But without it cronjob is not working .

**Comment by cmuench** [comment]
Sorry, I do not understand the issue.
Do you run your cronjob with n98-magerun or the native `cron:run` command?

**Comment by ronak2ram** [comment]
@cmuench 
You can try `php n98-magerun2.phar sys:cron:run`
List of crons
`php n98-magerun2.phar sys:cron:list`
Single cron run
`php n98-magerun2.phar sys:cron:run catalog_product_alert`

**Comment by cmuench** [comment]
@ronak2ram @tousif12 Only to clarify.
The native "cron:run" command runs all Magento cronjobs. If you do not have setup an unix cronjob (you can do this by calling cron:install command), no cronjob will automatically executed.
Our tool n98-magerun2 will not replace unix cronjobs. It is only a developer/admin tool to debug cronjobs.
