### ISSUE TITLE
db:dump and anonymized user data

### ISSUE THREAD

**Issue by ThomasNegeli** [netz98/n98-magerun2#368]
Are there any plans to implement a userdata anonymization when dumping the db?
On some installations we need the real customer account in developer environments, with complete account history, but we do not need real user data.

**Comment by cmuench** [comment]
@ThomasNegeli I know a develop who plans to publish a n98-magerun2 module for that purpose.

**Comment by buffcode** [comment]
@cmuench do you have any project name / contact data? We're also in need of "complete" dumps where the real data is anonymized. Fake generated data just doesn't cut all the scenarios of customers travelling the shop.

**Comment by buffcode** [comment]
Related: https://github.com/netz98/n98-magerun2/issues/436

**Comment by cmuench** [comment]
@buffcode anonymization is a complete different approach. I think it also a critical legal problem. I personally do not like such solutions. But that's a different topic.

**Comment by cmuench** [comment]
See also: https://github.com/elgentos/masquerade

**Comment by Aquive** [comment]
What is the status of this? Any plans? I would love to see such a feature too.

**Comment by cmuench** [comment]
There are no plans to include this as core feature.

**Comment by Aquive** [comment]
I am out of office until the 5th of May.

For urgent issues you may contact one of my colleagues, Jeroen de Reus ***@***.***) or Jan Zelig ***@***.***).
