### ISSUE TITLE
Feature request: add object manager to dev:console

### ISSUE THREAD

**Issue by nbennett25** [netz98/n98-magerun2#373]
It would be great to be able to pass an argument to the dev:console command to automatically instantiate an object manager rather than have to call it each time manually:

`$: ~/n98-magerun2.phar dev:console --with-object-manager objm`

would get you to something like:

```
To exit the shell, type ^D.
Psy Shell v0.8.17 (PHP 7.0.29 — cli) by Justin Hileman
New version is available (current: v0.8.17, latest: v0.9.3)
>>> get_class($objm);
>>>"Magento\Framework\ObjectManager\ObjectManager"
```

**Comment by Vinai** [comment]
It already exists as `$di`

**Comment by nbennett25** [comment]
thanks @Vinai! that's exactly what I was looking for - is there any documentation that that var is already set in `dev:console`? I don't see any mention of it in `dev:console --help`.

**Comment by Vinai** [comment]
I didn't see any documentation. Was planning on a PR to auto-declare the ObjectManager as `$om` and saw it already in the source :)

**Comment by amenk** [comment]
We should add documentation for this :) Maybe when starting up the dev:console ? currently one has to discover it via "ls"

**Comment by cmuench** [comment]
@amenk There is also a video available. https://www.youtube.com/watch?v=fILQnZ_v0SE

**Comment by amenk** [comment]
Thanks - so let's play the video, when somebody starts the console the first time *SCNR* :D
