### ISSUE TITLE
Feature request: pass area into dev:console 

### ISSUE THREAD

**Issue by nbennett25** [netz98/n98-magerun2#374]
In order to mitigate the 
`Magento\Framework\Exception\SessionException with message 'Area code not set: Area code must be set before starting a session.'`

error (which I'm seeing when loading a product through the object manager in dev:console, also [Issue #329](https://github.com/netz98/n98-magerun2/issues/329))

in the dev:console, it'd be great to be able to pass the area name in when starting the console:

`$:~/n98-magerun2 dev:console --area-code [admin|frontend|etc]`

**Comment by mludd** [comment]
Does anyone have a workaround for this issue?

**Comment by Vinai** [comment]
As a workaround I set the area manually
```
>>> $di->get(\Magento\Framework\App\State::class)->setAreaCode('frontend')
>>> $product = $di->create(\Magento\Catalog\Api\ProductRepositoryInterface::class)->getById(1)
>>> $product->getData()
```

**Comment by cmuench** [comment]
I am not sure if settings the area code is enough. We need to load events and config for each area.
@Vinai What is your opinion here? Would it be useful to init the complete area?

**Comment by Vinai** [comment]
Yes, I agree the full area should be initialized if it where implemented as an option to the `dev:console` command. The above workaround is just to get rid of the exception - depending on what is the goal that might be enough.
I think all that's missing however is

```
$di->configure($di->get(\Magento\Framework\ObjectManager\ConfigLoaderInterface::class)->load($areaCode))
```
I haven't looked into this very much yet though to be honest.

**Comment by Vinai** [comment]
By the way, I've built the videos on Dependency Injection on Mage2 TV around `n98-magerun2.phar dev:console`, so - thank you!

**Comment by cmuench** [comment]
@Vinai Great. :-)

**Comment by mmenozzi** [comment]
If you need to perform some admin related operation like deleting things you also need to do:

```php
$di->get(\Magento\Framework\Registry::class)->register('isSecureArea', true);
```

**Comment by cmuench** [comment]
@nbennett25 @Vinai The develop build contains the new feature.
You can add e.g. `--area frontend`. Please note that this version will only work with Magento >= 2.3.0.

See: #497
