### ISSUE TITLE
Can't run db:import without having valid db

### ISSUE THREAD

**Issue by lingwooc** [netz98/n98-magerun2#375]
If you run on `db:import` on a magento installation with a missing database then it throws `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento_full.xxx_store_website' doesn't exist, query was: SELECT 'xxx_store_website'.* FROM 'xxx_store_website'`. Which is the same error magento gives. I guess it's not unreasonable as this is a wrapper for `bin\magento`.

This is inconvenient as I'd like to use db:import to setup the database on a blank staging server, but it won't work until the database is setup. I'll add I've not checked if this command relies on `bin/magento` for anything.

**Comment by lingwooc** [comment]
Ugly one liner that does roughly the same thing for those with the same requirement.

`zcat {{dbfile}} | mysql -h $(php -r "\$env=include 'app/etc/env.php'; echo \$env['db']['connection']['default']['host'];") -u $(php -r "\$env=include 'app/etc/env.php'; echo \$env['db']['connection']['default']['username'];") -p$(php -r "\$env=include 'app/etc/env.php'; echo \$env['db']['connection']['default']['password'];") $(php -r "\$env=include 'app/etc/env.php'; echo \$env['db']['connection']['default']['dbname'];")`

Use cat if your file isn't gzipped.

**Comment by ktomk** [comment]
so this is bootstrap related I assume, what you did is like initializing the database, correct? and Magento (and therefore magerun) needs it in an initialized state to import (as it runs magento code which implies the database is set up already). so kind of a hen & egg problem.

I guess it should be possible to offer a low level-command for that (like what you did w/ the one-liner), that is using the configuration data to connect to the database (w/o booting whole Magento) and then import a file. I think this is kind of useful.

**Comment by lingwooc** [comment]
@ktomk yeah that's more or less my assessment. It's useful to use an import as an initialisation when standing up a testing server. I guess its a matter of opinion if it is worth the changes since it breaks the bootstrapping.

**Comment by fredden** [comment]
From what I can tell, [version 2.3.1](https://files.magerun.net/n98-magerun2-2.3.1.phar) works, but [version 2.3.2](https://files.magerun.net/n98-magerun2-2.3.2.phar) exhibits this bug.

From a quick look at the delta between those tags on this repository, this is my guess as to the cause:
https://github.com/netz98/n98-magerun2/compare/2.3.1..2.3.2#diff-733082d0f223a21b50061401f988bf02R390

Note that line is not present in the similar code earlier in the delta:
https://github.com/netz98/n98-magerun2/compare/2.3.1..2.3.2#diff-e42fe36d3628b1f8e91a653d64c7ba6dR341

**Comment by cmuench** [comment]
@fredden We re-structured the whole bootstrapping process.
Can you try again with current beta version v4.0.0?

`n98-magerun2.phar self-update --unstable` 

I tested with this procedure

- dump database
- drop database
- create new empty databas
- do db import

Everyhing was fine for me.

**Comment by fredden** [comment]
I can no longer reproduce this bug with the latest version. Thanks for fixing & following up.

**Comment by riconeitzel** [comment]
hi @cmuench

any plans on a new release including this fix?

Thanks,
Rico

**Comment by cmuench** [comment]
@riconeitzel which fix for which bug? Int the current version it cannot be reproduced.

**Comment by riconeitzel** [comment]
I just tried it on a maxcluster host with 4.4.0 and it still happened

```bash
c-xxxx/app-a ~/domain.de/current $ magerun2 db:import --compression=gz ~/2021-02-08.sql.gz

In Mysql.php line 110:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db-1.core_config_data' doesn't exist, query was: SELECT `main_table`.* FROM `core_config_data` A
  S `main_table`


In Mysql.php line 91:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db-1.core_config_data' doesn't exist


db:import [--connection CONNECTION] [-c|--compression COMPRESSION] [--only-command] [--only-if-empty] [--optimize] [--drop] [--drop-tables] [--force] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--root-dir [ROOT-DIR]] [--skip-config] [--skip-root-check] [--skip-core-commands [SKIP-CORE-COMMANDS]] [--skip-magento-compatibility-check] [--] <command> [<filename>]
```

**Comment by cmuench** [comment]
ok. That's a new info.
To be honest.... I am currently doing less n98-magerun related work.

**Comment by cmuench** [comment]
@riconeitzel  Can you run the command with `-vvv` option. Then it should print the stacktrace. Maybe we can see where the error is triggered.
In this case some code tries to initialize the Shop. We do not really need a initialized Magento for this command.

**Comment by riconeitzel** [comment]
Do you spin up magento for db:import? In that case I'm pretty sure it's instance specific. This shop has some oddly developed extensions that trigger this.

**Comment by cmuench** [comment]
@riconeitzel In general "no". Maybe the tool tries to use a Magento class accidentally which tries to load the Magento Scope Config.
That's what I try to check. I see that error sometimes in the bootstrap process.

**Comment by riconeitzel** [comment]
it seemed to be a broken extensions. didn't trigger the error when I replaced the dependencies with proxies :-)
