### ISSUE TITLE
sys:cron:run - translation is not loaded

### ISSUE THREAD

**Issue by inklammern** [netz98/n98-magerun2#377]

**Comment by mvenghaus** [comment]
i think s.th. like this is missing in 

https://github.com/netz98/n98-magerun2/blob/develop/src/N98/Magento/Command/System/Cron/RunCommand.php

$areaList = $objectManager->get(\Magento\Framework\App\AreaList::class);
$areaList->getArea(Area::AREA_CRONTAB)->load(Area::PART_TRANSLATE);
