### ISSUE TITLE
db:dump strip=@stripped does not strip email_contact

### ISSUE THREAD

**Issue by peterjaap** [netz98/n98-magerun2#380]
The table `email_contact` is introduced along with the dotmailer extension, which comes bundled with Magento 2.2.2. Horrible practices aside, this table should also be stripped when using the @stripped group because it might contain customer-sensitive data (the email address).

**Comment by Stripped** [comment]
i have a mail because github thinking that you say about my mail)
@Stripped

**Comment by cdiacon** [comment]
haha - sorry(izvini :)
