### ISSUE TITLE
customer:change-password cc@gmail.com Abc12345678 base return Area code is not set

### ISSUE THREAD

**Issue by ruby-zhang** [netz98/n98-magerun2#381]
customer:change-password cc@gmail.com Abc12345678 base 

return Area code is not set

**Comment by cmuench** [comment]
@ruby-zhang That's triggered by Magento in an observer.
That event is triggered after the customer was created. So we do not know how we can handle that.
The user should be created successfully. Can you verify that?

**Comment by shochdoerfer** [comment]
I just tested it as I ran into the same issue today. The password does not get set to the one I entered, the old password still seem to be in place as I can still log in with that. I tried with with Magento 2.2.5 CE.

Can't you set the area code in your command somehow globally?

**Comment by ktomk** [comment]
I think we had that once, but it was not doing well. IIRC area code is problematic.

**Comment by peterjaap** [comment]
Dirty hack; make magerun echo (the actual echo function) something early on, this will cause Magento to set an area and the command works.

**Comment by ktomk** [comment]
so setting an area code is triggered via the output (buffer)? If it's the output buffer, that one is actually stackable...

**Comment by codercv** [comment]
I have same issue to.

**Comment by cmuench** [comment]
Same problem as #329

**Comment by simonrl** [comment]
I am still having this issue in a multistore environment (6 websites, 18 store views) with N98 2.3.2, Magento 2.1.14, PHP CLI 7.0.22, on Mac OS High Sierra.

After executing the command, I am prompted to select a website and afterwards get the error "Area code is not set".

Command:
`n98-magerun2 customer:change-password existingcustomer@somedomain.com Password123`

I have verified the customer exists for this website and the password even meets the configured password requirements

Any ideas why I still get this error?

Thanks!
