### ISSUE TITLE
db:dump --add-time broken?

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#388]
Add Time does not seem to add the time stamp anymore?

	www-data@www:/var/www/html/example.de/web$ n98-magerun2 db:dump --add-time

		               
	  Dump MySQL Database  
		               

	Filename for SQL dump: [example.sql]
	Start dumping database example_prod to file example_prod.sql

**Comment by cmuench** [comment]
Bug Confirmed.
