### ISSUE TITLE
--magentoVersion "2.2.5"

### ISSUE THREAD

**Issue by awkwords** [netz98/n98-magerun2#393]
when using n98 to install, looks like for --version "2.2.5" its still pulling 2.2.3

**Comment by cmuench** [comment]
@awkwords The current n98-magerun2 version is "2.2.0".
There is a Magento 2.2.5 version available. If you run "n98-magerun2.phar --version" you see the version of our command line tool.

**Comment by awkwords** [comment]
@cmuench not sure how i butchered that issue, I completely missed the command i was trying to use.

the issue I am having is running this command

n98-magerun2 install --only-download --magentoVersion="2.2.5" --installationFolder="/var/www/htdocs" --skip-config --no-ansi

even when passing magentoVersion="2.2.5" it will still pull 2.2.3..

**Comment by awkwords** [comment]
@cmuench notice the composer output.. still says 2.2.3.

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Installing magento/project-community-edition (2.2.3)
  - Installing magento/project-community-edition (2.2.3): Downloading (100%)

**Comment by cmuench** [comment]
@awkwords I am still not able to reproduce the issue. Tried your command with the latest version and got a 2.2.5 download.
Could it be a composer problem? Which PHP version are you using?
