### ISSUE TITLE
DB dump strip also exclude drop/create table statement

### ISSUE THREAD

**Issue by arnoudhgz** [netz98/n98-magerun2#412]
Currently when you do a `db:dump --strip="@stripped"` e.g. with `@development` tables like `admin_user` are included in the dump as a drop+create empty table. 

In a a lot of cases I would like to have this dump also not include this drop+create.

**Comment by cmuench** [comment]
@arnoudhgz We strip the admin table according to fit the data protection laws. That is also true for admin users.
Feel free to add your own profile by config.

If you need the development dump with admin tables you can run this:

`n98-magerun2.phar db:dump --strip="@trade @stripped @search"`

**Comment by arnoudhgz** [comment]
@cmuench thanks for the fast reply. I know I can use the stripped option, but this will create empty admin tables when I import the dump on the staging environment I don't want to destroy my current staging admin tables.

**Comment by cmuench** [comment]
@arnoudhgz I checked that with a project on my local machine. I cannot confirm this.
The tool should print the names of the tables which are not exported. See "No-data export for:" message.
In my case I cannot see the admin tables there. The final dump file contains the admin_user table.
Instead of running the export it is possible to add " --only-command" to see the triggered mysqldump command.
Can you verify that on your machine?
`n98-magerun2.phar db:dump --strip="@trade @stripped @search" --only-command`
In my case no "admin_user" table is ignored.

**Comment by cmuench** [comment]
@arnoudhgz Can you provide the output of the command?

**Comment by arnoudhgz** [comment]
@cmuench yes: 

`mysqldump --single-transaction --quick --no-data -h'localhost' -u'root' --password='root' 'm226' catalogsearch_fulltext_cl catalogsearch_fulltext_scope1 catalogsearch_fulltext_scope2 catalogsearch_fulltext_scope3 catalogsearch_recommendations customer_address_entity customer_address_entity_datetime customer_address_entity_decimal customer_address_entity_int customer_address_entity_text customer_address_entity_varchar customer_entity customer_entity_datetime customer_entity_decimal customer_entity_int customer_entity_text customer_entity_varchar customer_grid_flat customer_log customer_visitor newsletter_subscriber paypal_billing_agreement paypal_billing_agreement_order paypal_payment_transaction paypal_settlement_report paypal_settlement_report_row product_alert_price product_alert_stock quote quote_address quote_address_item quote_id_mask quote_item quote_item_option quote_payment quote_preview quote_shipping_rate report_compared_product_index report_event report_viewed_product_aggregated_daily report_viewed_product_aggregated_monthly report_viewed_product_aggregated_yearly report_viewed_product_index sales_bestsellers_aggregated_daily sales_bestsellers_aggregated_monthly sales_bestsellers_aggregated_yearly sales_creditmemo sales_creditmemo_comment sales_creditmemo_grid sales_creditmemo_item sales_invoice sales_invoice_comment sales_invoice_grid sales_invoice_item sales_invoiced_aggregated sales_invoiced_aggregated_order sales_order sales_order_address sales_order_aggregated_created sales_order_aggregated_updated sales_order_grid sales_order_item sales_order_payment sales_order_status_history sales_order_tax sales_order_tax_item sales_payment_transaction sales_refunded_aggregated sales_refunded_aggregated_order sales_shipment sales_shipment_comment sales_shipment_grid sales_shipment_item sales_shipment_track sales_shipping_aggregated sales_shipping_aggregated_order vault_payment_token vault_payment_token_order_payment_link wishlist wishlist_item wishlist_item_option | LANG=C LC_CTYPE=C LC_ALL=C sed -e 's/DEFINER[ ]*=[ ]*[^*]*\*/\*/' > 'm226.sql'
mysqldump --single-transaction --quick --ignore-table=m226.catalogsearch_fulltext_cl --ignore-table=m226.catalogsearch_fulltext_scope1 --ignore-table=m226.catalogsearch_fulltext_scope2 --ignore-table=m226.catalogsearch_fulltext_scope3 --ignore-table=m226.catalogsearch_recommendations --ignore-table=m226.customer_address_entity --ignore-table=m226.customer_address_entity_datetime --ignore-table=m226.customer_address_entity_decimal --ignore-table=m226.customer_address_entity_int --ignore-table=m226.customer_address_entity_text --ignore-table=m226.customer_address_entity_varchar --ignore-table=m226.customer_entity --ignore-table=m226.customer_entity_datetime --ignore-table=m226.customer_entity_decimal --ignore-table=m226.customer_entity_int --ignore-table=m226.customer_entity_text --ignore-table=m226.customer_entity_varchar --ignore-table=m226.customer_grid_flat --ignore-table=m226.customer_log --ignore-table=m226.customer_visitor --ignore-table=m226.newsletter_subscriber --ignore-table=m226.paypal_billing_agreement --ignore-table=m226.paypal_billing_agreement_order --ignore-table=m226.paypal_payment_transaction --ignore-table=m226.paypal_settlement_report --ignore-table=m226.paypal_settlement_report_row --ignore-table=m226.product_alert_price --ignore-table=m226.product_alert_stock --ignore-table=m226.quote --ignore-table=m226.quote_address --ignore-table=m226.quote_address_item --ignore-table=m226.quote_id_mask --ignore-table=m226.quote_item --ignore-table=m226.quote_item_option --ignore-table=m226.quote_payment --ignore-table=m226.quote_preview --ignore-table=m226.quote_shipping_rate --ignore-table=m226.report_compared_product_index --ignore-table=m226.report_event --ignore-table=m226.report_viewed_product_aggregated_daily --ignore-table=m226.report_viewed_product_aggregated_monthly --ignore-table=m226.report_viewed_product_aggregated_yearly --ignore-table=m226.report_viewed_product_index --ignore-table=m226.sales_bestsellers_aggregated_daily --ignore-table=m226.sales_bestsellers_aggregated_monthly --ignore-table=m226.sales_bestsellers_aggregated_yearly --ignore-table=m226.sales_creditmemo --ignore-table=m226.sales_creditmemo_comment --ignore-table=m226.sales_creditmemo_grid --ignore-table=m226.sales_creditmemo_item --ignore-table=m226.sales_invoice --ignore-table=m226.sales_invoice_comment --ignore-table=m226.sales_invoice_grid --ignore-table=m226.sales_invoice_item --ignore-table=m226.sales_invoiced_aggregated --ignore-table=m226.sales_invoiced_aggregated_order --ignore-table=m226.sales_order --ignore-table=m226.sales_order_address --ignore-table=m226.sales_order_aggregated_created --ignore-table=m226.sales_order_aggregated_updated --ignore-table=m226.sales_order_grid --ignore-table=m226.sales_order_item --ignore-table=m226.sales_order_payment --ignore-table=m226.sales_order_status_history --ignore-table=m226.sales_order_tax --ignore-table=m226.sales_order_tax_item --ignore-table=m226.sales_payment_transaction --ignore-table=m226.sales_refunded_aggregated --ignore-table=m226.sales_refunded_aggregated_order --ignore-table=m226.sales_shipment --ignore-table=m226.sales_shipment_comment --ignore-table=m226.sales_shipment_grid --ignore-table=m226.sales_shipment_item --ignore-table=m226.sales_shipment_track --ignore-table=m226.sales_shipping_aggregated --ignore-table=m226.sales_shipping_aggregated_order --ignore-table=m226.vault_payment_token --ignore-table=m226.vault_payment_token_order_payment_link --ignore-table=m226.wishlist --ignore-table=m226.wishlist_item --ignore-table=m226.wishlist_item_option -h'localhost' -u'root' --password='root' 'm226' | LANG=C LC_CTYPE=C LC_ALL=C sed -e 's/DEFINER[ ]*=[ ]*[^*]*\*/\*/' >> 'm226.sql'`

**Comment by arnoudhgz** [comment]
@cmuench this is actually not what I need. I do not want the production admin users, but I do **also** not want the drop+create from the admin_user table.

So if I do this statement: `n98-magerun2.phar db:dump --strip="@development"` 

I now still get:

```
DROP TABLE IF EXISTS `admin_user`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `admin_user` (
  `user_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'User ID',
  `firstname` varchar(32) DEFAULT NULL COMMENT 'User First Name',
  `lastname` varchar(32) DEFAULT NULL COMMENT 'User Last Name',
  `email` varchar(128) DEFAULT NULL COMMENT 'User Email',
  `username` varchar(40) DEFAULT NULL COMMENT 'User Login',
  `password` varchar(255) NOT NULL COMMENT 'User Password',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'User Created Time',
  `modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'User Modified Time',
  `logdate` timestamp NULL DEFAULT NULL COMMENT 'User Last Login Time',
  `lognum` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'User Login Number',
  `reload_acl_flag` smallint(6) NOT NULL DEFAULT '0' COMMENT 'Reload ACL',
  `is_active` smallint(6) NOT NULL DEFAULT '1' COMMENT 'User Is Active',
  `extra` text COMMENT 'User Extra Data',
  `rp_token` text COMMENT 'Reset Password Link Token',
  `rp_token_created_at` timestamp NULL DEFAULT NULL COMMENT 'Reset Password Link Token Creation Date',
  `interface_locale` varchar(16) NOT NULL DEFAULT 'en_US' COMMENT 'Backend interface locale',
  `failures_num` smallint(6) DEFAULT '0' COMMENT 'Failure Number',
  `first_failure` timestamp NULL DEFAULT NULL COMMENT 'First Failure',
  `lock_expires` timestamp NULL DEFAULT NULL COMMENT 'Expiration Lock Dates',
  `refresh_token` text COMMENT 'Email connector refresh token',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `ADMIN_USER_USERNAME` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='Admin User Table';
/*!40101 SET character_set_client = @saved_cs_client */;
```
And this is exactly what I do not want, I do not need this drop + create at all.

**Comment by cmuench** [comment]
@arnoudhgz Ok. Now i understand your problem. I tested the command by calling this:
`n98-magerun2.phar db:dump --strip="@development" --exclude="admin_user"`.
Sadly the admin_user is in the structure is in the dump :-(
So, no quick solution for the problem.

**Comment by arnoudhgz** [comment]
@cmuench thanks, that is why it is maybe more a feature request  :P

Could be that I will investigate the options for mysqldump myself and work on this...

**Comment by cmuench** [comment]
@arnoudhgz It is a bug. We describe the "--exclude" option with "Tables to exclude entirely from the dump (including structure)".
