### ISSUE TITLE
Customer:create seems to expect store id but claims to expect website ID in help

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#416]
$ n98-magerun2 sys:web:list

                    
	  Magento Websites  
		            

	+----+--------------+
	| id | code         |
	+----+--------------+
	| 1  | shop_x_uk |
	| 2  | shop_it      |
	| 3  | x_de    |
	| 4  | shop_de      |
	+----+--------------+

	$ n98-magerun2 customer:create dev_user@example.com Dev123456# Dev Customer 2
	Requested store is not found

	$ n98-magerun2 help customer:create
	Usage:
	  customer:create [options] [--] [<email>] [<password>] [<firstname>] [<lastname>] [<website>]

**Comment by amenk** [comment]
Somehow seems to be another problem

**Comment by cmuench** [comment]
Do you use the latest version 3.0.1?
On my dev env your command works.

```
+----+-----------+---------------+------------------------------------------------+---------+---------------------+
| id | firstname | lastname      | email                                          | website | created_at          |
+----+-----------+---------------+------------------------------------------------+---------+---------------------+
| 67 | Dev       | Customer      | dev_user@example.com                           | 2       | 2018-12-12 17:41:45 |
| 68 | Dev       | Customer      | dev_user2@example.com                          | 2       | 2018-12-12 17:42:15 |
+----+-----------+---------------+------------------------------------------------+---------+---------------------+
```

We use the default store of the group to set the store.

```php
$customer->setStoreId($website->getDefaultGroup()->getDefaultStore()->getId());
```

**Comment by amenk** [comment]
I do --- and on some websites it works (same Magento installation), on other's it doesn't .. strange

**Comment by cmuench** [comment]
Could it be that the default store is not set correctly in DB?

**Comment by amenk** [comment]
Looks like I lied - I was on 3.0.0 -- not on 3.0.1
Works now. Nevermind .. :-)
