### ISSUE TITLE
magento 2.3 - missing root dir error

### ISSUE THREAD

**Issue by mvenghaus** [netz98/n98-magerun2#417]
Hey,

when i forget to set the correct root dir .. this happens:

PHP Fatal error:  Uncaught Error: Call to a member function get() on null in phar:///home/xxx/public_html/n98-magerun2.phar/src/N98/Util/Console/Helper/MagentoHelper.php:397

Regards
Marcus

**Comment by cmuench** [comment]
@mvenghaus Can you give me more information about?
Do you call n98-magerun2 in a directory where Magento is already installed?

**Comment by mvenghaus** [comment]
www./n98-magerun2.phar
www/magento/

It worked over a year .. but after updating magento to 2.3 and your tool to the latest version this happens when i forget to set the root-dir.

**Comment by cmuench** [comment]
@mvenghaus I failed to reproduce the problem.
If the structure is like this, the tool is not finding Magento.

```
www/n98-magerun2.phar
www/magento
```
There are three options to fix that.

1. Define the root by setting the `--root-dir` option.
2. Add a "stop file" with the name ".n98-magerun2" in the root. The file must contain the relative path to the magento root. In your case "magento".
3. Add the folder "magento" to the list of scanned sub-directories in a custom config. See https://github.com/netz98/n98-magerun2/blob/develop/config.yaml#L28

If will also try to prevent the thrown fatal error.

**Comment by mvenghaus** [comment]
1. not working
2. works!!!
3. not working

**Comment by cmuench** [comment]
@mvenghaus thanks for checking. I deployed a new phar develop version.
Can you please update with `n98-magerun2.phar self-update --unstable` and test the new version?

**Comment by mvenghaus** [comment]
@cmuench .. thx!

1. works
2. works
3. not working .. but maybe my mistake? I've created a file called "n98-magerun2.yaml" with the following content:

```
detect:
  subFolders:
    - magento
```

**Comment by cmuench** [comment]
@mvenghaus I added a documentation for the config here: https://github.com/netz98/n98-magerun2/wiki/Config

**Comment by mvenghaus** [comment]
/etc/n98-magerun2.yaml
-> works

~/.n98-magerun2.yaml
-> works

app/etc/n98-magerun2.yaml
-> not working .. because he needs the magento root dir to find this .. but i need the config to set the root dir :)

And maybe you can add an info to your doc that the filename in the home dir is differet (dot file). I didn't see that the first time.

**Comment by cmuench** [comment]
@mvenghaus right :-)
I published that in the blog some times ago...
https://magerun.net/released-n98-magerun-version-1-95-0/

I will add the content to the wiki or the README.

**Comment by mvenghaus** [comment]
But the rest works like it should .. BIG THX!

**Comment by cmuench** [comment]
@mvenghaus It's now documented: 

https://github.com/netz98/n98-magerun2/wiki/Magento-Root-Detection
https://github.com/netz98/n98-magerun2/wiki/Config#alternative-project-config
