### ISSUE TITLE
The "--encrypt" option does not exist for config:set

### ISSUE THREAD

**Issue by shawesome** [netz98/n98-magerun2#426]
Hi there,

I have a script which uses magerun to set up some configuration values. We are in the process of upgrading to Magento 2.3 and so updated our version of magerun accordingly.

This is working now for most of the script, however several of our "config:set" commands use the "--encrypt" flag. These no longer seem to work, and fail with an error:
                                                          
```
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--encrypt" option does not exist.                  
```

Although this example makes no sense, I can replicate the issue if I run:

```
$  php n98-magerun2.phar config:set --encrypt "payment/checkmo/title" "Some String"
```

**Comment by cmuench** [comment]
@shawsome please use the "config:store:set" command.
The "config:set" command is bundled with the Magento Core.
