### ISSUE TITLE
Request to update symfony/yaml dependency

### ISSUE THREAD

**Issue by YPyltiai** [netz98/n98-magerun2#430]
Currently n98-magerun2 tool has dependency on not maintained version of `symfony/yaml` (https://github.com/netz98/n98-magerun2/blob/develop/composer.json#L33).

As part of Commerce Cloud, main deployment tool (ECE-Tools) is also using `symfony/yaml` (https://github.com/magento/ece-tools/blob/develop/composer.json#L22) with some features working only for newer versions of package.

The request is to update tool to support newer versions of `symfony/yaml`, so it can work for Commerce Cloud customers without dependency conflict.

**Comment by cmuench** [comment]
@YPyltiai The recommended way is to use the phar file. We have to provide compatibility for all Magento 2 versions. That's at the moment not possible. I can try to change the contraint, but we have to be sure that the tool will also run in Magento 2.1, 2.2 and 2.3.

**Comment by YPyltiai** [comment]
@cmuench , we already run `symfony/yaml: ^3.3` as a default on Cloud, which means it is compatible or your main question is around compatibility of n98-magerun2 itself with newer version of the package?

**Comment by YPyltiai** [comment]
Makes sense, @cmuench . Base on this discussion, we've merged the request to remove `^2.3` support from ECE-Tools, since this compatibility issues was the only one blocking us from doing so.

Closing the issue.
