### ISSUE TITLE
config:store:set multiple values

### ISSUE THREAD

**Issue by grebbekevin** [netz98/n98-magerun2#431]
Hee Guys,

This is not an issue but more like a feature request.
Is it possible to make the config:store:set also accept arrays or something so we can update multiple values in 1 command. Now it is pretty annoying that we have to call the config:store:set multiple times. This also takes some time because the magerun2 command has to be run everytime.

Kind regards,

**Comment by cmuench** [comment]
@grebbekevin Did you try the script functionality?

**Comment by ktomk** [comment]
There is an example in the _read me_: https://github.com/netz98/n98-magerun2#n98-magerun-script
