### ISSUE TITLE
Add webapi:login command

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#435]
I think it would be nice to have a login command makes a 

    curl -XPOST -H 'Content-Type: application/json' $BASEURL/rest/V1/integration/admin/token -d '{ "username": "xxx", "password": "xxx" }' -v

at the webapi.

We could even extend the admin:user:create command to specify standard credential's so an option `--dev-credentails` would use the same password.

We could add options like

`--curl` which prints a curl request stub with the obtained bearer 

What do you think?

**Comment by cmuench** [comment]
Yes, good idea.
I love the idea of having REST client commands.

**Comment by amenk** [comment]
How shall we structure this feature?

**Comment by amenk** [comment]
@cmuench
I saw you implemented it ... admin:token:create .. 

Awesome!

But I think there should be a PHP_EOL after output?

And for customer:token:create a warning message should come when I enter a wrong website interactively .. currently it just asks again for the data.

**Comment by cmuench** [comment]
It's intented. So you can pipe the output to other commands.

**Comment by cmuench** [comment]
@amenk I changed the command to print a line break as default. For scripting the option `--no-newline` was added.
The commands are now published as "admin:token:create" and "customer:token:create".
