### ISSUE TITLE
Shall we include GDPR-dump?

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#436]
Shall we include this package? https://github.com/machbarmacher/gdpr-dump

This might also be a good time to extract some database functions and use https://github.com/iMi-digital/database-helper to unify the database code between n98-magerun + n98-magerun2 and other tools (such as the *famous* imi-conrun)

**Comment by cmuench** [comment]
@amenk :-) next try...
At the moment there is no plan to add more features to n98-magerun 1.
I don't like to split the codebase of n98-magerun2 at the moment. It's easier to maintain for me.

Why do you think is the current tool not GDPR compliant?

Some ppl already think it is.

https://inchoo.net/magento-2/gdpr-compliant-magento-2-database-dump/

**Comment by amenk** [comment]
> I don't like to split the codebase of n98-magerun2 at the moment. It's easier to maintain for me.

But it would allow others to use the great DB features :-)

> Why do you think is the current tool not GDPR compliant?

Basically because of the admin_user Table ... and GDPR Dump would open us ne possibilities to get anonymized production-database dumps for debugging purpose instead of just-stripped dumps.

Also another usecase: Mysqldump is not installed -> a PHP based dump option would allow to work around this

**Comment by cmuench** [comment]
There are already good tools which can be used to create a anonymous dump like this:
https://github.com/mpchadwick/dbanon

I am not sure if we should blow up the source here. What's up with a possibility to hook applicatiobs I to the pipe?

**Comment by amenk** [comment]
What would be included in magerun would be then the field config for what to anonymize. But sure we have to watch for bloat.

**Comment by cmuench** [comment]
I see an extra feature in that which is already provided by existing tools.
