### ISSUE TITLE
Database dump should also strip 2fa tables

### ISSUE THREAD

**Issue by peterjaap** [netz98/n98-magerun2#439]
When using `@development` table group, the admin tables are cleared. Recently Magento introduced the [two factor extension](https://github.com/magento/magespecialist_TwoFactorAuth), which adds (amongst others) the `msp_tfa_user_config` and `msp_tfa_trusted` tables. These store the 2FA configuration for the admin users. 

But when the admin_user table is stripped when the database is dumped, these configurations stay intact but are invalid, thus making it impossible to log in. So these tables should be stripped as well.

**Comment by cmuench** [comment]
@peterjaap A new development phar will be available in some minutes.
