### ISSUE TITLE
phive.xml is outdated

### ISSUE THREAD

**Issue by ThomasNegeli** [netz98/n98-magerun2#445]
https://files.magerun.net/phive.xml does not contain the latest releases.

**Comment by ThomasNegeli** [comment]
3.0.4+ are missing

**Comment by cmuench** [comment]
Thanks for reporting.
I will check that.

**Comment by cmuench** [comment]
@ThomasNegeli the phive.xml is now up-to-date.

**Comment by ThomasNegeli** [comment]
@cmuench thanks for the quick response.
And concrates to your certification.

@mzeis time to include phive in our VM. Our Docker Images are already up to date.

**Comment by cmuench** [comment]
Thanks :-)

Am Fr., 29. März 2019 um 09:06 Uhr schrieb Thomas Negeli <
notifications@github.com>:
