### ISSUE TITLE
Memory usage within Magerun script

### ISSUE THREAD

**Issue by matthew-muscat** [netz98/n98-magerun2#447]
When using the `magerun2 script` command to set a number of configuration values, the memory consumed by Magerun appears to increase for each command within the script, to the point where magerun can exceed the available memory allowed.

Additionally, each line of the script appears to take some time to execute, for what would otherwise be a simple operation.

For example, calling a script which contains multiple "config:store:set" entries will trigger this issue, with the memory limit being dependant on your environment.
`config:store:set --scope-id=0 --scope=default -- 'web/secure/base_url' 'example.com'`

I've seen this blow through 1GB memory limits on the PHP application when running 30+ commands of `config:store:set`

I suspect that a heavy operation i running for each command invocation — ie: the Magento application is being re-initialised on each script call.

**Comment by ktomk** [comment]
Please share the Magerun and the Magento version.

**Comment by peschmae** [comment]
I ran into the same issue, just using `config:store:set` commands, and blew through 5GB of memory when running 64 commands in one script.

Magento 2.3.2 (Also testet on 2.2.6)
Magerun 3.1.0

**Comment by peschmae** [comment]
I've now split my script into multiple files, and even though most of the time it's fine sometimes it still exceeds 2G of memory with just 16 config:store:set commands

**Comment by cmuench** [comment]
Did some tests. Seems that the execution of Symfony Console Command inside a Command increases the amount of memory.

**Comment by amenk** [comment]
Same problem here, with magerun 7.0.0

```
 echo 'config:store:set web/unsecure/base_url '\''https://shop245.example.com/'\''
config:store:set web/secure/base_url '\''https://shop245.example.com/'\''
config:store:delete web/secure/base_static_url --scope stores --scope-id 0
config:store:delete web/unsecure/base_url --scope stores --scope-id 0
config:store:delete web/secure/base_url  --scope stores --scope-id 0
config:store:delete web/cookie/cookie_path --scope stores --scope-id 0
config:store:delete web/cookie/cookie_domain --scope stores --scope-id 0
config:store:delete web/unsecure/base_url --scope stores --scope-id 4
config:store:delete web/secure/base_url  --scope stores --scope-id 4
config:store:delete web/cookie/cookie_path --scope stores --scope-id 4
config:store:delete web/cookie/cookie_domain --scope stores --scope-id 4
config:store:delete web/unsecure/base_url --scope stores --scope-id 6
config:store:delete web/secure/base_url  --scope stores --scope-id 6
config:store:delete web/cookie/cookie_path --scope stores --scope-id 6
config:store:delete web/cookie/cookie_domain --scope stores --scope-id 6
config:store:delete web/unsecure/base_url --scope stores --scope-id 7
config:store:delete web/secure/base_url  --scope stores --scope-id 7
config:store:delete web/cookie/cookie_path --scope stores --scope-id 7
config:store:delete web/cookie/cookie_domain --scope stores --scope-id 7
config:store:delete web/unsecure/base_url --scope stores --scope-id 8
config:store:delete web/secure/base_url  --scope stores --scope-id 8
config:store:delete web/cookie/cookie_path --scope stores --scope-id 8
config:store:delete web/cookie/cookie_domain --scope stores --scope-id 8
config:store:delete web/unsecure/base_url --scope stores --scope-id 9
config:store:delete web/secure/base_url  --scope stores --scope-id 9
config:store:delete web/cookie/cookie_path --scope stores --scope-id 9
config:store:delete web/cookie/cookie_domain --scope stores --scope-id 9
config:store:delete web/unsecure/base_url --scope stores --scope-id 10
config:store:delete web/secure/base_url  --scope stores --scope-id 10
config:store:delete web/cookie/cookie_path --scope stores --scope-id 10
config:store:delete web/cookie/cookie_domain --scope stores --scope-id 10
config:store:delete web/unsecure/base_url --scope stores --scope-id 11
config:store:delete web/secure/base_url  --scope stores --scope-id 11
config:store:delete web/cookie/cookie_path --scope stores --scope-id 11
config:store:delete web/cookie/cookie_domain --scope stores --scope-id 11
config:store:delete web/unsecure/base_url --scope stores --scope-id 12
config:store:delete web/secure/base_url  --scope stores --scope-id 12
config:store:delete web/cookie/cookie_path --scope stores --scope-id 12
config:store:delete web/cookie/cookie_domain --scope stores --scope-id 12
config:store:delete web/unsecure/base_url --scope stores --scope-id 13
config:store:delete web/secure/base_url  --scope stores --scope-id 13
config:store:delete web/cookie/cookie_path --scope stores --scope-id 13
config:store:delete web/cookie/cookie_domain --scope stores --scope-id 13
config:store:delete web/unsecure/base_url --scope stores --scope-id 14
config:store:delete web/secure/base_url  --scope stores --scope-id 14
config:store:delete web/cookie/cookie_path --scope stores --scope-id 14
config:store:delete web/cookie/cookie_domain --scope stores --scope-id 14
config:store:delete web/unsecure/base_url --scope stores --scope-id 15
config:store:delete web/secure/base_url  --scope stores --scope-id 15
config:store:delete web/cookie/cookie_path --scope stores --scope-id 15
config:store:delete web/cookie/cookie_domain --scope stores --scope-id 15
config:store:delete web/unsecure/base_url --scope stores --scope-id 16
config:store:delete web/secure/base_url  --scope stores --scope-id 16
config:store:delete web/cookie/cookie_path --scope stores --scope-id 16
config:store:delete web/cookie/cookie_domain --scope stores --scope-id 16
config:store:delete web/unsecure/base_url --scope stores --scope-id 17
config:store:delete web/secure/base_url  --scope stores --scope-id 17
config:store:delete web/cookie/cookie_path --scope stores --scope-id 17
config:store:delete web/cookie/cookie_domain --scope stores --scope-id 17
config:store:delete admin/url/custom
config:store:delete admin/url/use_custom
config:store:delete web/cookie/cookie_domain
config:store:delete web/cookie/cookie_domain --scope=websites
config:store:delete web/cookie/cookie_path
config:store:set web/unsecure/base_static_url NULL
config:store:set web/secure/base_static_url NULL
config:store:set web/url/use_store 1
' | /usr/local/bin/n98-magerun2 script
```

exhausts 4GB memory limit, increasing to 10G works...

**Comment by amenk** [comment]
![image](https://user-images.githubusercontent.com/1087128/224958827-546fe3d3-b5aa-4235-affc-1994003bf797.png)
Memory is consumed by compile::metadata/global.php - that seams to be `generated/metadata/global.php`

I am in production mode.

**Comment by amenk** [comment]
I think it would be better to not re-initialize Magento at all at each script line. We can see that for example Magento\Framework\App\Bootstrap::create is called many times.

But not recreating the app might cause side effects, so maybe a `--no-reinitialize` option could be added to the script?

**Comment by cmuench** [comment]
@amenk we have a check that Magento should not be initialized again. Sadly some other stuff seems to load several times. We have to find the source of the redundant "global.php" loading.

**Comment by amenk** [comment]
it's easier to reproduce with mem limit of 256M :)
But it still stops after a bunch of config:delete calls with memory exhaustion 

This is what I tried so far: https://github.com/netz98/n98-magerun2/compare/develop...iMi-digital:n98-magerun2:447-memleak?expand=1 - no luck

**Comment by amenk** [comment]
@cmuench I downgraded to 6.1.1 and cannot reproduce it there, so this seems somehow also to be a regression in 7.0.0

**Comment by cmuench** [comment]
@amenk I did some tests with a Magerun script file. In my tests the memory leak seems to be in the `config:store:delete` command.
We load there a DB collection. This is a core Magerun command. So the new Proxy Command behavior is not an issue.

**Comment by amenk** [comment]
@cmuench it might still influence it because with 6.1.1 we don't run into the memory leak

**Comment by cmuench** [comment]
@amenk I just found a part of the code where Magento get initialized multiple time. Let's see if I can fix it.

**Comment by cmuench** [comment]
@amenk I just started a test script. Patched version runs 10x faster.

**Comment by cmuench** [comment]
@amenk The main problem is not the initialization of n98-magerun2. It's the Magento init process which then is triggered for every command in the script.
Can you test the phar in the PR with your script?
 
https://github.com/netz98/n98-magerun2/pull/1156#issuecomment-1477915325

**Comment by cmuench** [comment]
I did a benchmark with a script of 616 commands.

Without the patch:

```
real	0m11.128s
user	0m10.115s
sys	0m0.816s
```

with patch:

```
real	0m1.074s
user	0m0.887s
sys	0m0.138s
```

Memory usage is 139 MB vs. 4362 MB.

**Comment by amenk** [comment]
Sounds very good, thanks, will try to test soon, but I am sure this will work:-)

**Comment by cmuench** [comment]
@amenk I just merged it in develop branch. Hope that fixes your issue.

**Comment by cmuench** [comment]
@amenk If that works then I plan to release it tomorrow as 7.0.1.
