### ISSUE TITLE
With Magento 2.3.1, command sys:setup:compare-versions returns errors on a lot of core modules

### ISSUE THREAD

**Issue by emastyle** [netz98/n98-magerun2#450]
`n98-magerun2.phar sys:setup:compare-versions` return errors on a lot of core modules with magento 2.3.1:

Env:
- centos7 on vagrant (host Mac)
- php PHP 7.1.22
........

| Magento_AdminNotification                            |         |         |         | Error  |
| Magento_AdvancedPricingImportExport                  |         |         |         | Error  |
| Magento_AdvancedSearch                               |         |         |         | Error  |
| Magento_Amqp                                         |         |         |         | Error  |
| Magento_Analytics                                    |         |         |         | Error  |
| Magento_AsynchronousOperations                       |         |         |         | Error  |
| Magento_Authorization                                |         |         |         | Error  |
| Magento_Authorizenet                                 |         |         |         | Error  |
| Magento_Backend                                      |         |         |         | Error  |
| Magento_Backup                                       |         |         |         | Error  |
| Magento_Braintree                                    |         |         |         | Error  |
| Magento_Bundle                                       |         |         |         | Error  |
| Magento_BundleGraphQl                                |         |         |         | Error  |
| Magento_BundleImportExport                           |         |         |         | Error  |
| Magento_CacheInvalidate                              |         |         |         | Error  |
| Magento_Captcha                                      |         |         |         | Error  |
| Magento_Catalog                                      |         |         |         | Error  |
| Magento_CatalogAnalytics                             |         |         |         | Error  |
| Magento_CatalogGraphQl                               |         |         |         | Error  |
| Magento_CatalogImportExport                          |         |         |         | Error  |
| Magento_CatalogInventory                             |         |         |         | Error  |
| Magento_CatalogInventoryGraphQl                      |         |         |         | Error  |
| Magento_CatalogRule                                  |         |         |         | Error  |
| Magento_CatalogRuleConfigurable                      |         |         |         | Error  |
| Magento_CatalogSearch                                |         |         |         | Error  |
| Magento_CatalogUrlRewrite                            |         |         |         | Error  |
| Magento_CatalogUrlRewriteGraphQl                     |         |         |         | Error  |
| Magento_CatalogWidget                                |         |         |         | Error  |
| Magento_Checkout                                     |         |         |         | Error  |
| Magento_CheckoutAgreements                           |         |         |         | Error  |
| Magento_Cms                                          |         |         |         | Error  |
| Magento_CmsGraphQl                                   |         |         |         | Error  |
| Magento_CmsUrlRewrite                                |         |         |         | Error  |
| Magento_CmsUrlRewriteGraphQl                         |         |         |         | Error  |
| Magento_Config                                       |         |         |         | Error  |
| Magento_ConfigurableImportExport                     |         |         |         | Error  |
| Magento_ConfigurableProduct                          |         |         |         | Error  |
| Magento_ConfigurableProductGraphQl                   |         |         |         | Error  |
| Magento_ConfigurableProductSales                     |         |         |         | Error  |
| Magento_Contact                                      |         |         |         | Error  |
| Magento_Cookie                                       |         |         |         | Error  |
| Magento_Cron                                         |         |         |         | Error  |
| Magento_CurrencySymbol                               |         |         |         | Error  |
| Magento_Customer                                     |         |         |         | Error  |
| Magento_CustomerAnalytics                            |         |         |         | Error  |
| Magento_CustomerGraphQl                              |         |         |         | Error  |
| Magento_CustomerImportExport                         |         |         |         | Error  |
| Magento_Deploy                                       |         |         |         | Error  |
| Magento_Developer                                    |         |         |         | Error  |
| Magento_Dhl                                          |         |         |         | Error  |
| Magento_Directory                                    |         |         |         | Error  |
| Magento_DirectoryGraphQl                             |         |         |         | Error  |
| Magento_Downloadable                                 |         |         |         | Error  |
| Magento_DownloadableGraphQl                          |         |         |         | Error  |
| Magento_DownloadableImportExport                     |         |         |         | Error  |
| Magento_Eav                                          |         |         |         | Error  |
| Magento_EavGraphQl                                   |         |         |         | Error  |
| Magento_Elasticsearch                                |         |         |         | Error  |
| Magento_Elasticsearch6                               |         |         |         | Error  |
| Magento_Email                                        |         |         |         | Error  |
| Magento_EncryptionKey                                |         |         |         | Error  |
| Magento_Fedex                                        |         |         |         | Error  |
| Magento_GiftMessage                                  |         |         |         | Error  |
| Magento_GoogleAdwords                                |         |         |         | Error  |
| Magento_GoogleAnalytics                              |         |         |         | Error  |
| Magento_GoogleOptimizer                              |         |         |         | Error  |
| Magento_GraphQl                                      |         |         |         | Error  |
| Magento_GroupedCatalogInventory                      |         |         |         | Error  |
| Magento_GroupedImportExport                          |         |         |         | Error  |
| Magento_GroupedProduct                               |         |         |         | Error  |
| Magento_GroupedProductGraphQl                        |         |         |         | Error  |
| Magento_ImportExport                                 |         |         |         | Error  |
| Magento_Indexer                                      |         |         |         | Error  |
| Magento_InstantPurchase                              |         |         |         | Error  |
| Magento_Integration                                  |         |         |         | Error  |
| Magento_InventoryDistanceBasedSourceSelection        |         |         |         | Error  |
| Magento_InventoryDistanceBasedSourceSelectionAdminUi |         |         |         | Error  |
| Magento_InventoryDistanceBasedSourceSelectionApi     |         |         |         | Error  |
| Magento_InventorySalesFrontendUi                     |         |         |         | Error  |
| Magento_InventorySetupFixtureGenerator               |         |         |         | Error  |
| Magento_LayeredNavigation                            |         |         |         | Error  |
| Magento_Marketplace                                  |         |         |         | Error  |
| Magento_MediaStorage                                 |         |         |         | Error  |
| Magento_MessageQueue                                 |         |         |         | Error  |
| Magento_Msrp                                         |         |         |         | Error  |
| Magento_MsrpConfigurableProduct                      |         |         |         | Error  |
| Magento_MsrpGroupedProduct                           |         |         |         | Error  |
| Magento_Multishipping                                |         |         |         | Error  |
| Magento_MysqlMq                                      |         |         |         | Error  |
| Magento_NewRelicReporting                            |         |         |         | Error  |
| Magento_Newsletter                                   |         |         |         | Error  |
| Magento_OfflinePayments                              |         |         |         | Error  |
| Magento_OfflineShipping                              |         |         |         | Error  |
| Magento_PageCache                                    |         |         |         | Error  |
| Magento_Payment                                      |         |         |         | Error  |
| Magento_Paypal                                       |         |         |         | Error  |
| Magento_Persistent                                   |         |         |         | Error  |
| Magento_ProductAlert                                 |         |         |         | Error  |
| Magento_ProductVideo                                 |         |         |         | Error  |
| Magento_Quote                                        |         |         |         | Error  |
| Magento_QuoteAnalytics                               |         |         |         | Error  |
| Magento_QuoteGraphQl                                 |         |         |         | Error  |
| Magento_ReleaseNotification                          |         |         |         | Error  |
| Magento_Reports                                      |         |         |         | Error  |
| Magento_RequireJs                                    |         |         |         | Error  |
| Magento_Review                                       |         |         |         | Error  |
| Magento_ReviewAnalytics                              |         |         |         | Error  |
| Magento_Robots                                       |         |         |         | Error  |
| Magento_Rss                                          |         |         |         | Error  |
| Magento_Rule                                         |         |         |         | Error  |
| Magento_Sales                                        |         |         |         | Error  |
| Magento_SalesAnalytics                               |         |         |         | Error  |
| Magento_SalesGraphQl                                 |         |         |         | Error  |
| Magento_SalesInventory                               |         |         |         | Error  |
| Magento_SalesRule                                    |         |         |         | Error  |
| Magento_SalesSequence                                |         |         |         | Error  |
| Magento_SampleData                                   |         |         |         | Error  |
| Magento_Search                                       |         |         |         | Error  |
| Magento_Security                                     |         |         |         | Error  |
| Magento_SendFriend                                   |         |         |         | Error  |
| Magento_SendFriendGraphQl                            |         |         |         | Error  |
| Magento_Shipping                                     |         |         |         | Error  |
| Magento_Signifyd                                     |         |         |         | Error  |
| Magento_Sitemap                                      |         |         |         | Error  |
| Magento_Store                                        |         |         |         | Error  |
| Magento_StoreGraphQl                                 |         |         |         | Error  |
| Magento_Swagger                                      |         |         |         | Error  |
| Magento_SwaggerWebapi                                |         |         |         | Error  |
| Magento_SwaggerWebapiAsync                           |         |         |         | Error  |
| Magento_Swatches                                     |         |         |         | Error  |
| Magento_SwatchesGraphQl                              |         |         |         | Error  |
| Magento_SwatchesLayeredNavigation                    |         |         |         | Error  |
| Magento_Tax                                          |         |         |         | Error  |
| Magento_TaxGraphQl                                   |         |         |         | Error  |
| Magento_TaxImportExport                              |         |         |         | Error  |
| Magento_Theme                                        |         |         |         | Error  |
| Magento_ThemeGraphQl                                 |         |         |         | Error  |
| Magento_Tinymce3                                     |         |         |         | Error  |
| Magento_Translation                                  |         |         |         | Error  |
| Magento_Ui                                           |         |         |         | Error  |
| Magento_Ups                                          |         |         |         | Error  |
| Magento_UrlRewrite                                   |         |         |         | Error  |
| Magento_UrlRewriteGraphQl                            |         |         |         | Error  |
| Magento_User                                         |         |         |         | Error  |
| Magento_Usps                                         |         |         |         | Error  |
| Magento_Variable                                     |         |         |         | Error  |
| Magento_Vault                                        |         |         |         | Error  |
| Magento_Version                                      |         |         |         | Error  |
| Magento_Webapi                                       |         |         |         | Error  |
| Magento_WebapiAsync                                  |         |         |         | Error  |
| Magento_WebapiSecurity                               |         |         |         | Error  |
| Magento_Weee                                         |         |         |         | Error  |
| Magento_WeeeGraphQl                                  |         |         |         | Error  |
| Magento_Widget                                       |         |         |         | Error  |
| Magento_Wishlist                                     |         |         |         | Error  |
| Magento_WishlistAnalytics                            |         |         |         | Error  |
| Magento_WishlistGraphQl                              |         |         |         | Error  |
+------------------------------------------------------+---------+---------+---------+--------+

  157 setup errors were found!

**Comment by ktomk** [comment]
@emastyle Please try w/ `-vvv` and check if in the output some more information is available about which error occurred.

**Comment by cmuench** [comment]
I was able to reproduce that error.

**Comment by cmuench** [comment]
@emastyle A new v3.0.8 is deployed. Please update. Error should be fixed.

**Comment by emastyle** [comment]
> @emastyle A new v3.0.8 is deployed. Please update. Error should be fixed.

Just update and seems to works fine! Thank a lot!
