### ISSUE TITLE
[Exception]  Warning: file_exists(): Unable to find the wrapper "phar" - did you forget to enable it when you configured PHP? in phar:///l/magento2/n98-magerun2.phar/vendor/composer/ClassLoader.php on line 384

### ISSUE THREAD

**Issue by mozgbrasil** [netz98/n98-magerun2#452]
Hello good afternoon

I am trying to create a module but the error is being displayed as images

Can you help me please

![Captura de tela de 2019-04-10 16-11-56](https://user-images.githubusercontent.com/17202780/55907092-3698d900-5bac-11e9-86e0-f90e5283c46b.png)
![Captura de tela de 2019-04-10 16-17-04](https://user-images.githubusercontent.com/17202780/55907093-3698d900-5bac-11e9-854a-a562f89861f9.png)

**Comment by ktomk** [comment]
Thanks for the report. Are you using the latest Magerun2 version? I ask because there were some changes recently which deal with the unregistered phar wrapper (#440 , ad58ccabdf173ea7d1ee7de964c6e1063d986537).

**Comment by mozgbrasil** [comment]
Hello

The version I'm using follows

$ php --version
    PHP 7.2.15-0ubuntu0.18.04.2 (cli) (built: Mar 22 2019 17:05:14) ( NTS )
    Copyright (c) 1997-2018 The PHP Group
    Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
        with Zend OPcache v7.2.15-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies
    
$ ./magento/bin/magento --version
    Magento CLI 2.3.1

$ ./n98-magerun2.phar --version
    n98-magerun2 version 3.0.4 by netz98 GmbH

![Captura de tela de 2019-04-10 19-08-46](https://user-images.githubusercontent.com/17202780/55916958-3ad0f080-5bc4-11e9-87d7-2088287b50a6.png)

**Comment by cmuench** [comment]
@mozgbrasil please upgrade to latest version.
This problem is already fixed.

**Comment by cmuench** [comment]
Solved in #440
