### ISSUE TITLE
There are no commands defined in the "local-config" namespace.

### ISSUE THREAD

**Issue by mozgbrasil** [netz98/n98-magerun2#454]
Hello good Morning

When executing the following command the error is being returned

   [Symfony \ Component \ Console \ Exception \ CommandNotFoundException]
   There are no commands defined in the "local-config" namespace.

![Captura de tela de 2019-04-13 23-35-29](https://user-images.githubusercontent.com/17202780/56087649-b392af80-5e45-11e9-90f6-fea396a2b5c9.png)
![Captura de tela de 2019-04-13 23-35-40](https://user-images.githubusercontent.com/17202780/56087650-b42b4600-5e45-11e9-8f34-bd70ed5c5da9.png)

**Comment by cmuench** [comment]
@mozgbrasil this command is currently only available in n98-magerun1.

**Comment by cmuench** [comment]
@mozgbrasil
Maybe you can work with the `bin/magento setup:config:set` command.

**Comment by mozgbrasil** [comment]
Hello good afternoon

For the purpose of creating env.php, I came up with the option "bin / magento setup: config: set" but in this way the "install-> date" attribute is not created.

I am using the following example

https://github.com/marcinbojanowski/docker-magento-web/blob/1949c75d7b238e71ef32e2b22202a2f491635f90/rootfs/etc/cont-init.d/20-magento

Thank you my friend

**Comment by cmuench** [comment]
@mozgbrasil Last week we were working on a Kubernetes setup. We had the same problem, too. Maybe it would be good to create a new command "config:env:generate".
