### ISSUE TITLE
command n98-magerun2 install does not ask admin parameters

### ISSUE THREAD

**Issue by LouNik1984** [netz98/n98-magerun2#464]
Hi
I launched this command to install latest magento version (2.3.1) : 

n98-magerun2 install

it starts fine, lets me choose the magento I want (the first, 2.3.1), check composer, download magento files, asks the database parameters and successfully create the database if it doesn't exist; but then, the only thing that asks again is the base url, the rest of the parameters are never asked and I end up with the default ones: 

![Cattura](https://user-images.githubusercontent.com/6501073/58718193-4de68c80-83cd-11e9-88d1-b4730450b557.JPG)

Is this intended behaviour? Is there a way to change this? At least for some important parameters like the admin and use-secure-admin (which can prevent the user from accessing the backend without further configuration)

I think like these parameters should be asked during install procedure and all the tutorials I found online show the cli asking for them.

**Comment by cmuench** [comment]
@LouNik1984 We do not ask for every parameter. If you need a quick solution, you can set your own pre-settings with an own config file.
The dist config can be found here: https://github.com/netz98/n98-magerun2/blob/develop/config.yaml#L555

**Comment by LouNik1984** [comment]
Thank you but I don't need to change the default settings, I need those parameters to be asked during the install procedure. Is there a way to set this?

**Comment by cmuench** [comment]
@LouNik1984 The config contains more values as the installed asks for.
This command was designed to provide a simple way to install Magento for newbies.
Magento 2 has a lot of optional parameters. So the short answer is "no". It is not possible at the moment.
