### ISSUE TITLE
Are there any plans to create a DIST release to install via composer dependency

### ISSUE THREAD

**Issue by ThomasNegeli** [netz98/n98-magerun2#466]
In the past, we were installing magerun2 via composer dependency.
This brings us the benefit that we can adjust the required magerun version on a project level.
With Magento 2.3 Release and magerun version > 3 (I think it was 3), we ended up in an endless loop resolving composer dependencies. So we are lost in dependency hell.
So we thought about pinning down the magerun version in our develop VMs or docker images, by installing the tool as a phar release globally.
This has the drawback that, in some cases, the latest version is not always suitable for our projects. This sometimes differs from project to project.

I know the concept of DIST releases from deployer.
From a user perspective, you just require the dist release of n98-magerun2 in your composer.json. The dist release does not have any other dependency. It is just the PHAR release under different clothes installed locally in your project.
https://packagist.org/packages/deployer/dist

Any thoughts on that?

**Comment by cmuench** [comment]
@ThomasNegeli Interesting concept.
Maybe that's solution for some problems.
We currently deploy with every release a "phive" version.
See https://magerun.net/phive-support-for-n98-magerun/

The composer dist package could be created with the same workflow.

**Comment by ThomasNegeli** [comment]
@cmuench yes, we are testing phive to install magerun. We already talked about that at #445.
The problem with PHIVE is, that you can't skip the keyserver check. So installing magerun during deployment with PHIVE might not work correctly.
They are improving the keyserver check at PHIVE, because now they are checking more than just 1 server (https://github.com/phar-io/phive/releases/tag/0.12.2), but keyservers in generall are not very stable. 
Having a dist release of n98-magerun2 would be very welcome.

**Comment by cmuench** [comment]
@ThomasNegeli Maybe my last sentence was misleading. I mean that we should be able to deploy a dist package in the same workflow we are creating the phive release. If I understand the procedure correct, we have to commit the phar file a seperate git repository? Or is it possible to re-use already existing phar files via a url reference?

**Comment by ThomasNegeli** [comment]
@cmuench never checked how to build it.
I'm just using it :-D
But it seems to be the PHAR file of the release which installs under vendor/bin/dep

**Comment by cmuench** [comment]
@ThomasNegeli For me it looks like the phar is commited. See e.g. https://github.com/deployphp/distribution/blob/v6.4.2/dep
I try to prevent committing binaries in the git repo. There is a 1GB limit on Github.

**Comment by ThomasNegeli** [comment]
@cmuench I think it will take some time to get to the point where n98-magerun2 has 1 GB.
But there is a huge benefit from an integrator perspective if there is DIST release.

**Comment by cmuench** [comment]
Yes, ca. 85 releases. It would be better if we can re-use existing phar files of the current archive.
https://files.magerun.net/old_versions.php

**Comment by cmuench** [comment]
@ThomasNegeli We will try to provide a dist repository but we have to think about the limitations.

**Comment by cmuench** [comment]
Another example for a dist repo can be found here: https://github.com/phpstan/phpstan-shim

**Comment by cmuench** [comment]
@ThomasNegeli I manually created a experimental package with the latest 3.0.10 as tag available.

https://packagist.org/packages/n98/magerun2-dist

```
composer require n98/magerun2-dist 
```

**Comment by cmuench** [comment]
Deployed... https://magerun.net/released-n98-magerun2-v3-1-0-with-brand-new-webapi-commands/
