### ISSUE TITLE
There are no commands defined in the "indexer" namespace. CE 2.3.1

### ISSUE THREAD

**Issue by diazwatson** [netz98/n98-magerun2#469]
Hi guys, while installing ce-2.3.1 today I got this:
```
...
[Progress: 833 / 833]
[SUCCESS]: Magento installation complete.
[SUCCESS]: Magento Admin URI: /admin
Nothing to import.
Install sample data? [y]: n
Reindex all after installation


  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "indexer" namespace.

  Did you mean one of these?
      index
      index:trigger


Successfully installed magento
```
When it finished I cleared `generated` folder and everything worked as expected.

Maybe we should clear the content of this folder after installation but before reindex?

I will do my best to create a PR with this asap if no-one else has done it before.

**Comment by cmuench** [comment]
I close this ticket. If needed, please re-open it.
