### ISSUE TITLE
Update travis versions

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#475]
Travis should check the newest Magento version of each minor release.
- 2.3.2
- 2.2.8
- 2.1.16

**Comment by hostep** [comment]
@cmuench: just FYI, at the moment of writing, these are the latest versions of Magento2:
- 2.3.2 (correct!)
- 2.2.9
- 2.1.18

All released 5 days ago, ref: https://magento.com/tech-resources/download#download2302

No big deal though, I just noticed you missed some versions 😉
