### ISSUE TITLE
Generate empty db_schema.xml when running dev:module:create

### ISSUE THREAD

**Issue by ooa113y** [netz98/n98-magerun2#484]
Other kinds of empty config files are generated with the correct xsi schema locations. This one isn't getting created though.

**Comment by cmuench** [comment]
@ooa113y Can you clearify what you expect?
Should an empty db_schema.xml file be created?

**Comment by ooa113y** [comment]
My wish is to have a skeleton file akin to other similar ones already created by this command to appear as part of the new module. Specifically, the contents would be, more or less, something like this:
```xml
<?xml version="1.0"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Setup/Declaration/Schema/etc/schema.xsd">
    
</schema>
```

**Comment by cmuench** [comment]
@ooa113y The dev:module:create command will someday be replaced since the "app/code" directory is deprecated.
I would prefer to create a new dev:console "make:config:db-schema" command.
