### ISSUE TITLE
Can't create customer

### ISSUE THREAD

**Issue by neilborromeo** [netz98/n98-magerun2#486]
Magento version: 2.3.1

Magerun version: 3.2.0

I'm trying to create a customer by issuing the command:
`php bin/n98-magerun2 customer:create ouremail@email.com complexpassword John Doe sample.com`

CLI output:
Zend\Mail\Message::addTo expects a string, AddressInterface, array, AddressList, or Traversable as its first argument; received "NULL"

**Comment by cmuench** [comment]
@neilborromeo I tested the command in a local instance and was able to crate a user. The password btw. does not match the requirements.

**Comment by neilborromeo** [comment]
The password of course is just a sample. I did try to enclose the password with a single and double quote but still get the same issue. The email preferences is working just fine. I'll try this again with a fresh magento instance.

**Comment by cmuench** [comment]
@neilborromeo Thanks. That would help to exclude external dependencies as source of the problem.
We have also a running integration test for 2.3.2, 2.2.8, 2.1.16.
e.g. https://travis-ci.org/netz98/n98-magerun2/jobs/561126296#L3408

**Comment by cmuench** [comment]
@neilborromeo If you add the "-vvv" Option, the you should see the complete PHP stack trace for the exception.
`php bin/n98-magerun2 -vvv`

**Comment by cmuench** [comment]
I close this ticket. If needed, please re-open it.
