### ISSUE TITLE
mcrypt is optional module in Magento 2.3

### ISSUE THREAD

**Issue by olivierchabert** [netz98/n98-magerun2#488]
Hello,

mcrypt extension seems to be an optional extension see: https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

More mcrypt is no longer in php 7.2 (but it can be install via PECL).

Is it possible to remove mcrypt from the list of required extensions?

Thanks

**Comment by martin-cod** [comment]
+1

sys:check command fails system check:

`✖ Required PHP Module mcrypt not found!`

**Comment by cmuench** [comment]
Yes, but we need a  new logic in extension check to distinguish between version numbers, because the old Magento 2 version require `mcrypt`.

**Comment by cmuench** [comment]
@olivierchabert @martin-cod 
We will remove the requirement to mcrypt with release 4.0.0 of n98-magerun2.
