### ISSUE TITLE
Porting command: config:dump

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#49]
Dump merged xml config

**Comment by scottsb** [comment]
This is probably not worth completing, given the introduction of the new `config:dump` command that largely overlaps this introduced in Magento 2.2.

Also, there is this project which is very similar:
https://github.com/semaio/Magento2-ConfigImportExport

**Comment by cmuench** [comment]
We decided to have different "config:data" commands. M2 comes with more than one config file and type.
