### ISSUE TITLE
Command to list routes of an area

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#498]
A command which lists all available routes and frontnames could be useful.

**Comment by GautierDig** [comment]
To do the same as with `n98-magerun.phar config:dump frontend/routers` . Any news on this topic ?

**Comment by cmuench** [comment]
@GautierDig Yes. In M2 the route handling is different. That would be a nice feature for M2.
Contributions will be accepted. :-)

**Comment by gowrizrh** [comment]
@cmuench I'd be happy to contribute to this one. Can this issue be assigned to me?

**Comment by cmuench** [comment]
@gowrizrh done 😉

**Comment by gowrizrh** [comment]
@cmuench :) I've opened a PR for this
