### ISSUE TITLE
admin:user:create throws Exception

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#521]
```
Admin user: PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Console\Question\Question::getAutocompleterCallback() in phar:///opt/n98-magerun2/n98-magerun2.phar/vendor/symfony/console/Helper/QuestionHelper.php:119
Stack trace:
#0 phar:///opt/n98-magerun2/n98-magerun2.phar/vendor/symfony/console/Helper/QuestionHelper.php(85): Symfony\Component\Console\Helper\QuestionHelper->doAsk(Object(Symfony\Component\Console\Output\StreamOutput), Object(Symfony\Component\Console\Question\Question))
#1 phar:///opt/n98-magerun2/n98-magerun2.phar/vendor/symfony/console/Helper/QuestionHelper.php(451): Symfony\Component\Console\Helper\QuestionHelper->Symfony\Component\Console\Helper\{closure}()
#2 phar:///opt/n98-magerun2/n98-magerun2.phar/vendor/symfony/console/Helper/QuestionHelper.php(88): Symfony\Component\Console\Helper\QuestionHelper->validateAttempts(Object(Closure), Object(Symfony\Component\Console\Output\StreamOutput), Object(Symfony\Component\Console\Question\Question))
#3 /var/www/shop in phar:///opt/n98-magerun2/n98-magerun2.phar/vendor/symfony/console/Helper/QuestionHelper.php on line 119
```

**Comment by cmuench** [comment]
Seems to work in 4.0.3 and CE 2.3.4.

**Comment by luklewluk** [comment]
@cmuench It still doesn't work to me. Magerun 4.0.3 and Magento 2.3.4 CE, PHP 7.3.13.

**Comment by grafikchaos** [comment]
@cmuench same thing happens in Magerun 4.0.3, Magento 2.3.3 CE and PHP 7.2.24

**Comment by cmacdonald-au** [comment]
For us - this stems from an autoloader collision.

mage2.3.2:  "symfony/console": "~4.1.0"

**Comment by cmacdonald-au** [comment]
Turns out, it was `composer --optimize-autoloader` triggering the issue for us. The static classmaps were hard mapping the Question class to magento's and using that in favour of the classes within the phar.

nfi how to work around that one.

**Comment by cmuench** [comment]
@cmacdonald-au thanks for investigation. Good that we can reproduce the issue.
I think we should find a way that the shop can run with a optimized autoloader.

**Comment by cmuench** [comment]
@cmacdonald-au I think the bug can be fixed by forcing the n98-magerun2 autoloader to load the class before Magento can load the older version of the class. I patched that in the development version.

Can you verify that the bug is fixed?

`n98-magerun2.phar self-update --unstable`  -> update to current development version

**Comment by cmacdonald-au** [comment]
No worries, will give it a shot and see how we go.
