### ISSUE TITLE
n98-magerun for magento repository

### ISSUE THREAD

**Issue by TadeuRodrigues** [netz98/n98-magerun2#525]
When i tried using the oldest version 3.2.0 of the n98-magerun2 script it worked unlike the new version 4.0 it didn' work, it showed me an error for the magento version because it shows that i need to use the community edition 2.3 but i am using the repository version.

![Captura de tela de 2020-01-27 17-32-05](https://user-images.githubusercontent.com/1669081/73211589-4ed1e880-412b-11ea-8cdf-ab05dcea3fd2.png)

I'm using Inventory repository now this is why you can see 'dev-1.1-develop', that's the main branch of repository.

**Comment by cmuench** [comment]
@TadeuRodrigues We removed support for old Magento 2.2 in n98-magerun2 4.0.0.
Is "dev-1.1-develop" the version which is returned by Magento core?
Can you provide me a URL to the repository and branch where I can verify that?

**Comment by cmuench** [comment]
@TadeuRodrigues I was able to figure out what's the issue is. The kind of version detection has changed in Magento.
See `\Magento\Framework\App\ProductMetadata::getVersion`
I will try to find a fix for that.

**Comment by cmuench** [comment]
Fix is in develop version available and will be released as 4.0.3.
Please update to this version by running this:

`n98-magerun2.phar self-update --unstable`

**Comment by TadeuRodrigues** [comment]
@cmuench thank you so much, I'm checking now.

**Comment by cmuench** [comment]
@TadeuRodrigues 4.0.3 is also available since some seconds.
