### ISSUE TITLE
n98-magerun2 fails when running against 2.4-develop branch

### ISSUE THREAD

**Issue by ryanreeves-taxjar** [netz98/n98-magerun2#528]
Trying to run n98-magerun2 against the 2.4 develop branch fails the version check.  I suspect it fails because the 2.4 branch name starts with dev:  "dev-2.4-develop".  

![Screen Shot 2020-02-10 at 10 39 15 AM](https://user-images.githubusercontent.com/44789510/74174867-f8b47900-4bf1-11ea-97ff-a9e3253af805.png)

**Comment by cmuench** [comment]
@ryanreeves-taxjar Which version of n98-magerun2 you are running?

**Comment by cmuench** [comment]
@ryanreeves-taxjar This was already fixed in v4.0.3.
See #525
