### ISSUE TITLE
PHP Fatal Error on latest 4.0.3

### ISSUE THREAD

**Issue by tprocter1984** [netz98/n98-magerun2#531]
`PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Console\Question\Question::getAutocompleterCallback() in phar:///usr/local/bin/magerun2/vendor/symfony/console/Helper/QuestionHelper.php:119
Stack trace:
#0 phar:///usr/local/bin/magerun2/vendor/symfony/console/Helper/QuestionHelper.php(81): Symfony\Component\Console\Helper\QuestionHelper->doAsk(Object(Symfony\Component\Console\Output\StreamOutput), Object(Symfony\Component\Console\Question\Question))
#1 phar:///usr/local/bin/magerun2/src/N98/Magento/Command/Database/DumpCommand.php(500): Symfony\Component\Console\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\StreamOutput), Object(Symfony\Component\Console\Question\Question))
#2 phar:///usr/local/bin/magerun2/src/N98/Magento/Command/Database/DumpCommand.php(266): N98\Magento\Command\Database\DumpCommand->getFileName(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(N9 in phar:///usr/local/bin/magerun2/vendor/symfony/console/Helper/QuestionHelper.php on line **119`**

**Comment by cmuench** [comment]
Duplicate to #521
