### ISSUE TITLE
version check incorrectly fails

### ISSUE THREAD

**Issue by beargroup-jay** [netz98/n98-magerun2#534]
I'm attempting to run n98-magerun2 (installed as ~/bin/mr2) on a cpanel managed site, and acknowledge that this may be environment specific and not the tool. There is some php version management in place here, but is set to 7.2 for the domain in question.

```
$ php --version
PHP 7.2.28 (cli) (built: Mar 11 2020 18:01:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.9, Copyright (c) 2002-2019, by ionCube Ltd.

$ ~/bin/mr2 --version
ErrorException: PHP Version is lower than 7.2.0. Please upgrade your runtime.

$ php -r "echo PHP_VERSION;"
7.2.28
```
I'm not sure how to debug this further, I'll try an older version of the tool next, but curious if there's a way to tell which php version is being used by the phar. Thanks!

**Comment by beargroup-jay** [comment]
Using an older version of n98-magerun2 gets past that version check (or maybe doesn't have it) but Magento sees an older version of php.

    $ mr2 --version
    Magento supports PHP 7.1.3 or later.

You can close this one out, almost certainly an environment issue on my end, but curious if this has been seen before?

**Comment by cmuench** [comment]
@beargroup-jay We use PHP_VERSION constant to check the current version.

See: https://github.com/netz98/n98-magerun2/blob/879101c228bb7da41765ff9b4c186333125c135c/src/bootstrap.php#L8

I guess that the wrong version of PHP is used to start n98-magerun.
You can run n98-magerun with PHP binary prefixed.

Example:

` php n98-magerun2.phar`

If you omit php and marked the phar as executable, then the environment specific php is used.

We have this shebang in the phar file.

`#!/usr/bin/env php`

You should be able to test which php version is used by running:

`/usr/bin/env php`

**Comment by beargroup-jay** [comment]
Thanks for the very quick response! I had tried echoing out the PHP_VERSION before which gave 7.2.28, and running with explicit `php ~/bin/mr2` which still failed the php version check. Hadn't  tested `/usr/bin/env php` but that also give 7.2.28.

I'll go ahead and close this one out for now, almost certainly something funky with this environment, and will follow up if I figure it out. Thanks again, it's a great tool when the environment isn't misbehaving :)

**Comment by cmuench** [comment]
@beargroup-jay You could add "strace" in front of the call to see which files are loaded by the kernel.

**Comment by beargroup-jay** [comment]
I've found issues reported with both composer and wordpress (specifically phar files) not working with cpanel / EasyApache php versioning, seems they really want to use the php version defined as system default. Definitely not a n98-magerun2 issue.

Most straightforward fix is to change the system php version, but others report success with things like (this didn't work for me):
```
/opt/cpanel/ea-php72/root/usr/bin/php ~/bin/mr2 --version
```

* https://forums.cpanel.net/threads/using-composer-with-ea-php-cli-incorrect-php-version.635413/
* https://www.knownhost.com/wiki/control-panels/directadmin/wrong-php-version-detected-using-multiple-php-versions
