### ISSUE TITLE
Pass area code to sys:url:list

### ISSUE THREAD

**Issue by flavius** [netz98/n98-magerun2#537]
When executing

`n98 sys:url:list --add-all -- 1`

I get the error:

> In State.php line 153:
>                         
>   Area code is not set  

Using v4.0.4

**Comment by cmuench** [comment]
@flavius I tested the command in a Magento EE 2.3.4 and it works on my machine. Maybe there is an issue with some other module.

Can you give me more informations.
You can get the exception trace if you add the `-vvv` option.

**Comment by cmuench** [comment]
@flavius Any new information?
