### ISSUE TITLE
Support installation of 2.3.4

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#538]
$ n98-magerun2 install

		                  
	  Magento 2 Installation  
		                  

	Choose a magento version:
	  [1] magento-ce-2.3.3 
	  [2] magento-ce-2.3.2 
	  [3] magento-ce-2.3.1 
	  [4] magento-ce-2.3.0 

The recent Magento version is not supported, even in unstable branch

**Comment by amenk** [comment]
General question: Once https://travis-ci.org/github/netz98/n98-magerun2 finished will there be a .phar artifact available on travis or somewhere else?

**Comment by cmuench** [comment]
@amenk Yes, everything which is part of the develop branch is automatically published as n98-magerun2-dev.phar file.
Have a look here: https://files.magerun.net/
