### ISSUE TITLE
Porting command: customer:create

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#54]
Creates a new customer/user for shop frontend.

**Comment by cmuench** [comment]
Command is now available in develop branch

**Comment by ktomk** [comment]
Your develop branch was outdated. Please make this as a single commit or a PR.

**Comment by tkn98** [comment]
@cmuench: Thanks for porting, I just needed it :)

**Comment by cmuench** [comment]
It was a pleasure to serve you.
