### ISSUE TITLE
how to delete all subscribers in magento 2

### ISSUE THREAD

**Issue by mad1143** [netz98/n98-magerun2#542]
hi, I have magento 2.3.4 and I have 136500 newsletter subscribers, all SPAM. Can I delete all subscribers with magerun2?
In command list of magerun2 I didn't saw command delete.

Thank you!

**Comment by cmuench** [comment]
@mad1143 We do not offer a special command to delete newsletter subscribers.
You can delete everyone in `newsletter_subscriber` database table.
