### ISSUE TITLE
Magerun2 version 4.1.0 problem with the db dump and excluding tables

### ISSUE THREAD

**Issue by JelleGroenendal** [netz98/n98-magerun2#546]
We have been using Magerun for a while now as the go to tool for copying our database to our different environments.
We use db:dump with --exclude to remove the core_config_data and some other tables from the dump.
This used to work without fail but since 4.1.0 we have problems.

The command we use is:
`magerun2 db:dump --compression="gzip" --root-dir="site/location/" --exclude="table1 table2 table3" /tmp/dump.sql.gz`

The error we get:
`Too many arguments, expected arguments "command" "filename".`

When we reduce the exclude to only one table it works.

Our Magento version is 2.3.4

**Comment by cmuench** [comment]
@JelleGroenendal I was not able to reproduce the issue. In your example it looks for me that you are using a shell variable. Can you verify what's store in this variable?

**Comment by JelleGroenendal** [comment]
I edited my comment. The command was without $ (copy added it). We rolled back a version and it seems to work now.

To add some additional information.
We are on php 7.2.22 with mysql  Ver 14.14 Distrib 5.7.27-30, for Linux (x86_64) using  6.2

**Comment by cmuench** [comment]
@JelleGroenendal you rolled back a version of n98-magerun2 or of your shop?

**Comment by JelleGroenendal** [comment]
We went back with n98-magerun2 to version 4.0.4

**Comment by cmuench** [comment]
@JelleGroenendal We reworked some stuff in the db commands. Can you test the issue again?

**Comment by alex5513** [comment]
Same error on 4.5.0

![Capture d’écran 2021-06-07 à 20 48 25](https://user-images.githubusercontent.com/6359584/121072758-e5a7be00-c7d1-11eb-8ce1-676b1dec1beb.png)

**Comment by ktomk** [comment]
@alex5513: please edit-in the text-data next to the screenshot. thanks!

**Comment by alex5513** [comment]
@ktomk n98 db:dump --strip="url_rewrite* @development" --compression="gzip" project.sql

**Comment by cmuench** [comment]
@alex5513 Is "n98" the phar file? Sometimes that's an alias with some preconfiguration.

**Comment by cmuench** [comment]
No futher feedback. Feel free to re-open.
