### ISSUE TITLE
Sitemap Generate Error: "Area code is not set"

### ISSUE THREAD

**Issue by sprankhub** [netz98/n98-magerun2#550]
If I generate the sitemap via `bin/magento`, it just works:

```
$ bin/magento xmlsitemap:generate 1
Generation has been finished successfuly.
```

However, using n98-magerun2:

```
$ n98-magerun2.phar xmlsitemap:generate 1
```

this fails. In the error mail, the following error is shown:

```
Area code is not set
```

**Comment by cmuench** [comment]
@sprankhub Cannot find that command in Magento 2. Is that provided by a 3rd party module?

**Comment by sprankhub** [comment]
Sorry @cmuench, you are absolutely right.
