### ISSUE TITLE
db:dump produces COLUMN_STATISTICS error

### ISSUE THREAD

**Issue by callum-atwal** [netz98/n98-magerun2#571]
It is supposedly an error with mysqldump 8+ where a flag is enabled by default.

Searching this error online, it states that `mysqldump` should be ran with the flag `--column-statistics=0`.

Could this be added to the db:dump command? Or is there an existing workaround for this?

**Comment by cmuench** [comment]
@callum-atwal If we set this flag, is it then backwards compatible?

**Comment by callum-atwal** [comment]
I believe so. I will double check now but iirc the flag has always existed, just that now in recent versions of mysqldump, it is set to 1. 

Else we can add it as an option to the dump command and check the version of mysqldump if it is needed

**Comment by cmuench** [comment]
@callum-atwal I checked that. The option was introduced in the mysqldump for MySQL 8. Older clients will throw an error.

Tested that in my devbox and got `mysqldump: unknown variable 'column-statistics=0'`.
Nevertheless we have to find a solution for the upcoming Magento 2.4 release which provided official support for MySQL 8.

**Comment by callum-atwal** [comment]
Could this not be added as a db:dump optional command? But only if the mysqldump version is greater than 8 (sure there's a programmatic way of fetching this)?
It would still be a solution for those wanting to use the db: dump command and can be added to deploy scripts etc.

**Comment by cmuench** [comment]
@callum-atwal I did not disagree. :-)
Yes, we have to find a good solution. Maybe it's not so easy to find out the version of mysqldump (there are forks of MySQL).

**Comment by cmuench** [comment]
@callum-atwal We can run this `mysqldump --help | grep -q 'column-statistics'`.
If the option exists we get return code "0" otherwise "1".
If it exists, then we can run `mysqldump --skip-column-statistics`.

**Comment by callum-atwal** [comment]
Sorry, I meant that in a tone where I was suggesting :D 
Yep I like your solution, I was also thinking along the same lines as doing a `grep -c` and checking if `>0`. 
This would, however, force the user to run without column statistics, which may not be intended by the user. They might, for some reason, want this column statistics as part of the dump.

So I believe, by default, we should have it skip column statistics if it exists on the `mysqldump --help` output. If it does exist however, we could add a command such as `db:dump --keep-column-statistics` just in case such a user ever in the future wanted to _not_ skip dumping this data too.

(Did some limited research on what this new table is, it belongs to the information_schema and is meant to provide histogram data? Not sure why this would be enabled by default)

**Comment by cmuench** [comment]
@callum-atwal ok. We have some idea. Sadly I have no time to fix that in the next two weeks.

**Comment by callum-atwal** [comment]
I could submit a PR later on with these discussed changes if I have some spare time :+1:

**Comment by cmuench** [comment]
@callum-atwal :+1: 

I had already started with some implementation tests. Maybe you can re-use some of the code.

Created a gist: https://gist.github.com/cmuench/c6296eba71daea84d3e2dfa3c72daaa9

**Comment by Ig0r-M-magic42** [comment]
Any progress on this one ??
Hey @callum-atwal :)

**Comment by callum-atwal** [comment]
> Any progress on this one ??
> Hey @callum-atwal :)

Fancy seeing you here! Haha. Been busy these past few days, I'll submit a PR in the evening once I've tested my changes

**Comment by Ig0r-M-magic42** [comment]
I've worked around by having command output mysqldump command and then manually doing that.

**Comment by callum-atwal** [comment]
> I've worked around by having command output mysqldump command and then manually doing that.

Yep same here, although tedious to manually fetch credentials each time haha

Opened PR #586, these changes reflect what was discussed here
