### ISSUE TITLE
magerun2 failed to open stream: No such file or directory application.config.php

### ISSUE THREAD

**Issue by agrishin-th** [netz98/n98-magerun2#573]
magerun2 binary was copied to /usr/local/bin/magerun2 path.
Project path: /var/www/magento

I have a weird issue with magerun2 command. When I run 'magerun2' command from magento2 root directory I get a following issue:
bash-4.2# magerun2 
PHP Warning:  require(/var/www/magento/pub/setup/config/application.config.php): failed to open stream: No such file or directory in /var/www/magento/vendor/magento/framework/Console/Cli.php on line 72
PHP Fatal error:  require(): Failed opening required '/var/www/magento/pub/setup/config/application.config.php' (include_path='/var/www/magento/pub/generated/code:/var/www/magento/vendor/magento/zendframework1/library:.:/usr/share/pear:/usr/share/php') in /var/www/magento/vendor/magento/framework/Console/Cli.php on line 72

There are no errors if 'magerun2' command run from any other directories or if I set magento root explicitly 'magerun2 --root-dir /var/www/magento'

Version: n98-magerun2 4.1.0 by netz98 GmbH

**Comment by cmuench** [comment]
@agrishin-th Which Magento version are you using?

**Comment by cmuench** [comment]
Looks like the "pub" is wrong in the path.

**Comment by cmuench** [comment]
@agrishin-th Have you modified the "pub" path in your project?

**Comment by agrishin-th** [comment]
No, project is installed with composer from the scratch. "pub" directory is located in the project's root. 
Can this issue be related to docker environment? It happened inside docker container.

**Comment by agrishin-th** [comment]
Closing this issue, cant reproduce with version 4.4.0
