### ISSUE TITLE
db:drop --tables not clearing all tables

### ISSUE THREAD

**Issue by ioweb-gr** [netz98/n98-magerun2#579]
Whenever I try to clear the database tables using 

`n98-magerun2.phar db:drop --tables`

There's always a single table surviving the procedure. The table is `inventory_stock_1` 

Any ideas why?

```
/httpdocs$ n2 db:drop --tables -f
Dropped database tables 415 tables dropped

/httpdocs$ n2 db:drop --tables -f
Dropped database tables 1 tables dropped

/httpdocs$ n2 db:drop --tables -f
Dropped database tables 1 tables dropped

```

**Comment by cmuench** [comment]
@ioweb-gr yes, it's a db view. As we created that command there were only normal tables in a Magento shop. Maybe we should extend the command to drop the views as well.

**Comment by cmuench** [comment]
@ioweb-gr  I created a new feature request issue for this.
