### ISSUE TITLE
Porting command: dev:class:lookup

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#70]
Resolves a grouped class name

**Comment by robbieaverill** [comment]
With the introduction of plugins, perhaps class rewriting might become almost obselete?

**Comment by ktomk** [comment]
@robbieaverill  Well, I might imagine what you want to say, but if so from that standpoint I would tend to add as well that class rewriting should have been used as much as last resort (and by default: not at all) as much as using interceptors in Magento 2 :). 

I'm not yet profound with Magento 2 class rewrites so I can't say if it actually exists as it did in Magento 1. However Magento 2 does have class aliasing within the DI layer and that might come more close to what was the class rewrite in Magento 1. I'd say it's not that bad to have some commands related to that in the magerun2 toolchest. Perhaps `dev:class:lookup` is a well suited command name for such a functionality.

**Comment by robbieaverill** [comment]
Hi Tom,

Good point. Preference is still relevant for this command especially with
controllers, and the odd rewrite that persists or is needed for a
particular reason.

R

On Thursday, 17 December 2015, Tom Klingenberg <notifications@github.com>
wrote:

> @robbieaverill <https://github.com/robbieaverill> Well, I might imagine
> what you want to say, but if so from that standpoint I would tend to add as
> well that class rewriting should have been used as much as last resort (and
> by default: not at all) as much as using interceptors in Magento 2 :).
>
> I'm not yet profound with Magento 2 class rewrites so I can't say if it
> actually exists as it did in Magento 1. However Magento 2 does have class
> aliasing within the DI layer and that might come more close to what was the
> class rewrite in Magento 1. I'd say it's not that bad to have some commands
> related to that in the magerun2 toolchest. Perhaps dev:class:lookup is a
> well suited command name for such a functionality.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/netz98/n98-magerun2/issues/70#issuecomment-165366432>.
>


-- 
*Robbie Averill*
LA PETITE MANOUCHE - NZ Gypsy Jazz Guitar Duo
Phone: +64 27 321 4758
contact@lapetitemanouche.com
www.lapetitemanouche.com

**Comment by Vinai** [comment]
Reference https://github.com/dmanners/DavidAndVinai_PreferencesInfoCommand/

**Comment by cmuench** [comment]
Implemented as `dev:di:info` command.
