### ISSUE TITLE
ERROR 1044 (42000) at line 2144: Access denied for user 'foo'@'localhost' to database 'bar'

### ISSUE THREAD

**Issue by Eddcapone** [netz98/n98-magerun2#730]
## Your Question

* Source File: ?
* Line(s): ERROR 1044 (42000) at line 2144: Access denied for user 'foo'@'localhost' to database 'bar'
* Question:

I try to create a clone of my project, the database name of the clone is "bar".
I dumped the original database "foo" and now I try to import it to "bar", but I get:

**ERROR 1044 (42000) at line 2144: Access denied for user 'foo'@'localhost' to database 'bar'**

What can I do?

**Comment by cmuench** [comment]
@Eddcapone Sounds like a permission problem on your MySQL. Please check credentials in app/etc/env.php with a mysql client.

**Comment by Eddcapone** [comment]
@cmuench , no it was not a permission issue. The problem was, that the dump contained lines which tried to alter tables in the old database.

**Comment by cmuench** [comment]
@Eddcapone Thanks for the information. Can you create a new issue (feature request) with an example of such a SQL statement?

**Comment by Eddcapone** [comment]
@cmuench Yes, as soon as I will find such a dump I will add more informations. Unfortunatelly my software is unable to open such big dumps so it is hard.

**Comment by PascalBrouwers** [comment]
Got the same issue:
`ALTER DATABASE `xxx` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;`
