### ISSUE TITLE
config:env:set should support more then only string values

### ISSUE THREAD

**Issue by hostep** [netz98/n98-magerun2#766]
## Current Implementation
Currently, the command `config:env:set` only seems to support values that are always considered a string

## Suggested Enhancement
It would be neat if we can also set booleans, integers, arrays, ...

Example: I want to automate setting up this configuration in the `env.php` file:

```php
    "cron_consumers_runner" => [
        "cron_run" => true,
        "max_messages" => 1000,
        "consumers" => [
            "some.consumer.name"
        ]
    ],
```

Here's my best attempt at this using the current implementation:
```
magerun2 config:env:set cron_consumers_runner.cron_run true
magerun2 config:env:set cron_consumers_runner.max_messages 1000
magerun2 config:env:set cron_consumers_runner.consumers. some.consumer.name
```

This results in:
```php
    "cron_consumers_runner" => [
        "cron_run" => "true",
        "max_messages" => "1000",
        "consumers" => [
            "" => "some.consumer.name"
        ]
    ]
```

Which turns all values into a string and where we don't have the opportunity to set array values without a key (or multiple array values without an explicit key)

## Proposed solution
Instead of writing your own parser to verify if the values can be converted to a boolean, integer, array, ... somehow, and in order not to break backwards compatibility for people that rely on the current implementation, I would suggest to add a new flag where we can specify that the value we want to insert is in json format.
In json format the type can be explicity set by how you input it, so we could do something like the following and decoding the input with `json_decode($value, true)`:

```
magerun2 config:env:set --data-format=json cron_consumers_runner.cron_run true
magerun2 config:env:set --data-format=json cron_consumers_runner.max_messages 1000
magerun2 config:env:set --data-format=json cron_consumers_runner.consumers '["some.consumer.name"]'

# or even in one go:
magerun2 config:env:set --data-format=json cron_consumers_runner '{"cron_run":true,"max_messages":1000,"consumers":["some.consumer.name"]}'
```

Does this sounds like a good idea?

**Comment by ktomk** [comment]
well it sounds like a good addition, doesn't it? @hostep 

just while seeing it, this is what popped into my eye on first glance, just early feedback:

`--data-format=json` -> `--input-format=json-text`

(`--format` as per Sf Console is output format IIRC, so maybe make more clear as "data" can mean quite a lot, it is about input (or parameter?))

(formally this is called json text, not json, with a potential benefit it is clear it is all a string)

the even in one go thing I guess is a sweet spot. If it would additionally support concatenated json objects and reading from file and standard input would be golden.

just my 2 cents, no need from my end to see anything of this obligatory or something, just ideas.
