### ISSUE TITLE
script:repo:list and script:repo:run too slow and using much memory

### ISSUE THREAD

**Issue by a-dite** [netz98/n98-magerun2#819]
## Describe the bug

When running "script:repo:list" in a Magento 2 root - it takes too long (on my system about 1 minute) to get an output of existing scripts. Also the "script:repo:run" command takes too long until starting executing (tested with echo command as first directive in the .magerun script).

## Expected behaviour

"script:repo:list" shows the list of the project specific scripts in seconds, but not minute(s)
"script:repo:run" needs seconds, not minute(s) to start execution of the first command in the .magerun script.

## Steps to reproduce the issue

1. Create a .magerun script
2. run script:repo:list and wait until output, counting the time with a timer
3. run "script:repo:run yourscript" and before that add an echo command at beginning of the script, wait for the output of echo command, counting the time with a timer
4. trace the execution with xdebug tracing - one will see that the directory iteration uses about 1GB RAM
5. run command with "strace mr2 ... " - one will see the process reading in dev, vendor and other subfolders of Magento

## Technical details

- Host Machine OS (Windows/Linux/Mac): Mac
- DDEV Docker Container "web" (Linux)
- Magerun2 4.7.0
- Magento EE 2.4.2-p1

**Comment by cmuench** [comment]
I excluded a list of folders. We have now a config to add additional folder to speed up the process.
See https://github.com/netz98/n98-magerun2/blob/develop/config.yaml#L24

**Comment by cmuench** [comment]
Fix will be released with v4.8.0
