### ISSUE TITLE
Terminal broken after DB import

### ISSUE THREAD

**Issue by jeroenvermeulen** [netz98/n98-magerun2#823]
## Describe the bug

Often after importing a backup, the terminal does no longer work.
We are using iTerm with fairly default settings.
The problem is probably caused by the `pv` tool which is used to display the progress bars.
When you try to use the terminal session after the import you don't see what you type. If you press <kbd>Enter</kbd> the prompts don't appear on a new line but after each other.

## Expected behaviour

Being able to keep using the terminal session after a N98 import.

## Steps to reproduce the issue

![Screenshot 2021-09-09 at 15 59 34](https://user-images.githubusercontent.com/658024/132699907-5764e379-b433-4229-99c2-419c7034b62f.png)

## Technical details

- n98-magerun2 4.7.0 by netz98 GmbH
- Ubuntu 20.04 LTS
- Linux argon.magehost.pro 5.11.xxxxx xxx~20.04.1-Ubuntu SMP xxxx x86_64 x86_64 x86_64 GNU/Linux

## Possible Fix

Fixable by executing `stty echo`

## Additional context

I will contribute a fix.

**Comment by cmuench** [comment]
@jeroenvermeulen thanks
