### ISSUE TITLE
Porting command: dev:module:observer:list

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#83]
Lists all registered observers

**Comment by cmuench** [comment]
Thanks. Can you commit your config.yaml? The new command is currently missing there.

**Comment by EliasZ** [comment]
Ah, I see. I am only using the testing framework to execute commands to verify them so I didn't even notice that file required updating. How do you run the actual n98-magerun2 tool from the command line during development?

**Comment by cmuench** [comment]
I use "bin/n98-magerun2" inside a Magento 2 installation.
Additionally i created an alias in my .bashrc file.

alias n98-magerun2-dev='php /<path_to_magerun>/bin/n98-magerun2'

**Comment by cmuench** [comment]
`dev:module:observer:list` command is still missing in config.yaml. Should i add it?
