### ISSUE TITLE
Removing the definer doesn't work in all cases

### ISSUE THREAD

**Issue by alinalexandru** [netz98/n98-magerun2#834]
## Describe the bug

Using `db:dump` command should remove the definer from triggers, functions and procedures
Actually, the sed expression doesn't cover all the cases

```bash
### Works
echo '/* 50017 DEFINER=`user`@`111.22.33.44`*/' | LANG=C LC_CTYPE=C LC_ALL=C sed -e 's/DEFINER[ ]*=[ ]*[^*]*\*/\*/'

### Does't work
echo 'CREATE DEFINER=`test`@`localhost` FUNCTION' | LANG=C LC_CTYPE=C LC_ALL=C sed -e 's/DEFINER[ ]*=[ ]*[^*]*\*/\*/
```

## Expected behaviour

Instead of removing the definer, we can rename it to CURRENT_USER

## Steps to reproduce the issue

1. Run `db:dump` command

## Technical details

- Host Machine OS (Windows/Linux/Mac):

## Possible Fix
This sed expression covers all the cases, because it renames the definer, instead of trying to remove it.

```
s/DEFINER[ ]*=[ ]*`[^`]+`@`[^`]+`/DEFINER=CURRENT_USER/g
```

**Comment by cmuench** [comment]
@alinalexandru Thanks for contribution. Works like a charm.
