### ISSUE TITLE
Porting command: dev:di:preferences:list

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#85]
Lists all magento rewrites

**Comment by cmuench** [comment]
Command is not relevant in M2.

**Comment by sprankhub** [comment]
Wouldn't it still be helpful to have a command like `dev:module:preference:list`?

**Comment by cmuench** [comment]
> Wouldn't it still be helpful to have a command like `dev:module:preference:list`? I was just looking for this :D

Yes, of course.
Preferences are similar to the old rewrites.
There is already the command `dev:di:info` to resolve a single inerface/class.
A list is helpful for investigations.
I agree that `dev:module:preference:list` is the better name.

**Comment by sprankhub** [comment]
Wow, thanks! That was fast! I think we can resolve this issue, then :)
