### ISSUE TITLE
Issues with the download server

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#855]
More often then not we get a "HTTP/2 stream 0 was not closed cleanly" in our docker builds.

This one ran today at 05:07 GMT+1

	Step 15/40 : RUN if php -r 'if(PHP_VERSION_ID >= 70200) exit(1);'; then         export MAGERUN_VERSION="3.2.0";         export MAGERUN_SHASUM="5b5b4f7a857f7716950b6ef090c005c455d5e607f800a50b7b7aefa86d1c4e36";     fi     && curl -sS https://files.magerun.net/n98-magerun2-$MAGERUN_VERSION.phar --output n98-magerun2.phar     && echo "$MAGERUN_SHASUM  n98-magerun2.phar"| shasum -a 256 -c 1>/dev/null     && chmod +x ./n98-magerun2.phar     && mv n98-magerun2.phar /usr/bin/n98-magerun2     && ln /usr/bin/n98-magerun2 /usr/local/bin/n98-magerun2
	 ---> Running in 485020c6d594
	curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

It's not a big deal as retrying usually works. I just wanted to notice you :-) Maybe the system updates kicks in at this time and we should schedule the builds at another time?

**Comment by cmuench** [comment]
@amenk There is no system update ongoing on our side. We use a Cloudflare CDN to serve the files. Maybe there is an issue.
For Europe I cannot see any outage.
Did also some test with curl and got no errors.

**Comment by cmuench** [comment]
@amenk Can you try to disable http/2 in your test scenario? There is a option `--http1.1` to downgrade.

**Comment by amenk** [comment]
The problem is that it is not reproducible .. it just happens sometimes... 
We can as well close this, it's not affecting us much - just wanted to "document" it.
If it is cloudflare it might be also their bot detection as we build docker images for 4 different PHP versions and some work, some fail?

**Comment by amenk** [comment]
Also not reproducible with

	curl  https://files.magerun.net/n98-magerun2-3.2.0.phar --output /tmp/foo & curl  https://files.magerun.net/n98-magerun2-3.2.0.phar --output /tmp/foo & curl  https://files.magerun.net/n98-magerun2-3.2.0.phar --output /tmp/foo & curl  https://files.magerun.net/n98-magerun2-3.2.0.phar --output /tmp/foo & curl  https://files.magerun.net/n98-magerun2-3.2.0.phar --output /tmp/foo & curl  https://files.magerun.net/n98-magerun2-3.2.0.phar --output /tmp/foo

**Comment by cmuench** [comment]
Sounds strange. We also download the phar files in our build process. Never had issues with that. I checked the cloudflare dashboard and saw that we serve ~95% of the phar files from cache. I will revalidate the cache. Maybe there is in an issue in the cache?

**Comment by cmuench** [comment]
@amenk I purged the entire cloudflare cache of files.magerun.net.

**Comment by ktomk** [comment]
@amenk  Please for anything network related in a stable build - if it still relies on network resources - re-build on failure. The network is not always fully available (and resources are only eventually consistent) so I think this is merely a build process issue than an issue with the Magerun of the project itself.

Otherwise please provide a clear way to reproduce.. Issues on the network - if in doubt - are likely on your end.

**Comment by ktomk** [comment]
> We can as well close this
