### ISSUE TITLE
Where to download what version for PHP 7.2 support?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [netz98/n98-magerun2#891]
Your readme does not say what version are for which PHP version e.g. 7.2

Neither does files.magerun.net.
https://files.magerun.net/

Could be nice if this was clearly listed?
Or maybe it is and I'm just not seeing it.

Cheers,

```
We support the following PHP Versions:

PHP 7.4
PHP 7.3
PHP 7.2 (only with older versions, available as phar)
```

```
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 7.3.0". You are running 7.2.34-24+ubuntu18.04.1+deb.sury.org+1.

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0". You are running 7.2.34-24+ubuntu18.04.1+deb.sury.org+1. in phar:///var/www/vhost/magento2/n98-magerun2.phar/vendor/composer/platform_check.php on line 24
```

**Comment by LiamKarlMitchell** [comment]
I downloaded an older one which appeared to work.

[n98-magerun2-3.1.0.phar](https://files.magerun.net/n98-magerun2-3.1.0.phar)

**Comment by cmuench** [comment]
@LiamKarlMitchell You are right. I will add a hint, tomorrow.
We dropped support for Magento 2.2 with v4.0.0.
https://magerun.net/v4-0-0-has-landed/

You can also try v3.2.0

**Comment by cmuench** [comment]
@LiamKarlMitchell I updated the README in the project with more details.
Maybe the Composer dist package is also interesting for you.

https://github.com/netz98/n98-magerun2#install-the-phar-via-composer

**Comment by cmuench** [comment]
Also added a table at https://files.magerun.net/#compatibility
