### ISSUE TITLE
Porting command: dev:template-hints

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#91]
Toggles template hints

**Comment by cmuench** [comment]
Ported

**Comment by agoeurysky** [comment]
@cmuench are you sure this command works ?
This command adds a config entry with path `dev/debug/template_hints`, but the Magento2 path seems to be `dev/debug/template_hints_storefront` and `dev/debug/template_hints_admin`.
Thanks.

**Comment by tommypyatt** [comment]
@agoeurysky: I think this changed from 2.0 -> 2.1. I have added a PR to #230 that prospectively fixes this.

**Comment by agoeurysky** [comment]
@tommypyatt,
no, I tested and posted the comment for Magento 2.0 :)
Thanks for your PR.

**Comment by ktomk** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.
