### ISSUE TITLE
Warning: file_exists(): Unable to find the wrapper "phar"

### ISSUE THREAD

**Issue by rafaelstz** [netz98/n98-magerun2#914]
## Describe the bug

Suddenly I start to have these two issues below in different environments that I used to run with no problems. I have phar extension installed.

```
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0". You are running 7.2.26. in phar:///var/www/html/vendor/n98/magerun2-dist/n98-magerun2/vendor/composer/platform_check.php on line 24
```

The outdated version of Magerun2 (e.g. v3 or v2) shows this error below.

```
  [Exception]                                                                                                                                                                                             
  Warning: file_exists(): Unable to find the wrapper "phar" - did you forget to enable it when you configured PHP? in phar:///var/www/html/n98-magerun2.phar/vendor/composer/ClassLoader.php on line 384 
```

## Expected behaviour

Show commands.

## Steps to reproduce the issue

1. I ran the installation via Curl command and I've tried the Composer install too.
2. Run it on different servers and Magento versions.

## Technical details

- Linux servers (Ubuntu and Debian)
- PHP 7.2 and PHP 7.3
- Magento 2.3

**Comment by cmuench** [comment]
@rafaelstz which version of n98-magerun are you using in your PHP 7.2 environment?
PHP 7.2 is a EOL PHP version which is supported by us until v4.7.0.

**Comment by cmuench** [comment]
@rafaelstz Any update?

**Comment by rafaelstz** [comment]
Hi @cmuench,

I was trying Magerun2 v2.2 and Magerun2 v3.0.
I checked the compatibilities in the link you sent and it worked with **Magerun2 v3.2** and **Magerun2 4.7**.

Thank you!

**Comment by cmuench** [comment]
@rafaelstz ok. Great.
