### ISSUE TITLE
Porting command: dev:template-hints-blocks

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#92]
Toggles template hints block names

**Comment by EliasZ** [comment]
This, and many other commands, is a case of toggling a config value. As you already have `config:set` and `config:get` you could create an abstract class which proxies into these commands instead of completely recreating the `AbstractMagentoStoreConfigCommand`.

**Comment by cmuench** [comment]
Yes, thanks for hint. I didn't notice that we duplicated the code in the abstract class.

**Comment by cmuench** [comment]
Ported.
