### ISSUE TITLE
Php 8.1 support

### ISSUE THREAD

**Issue by fooman** [netz98/n98-magerun2#926]
## Current Implementation

```
magerun2 sys:url:list

In ErrorHandler.php line 61:

  Deprecated Functionality: Method ReflectionParameter::getClass() is deprecated in phar:///usr/local/bin/magerun2/src/N98/Util/Console/Helper/InjectionHelper.php on line 91
```

## Suggested Enhancement
Php 8.1 support
This seems to be a solution
https://php.watch/versions/8.0/deprecated-reflectionparameter-methods#getClass

## Expected Benefits
With Magento getting php 8.1 support soon it would be great if n98-magerun2 could also support that environment.

**Comment by cmuench** [comment]
@fooman Yes, we will start to test n98-magerun2 in PHP 8.1, soon.

**Comment by cmuench** [comment]
@fooman ok. Found a solution to do a test run on local machine with public github `2.4-develop` branch.

**Comment by cmuench** [comment]
Can reproduce it.
![image](https://user-images.githubusercontent.com/211294/149621158-138e505d-8be4-402b-9aae-f66739afc8fb.png)

**Comment by cmuench** [comment]
@fooman did some changes 😁
