### ISSUE TITLE
Exclude system_config_snapshot in db:dump --strip=@development by default?

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#957]
## Feature description

Exclude the table system_config_snapshot

## Problem and motivation

It can be a good practise to store sensitive config data such API keys in `app/etc/env.php` to not have them in the database.
Problem here is, that it will still be present in `system_config_snapshot`. So we might just exclude this table.

## Is this something you're interested in working on

Yes

## Discussion

I do currently not know if it causes problems to exclude this table. It might need `app:config:import` calls when importing.
That is why I put this up for discussion.

Also it might be B/C breaking if add this table to the standard configuration. An alternative is to specific it manually on each dump.

**Comment by amenk** [comment]
@cmuench what do you think? Should we change that preset in the next n98-magerun2 version?

**Comment by cmuench** [comment]
@amenk Yes, we should skip the data for `@development`. We can try it out if there are problems without the table before we release it.

**Comment by amenk** [comment]
Making a PR ...

**Comment by amenk** [comment]
@cmuench  I think I would add it to @stripped ?

**Comment by cmuench** [comment]
@amenk yes
