### ISSUE TITLE
version 5.0.0 - broken with guzzle dependency chain

### ISSUE THREAD

**Issue by convenient** [netz98/n98-magerun2#964]
## Describe the bug

- Magento 2.3 requires guzzle 6 https://github.com/magento/magento2/blob/ad91bd9eb0a691dc72bb8d794484dbd0b5a2a3f0/composer.json#L39
- Magerun 5 requires guzzle 7 https://github.com/netz98/n98-magerun2/blob/376f301a2bcffd6239040c0fd71f424d0b403e32/composer.json#L34
- When magerun boots it autoloads in  `./vendor/guzzlehttp/guzzle/src/functions.php` from the phar
- When the magento code boots it does not autoload in the magento `./vendor/guzzlehttp/guzzle/src/functions.php` because there are `function_exists` safety checks
- This means we can have guzzle 6 magento code trying to run with guzzle 7 magerun functions

I spotted this in one of our clients as we have a console command which uses guzzle to ping an endpoint for activity. Useful for testing auth credentials etc.

In this case because the console commands from magento are merged with magerun, the entirety of magerun is broken for that clients code base.

## The error

```
$ ./n98-magerun2-5.0.0.phar --version | head -5
PHP Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in phar:///Users/lukerodgers/src/magerun-broken/n98-magerun2-5.0.0.phar/vendor/guzzlehttp/guzzle/src/functions.php:61
Stack trace:
#0 /Users/lukerodgers/src/magerun-broken/vendor/guzzlehttp/guzzle/src/HandlerStack.php(42): GuzzleHttp\choose_handler()
#1 /Users/lukerodgers/src/magerun-broken/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create()
#2 /Users/lukerodgers/src/magerun-broken/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): GuzzleHttp\Client->__construct(Array)
#3 /Users/lukerodgers/src/magerun-broken/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('GuzzleHttp\\Clie...', Array)
#4 /Users/lukerodgers/src/magerun-broken/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('GuzzleHttp\\Clie...')
#5 /Users/lukerodge in phar:///Users/lukerodgers/src/magerun-broken/n98-magerun2-5.0.0.phar/vendor/guzzlehttp/guzzle/src/functions.php on line 61

Fatal error: Uncaught Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in phar:///Users/lukerodgers/src/magerun-broken/n98-magerun2-5.0.0.phar/vendor/guzzlehttp/guzzle/src/functions.php on line 61

Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in phar:///Users/lukerodgers/src/magerun-broken/n98-magerun2-5.0.0.phar/vendor/guzzlehttp/guzzle/src/functions.php on line 6
```

## Expected behaviour

On clients with guzzlehttp/client within a console command dependency chain i can run `magerun --version` 

## Steps to reproduce the issue

1. Go to https://github.com/convenient/magerun-5-broken#to-repo
2. Follow instructions there 
    
    
## Possible Fix

Not sure, but you've faced similar problems back here https://github.com/netz98/n98-magerun/issues/938#issuecomment-327143700 , symfony/console was the issue at that time. But that was changed by changing the ordering of how things were loaded i think.

In this case maybe its okay for v5 magerun to not play with with magento 2.3 which will be EOL soon enough.

In my case I can work around the console command breakages by doing something like `use GuzzleHttp\Client\Proxy` I think, that'll stop it eagerly instantiating and breaking the full magerun tool.

Not sure if its even worth yous fixing or if its better for this to be tracked and closed here and let edge cases like ourselves for 2.3 just work it out 🤷  at least now some google indexable might help anyone else seeing the same error

**Comment by cmuench** [comment]
@convenient Thanks for the report. We had a simular issue today in a customer project. 
It's interesting, because the functional tests for Magento 2.3 are still OK.
Which exact Magento 2.3 version are you using to reproduce the issue?

**Comment by cmuench** [comment]
@convenient I just tested in a Magento 2.3.7-p2 with Guzzle 6.3.3 (manually downgraded) and I cannot reproduce the issue.

**Comment by cmuench** [comment]
@convenient I will try it with the code in your repository next.

**Comment by cmuench** [comment]
@convenient Thanks. Can reproduce it with your example module.

**Comment by convenient** [comment]
@cmuench I think you need to have some custom code to trigger it, 

https://github.com/convenient/magerun-5-broken/blob/c499955aecfc7be5884d3ca0579e453d378cfead/app/code/Convenient/Example/Console/ExampleCommand.php#L21

having it injected here is enough.

**Comment by convenient** [comment]
ah @cmuench good :) glad you can reproduce.

we're working around it now by rolling magerun back for this client, but next week i'll wrap up my proxy hack a bit better. if the guzzle dep is never constructed it'll never fatal like this.

**Comment by cmuench** [comment]
> ah @cmuench good :) glad you can reproduce.
> 
> we're working around it now by rolling magerun back for this client, but next week i'll wrap up my proxy hack a bit better. if the guzzle dep is never constructed it'll never fatal like this.

I will replace all download operations in n98-magerun2 with a alternative HTTP library which does not conflict with Magento.

**Comment by cmuench** [comment]
@convenient Hotfix 5.0.1 is released.
