### ISSUE TITLE
InstalledVersions.php could not be opened

### ISSUE THREAD

**Issue by frostblogNet** [netz98/n98-magerun2#968]
magerun 5.0.1 
magento/product-enterprise-edition 2.4.3-p2
justbetter/magento2-sentry 2.6.0

## Describe the bug

bin/magento cache:flush works as expected but when I try to run it with magerun the following error occur

n98-magerun2 cache:flush

```
 Warning: require(phar:///usr/local/bin/n98-magerun2.phar/vendor/composer/installed.php): failed to open stream: phar error: "vendor/composer/installed.php" is not a file in phar "/usr/local/bin/n98-magerun2.phar" in phar:///usr/local/bin/n98-magerun2.phar/vendor/composer/InstalledVersions.php on line 343  
```

## Expected behaviour

Flushing the magento caches.

## Steps to reproduce the issue

- Install magento 
- require justbetter/magento2-sentry 2.6.0
- run magerun with any command

**Comment by cmuench** [comment]
Fix by PR #966
