### ISSUE TITLE
strftime deprecated in php 8.1

### ISSUE THREAD

**Issue by hatimeria-artur-jewula** [netz98/n98-magerun2#969]
## Describe the bug

When using magerun with magento 2.4.4 and php 8.1 there is a bug when executing `sys:cron:run` command:
``` 
Deprecated Functionality: Function strftime() is deprecated in phar:///n98-magerun.phar/src/N98/Magento/Command/System/Cron/RunCommand.php on line 62
```

## Expected behaviour

command runs without errors

## Steps to reproduce the issue

1. Install magento 2.4.4 with PHP 8.1
2. Run `sys:cron:run` command

## Technical details

- Any system

## Possible Fix

Possible changes are described here: https://php.watch/versions/8.1/strftime-gmstrftime-deprecated

**Comment by cmuench** [comment]
@hatimeria-artur-jewula thanks. We will fix it.

**Comment by cmuench** [comment]
@hatimeria-artur-jewula I merged a fix. You can test it by upading to development version by `n98-magerun2.phar self-update --unstable`.

**Comment by hatimeria-artur-jewula** [comment]
Yes, working on my end
