### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Parser.php:532

### ISSUE THREAD

**Issue by r-martins** [netz98/n98-magerun2#971]
## Describe the bug
After installing n98 on a Magento 2.4.4 server + PHP 8.1, and simply run `./n98-magerun2.phar` with any command, I get a PHP Exception.

> $ ./n98-magerun2.phar
> PHP Fatal error:  Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Parser.php:532
> Stack trace:
> #0 phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Parser.php(532): abs()
> #1 phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Parser.php(258): Symfony\Component\Yaml\Parser->parseValue()
> #2 phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Parser.php(320): Symfony\Component\Yaml\Parser->doParse()
> #3 phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Parser.php(151): Symfony\Component\Yaml\Parser->parseBlock()
> #4 phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Parser.php(320): Symfony\Component\Yaml\Parser->doParse()
> #5 phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Parser.php(246): Symfony\Component\Yaml\Parser->parseBlock()
> #6 phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Parser.php(320): Symfony\Component\Yaml\Parser->doParse()
> #7 phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Parser.php(246): Symfony\Component\Yaml\Parser->parseBlock()
> #8 phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Parser.php(320): Symfony\Component\Yaml\Parser->doParse()
> #9 phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Parser.php(246): Symfony\Component\Yaml\Parser->parseBlock()
> #10 phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Parser.php(78): Symfony\Component\Yaml\Parser->doParse()
> #11 phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Yaml.php(64): Symfony\Component\Yaml\Parser->parse()
> #12 phar:///var/www/html/n98-magerun2.phar/src/N98/Magento/Application/ConfigFile.php(93): Symfony\Component\Yaml\Yaml::parse()
> #13 phar:///var/www/html/n98-magerun2.phar/src/N98/Magento/Application/ConfigurationLoader.php(162): N98\Magento\Application\ConfigFile->toArray()
> #14 phar:///var/www/html/n98-magerun2.phar/src/N98/Magento/Application/ConfigurationLoader.php(112): N98\Magento\Application\ConfigurationLoader->loadDistConfig()
> #15 phar:///var/www/html/n98-magerun2.phar/src/N98/Magento/Application/Config.php(257): N98\Magento\Application\ConfigurationLoader->getPartialConfig()
> #16 phar:///var/www/html/n98-magerun2.phar/src/N98/Magento/Application.php(380): N98\Magento\Application\Config->loadPartialConfig()
> #17 phar:///var/www/html/n98-magerun2.phar/src/N98/Magento/Application.php(315): N98\Magento\Application->init()
> #18 /var/www/html/n98-magerun2.phar(8): N98\Magento\Application->run()
> #19 {main}
>   thrown in phar:///var/www/html/n98-magerun2.phar/vendor/symfony/yaml/Parser.php on line 532

## Expected behaviour
See a list of n98 commands.

## Steps to reproduce the issue
Simply install it in the magento folder as per official instructions.

## Technical details

- Host Machine OS (Windows/Linux/Mac): Linux / Ubuntu 20.04
- PHP 8.1
- Magento 2.4.4 (upgraded from 2.4.2-p2)

**Comment by cmuench** [comment]
@r-martins thanks for reporting.
I can this currently not reproduce.
Maybe there is a user configuration involved.
Please verify that by `n98-magerun2.phar --skip-config`.

**Comment by r-martins** [comment]
I was about to remove my issue, because it was my mistake, but now I saw your commend.
For some dumb reason I didn't realize I installed it again, and then I got 2 versions of n98, and was executing a 2020 version with PHP 8.1.
Sorry for that. 🤦‍♂️
