### ISSUE TITLE
"Can't drop database" error since magerun 4.8.0 (db:import --drop became more strict, on purpose, or by accident?)

### ISSUE THREAD

**Issue by hostep** [netz98/n98-magerun2#992]
## Describe the bug

Hi folks

We have a certain workflow, that we don't use a lot, but occasionally have to execute.
Apparently this started breaking after we upgraded magerun2 to a more recent version.

After testing some versions of magerun2, it appears this started happening in version 4.8.0 and still worked fine in 4.7.0

So the bug itself (might not be considered a bug, but it introduced a backwards incompatibility):
```bash
# have an app/etc/env.php file pointing to a database 'whatever' that doesn't exist
$ magerun2 db:import --drop some-db-dump.sql


  Import MySQL Database



In DatabaseHelper.php line 728:

  SQLSTATE[HY000]: General error: 1008 Can't drop database 'whatever'; database doesn't exist


```
This happens in versions 4.8.0 and 5.1.0

## Expected behaviour

```bash
# have an app/etc/env.php file pointing to a database 'whatever' that doesn't exist
$ magerun2 db:import --drop some-db-dump.sql


  Import MySQL Database


Dropped database whatever
Created database whatever
Importing SQL dump some-db-dump.sql to database whatever
...
```

This happens in versions 4.7.0 and earlier.
If the database didn't exist, the `db:import --drop` command simply ignored it and just created it without erroring out.

## Steps to reproduce the issue

See above

## Technical details

- Host Machine OS (Windows/Linux/Mac): Mac/Linux

## Possible Fix

We work around it in this way now, but it's a bit clunky:

```bash
$ magerun2 db:drop --force; true
$ magerun2 db:create
$ magerun2 db:import some-db-dump.sql
```

## Additional context

N/A

**Comment by ktomk** [comment]
This might have changed from a warning to an error on the SQL level and is therefore an issue now?

In any case it makes sense to have a `DROP DATABASE IF EXISTS carton_bleue` from my end.

[ref](https://github.com/netz98/n98-magerun2/blob/3e98fb644557ffc222cd7202288e8b63ac3b0cdf/src/N98/Util/Console/Helper/DatabaseHelper.php#L728)

And proper quoting now looking at it.

**Comment by cmuench** [comment]
@hostep Just followed the idea of @ktomk and added the exists check.
Can you try the phar of the PR?

Can be downloaded as artifact here: https://github.com/netz98/n98-magerun2/actions/runs/2339706448

**Comment by hostep** [comment]
Nice, works perfectly fine again like this. Good idea @ktomk!
